@startuml

component [Core] as core
component [SSLplus] as sslplus
component [Shapes] as shapes
component [Message\nBus] as msgbus
component [EGLplus] as eglplus
component [OGLplus] as oglplus
component [OALplus] as oalplus
component [GUIplus] as guiplus
component [Entity\nComponent\nSystem] as ecs
component [Application] as app

sslplus --> core
shapes --> core
msgbus --> sslplus
msgbus --> core
eglplus --> core
oglplus --> core
oglplus --> shapes
oalplus --> core
guiplus --> core
ecs --> core
app --> core
app --> eglplus
app --> oglplus
app --> oalplus
app --> guiplus
app --> shapes
app --> msgbus

@enduml
