eagine::bitfield< Bit > Class Template Reference
EAGine (0.87.0) a C++ wrapper for rendering APIs
eagine::bitfield< Bit > Class Template Reference
Type utilities
Class for manipulating and testing a group of enumeration-based bits.
#include <eagine/bitfield.hpp>
Public Types
using bit_type = Bit
The enumeration type specifying individual bit values.
using value_type = std::underlying_type_t< bit_type >
The Integral type used to store the bits.
Public Member Functions
constexpr bitfield () noexcept=default
Default constructor.
constexpr bitfield (const value_type bits) noexcept
Explicit construction from the underlying interger type value.
constexpr bitfield (const bit_type _bit) noexcept
Construction from the bit enumeration type value.
constexpr auto is_empty () const noexcept
Indicates that none of the bits are set.
constexpr operator bool () const noexcept
Indicates that some of the bits are set.
constexpr operator value_type () const noexcept
Explicit conversion to the underlying integer value type.
constexpr auto bits () const noexcept -> value_type
Returns the bits in the underlying integer value type.
constexpr auto has (const bit_type bit) const noexcept
Tests if the specified bit is set.
constexpr auto has_not (const bit_type bit) const noexcept
Tests if the specified bit is not set.
template<typename... B>
constexpr auto has_all (const bit_type bit, B... bits) const noexcept -> bool requires(all_are_same_v< bit_type, B... >)
Tests if all of the specified bits are set.
template<typename... B>
constexpr auto has_any (const bit_type bit, B... bits) const noexcept -> bool requires(all_are_same_v< bit_type, B... >)
Tests if any of the specified bits are set.
template<typename... B>
constexpr auto has_none (const bit_type bit, B... bits) const noexcept -> bool requires(all_are_same_v< bit_type, B... >)
Tests if none of the specified bits are set.
constexpr auto has_only (const bit_type bit) const noexcept
Tests if only the specified bit is set.
constexpr auto has_at_most (const bit_type bit) const noexcept
Tests if at most the specified bit is set (or is empty).
auto operator|= (const bitfield b) noexcept -> bitfield &
Bitwise-or operator.
auto operator&= (const bitfield b) noexcept -> bitfield &
Bitwise-and operator.
auto set (const bit_type b) noexcept -> bitfield &
Sets the specified bit.
auto clear (const bit_type b) noexcept -> bitfield &
Clears the specified bit.
auto clear () noexcept -> bitfield &
Clears all bits.
Friends
constexpr friend auto operator== (const bitfield a, const bitfield b) noexcept
Equality comparison.
constexpr friend auto operator!= (const bitfield a, const bitfield b) noexcept
Nonequality comparison.
constexpr friend auto operator| (const bitfield a, const bitfield b) noexcept -> bitfield
Bitwise-or operator.
constexpr friend auto operator& (const bitfield a, const bitfield b) noexcept -> bitfield
Bitwise-and operator.
constexpr friend auto operator~ (const bitfield b) noexcept -> bitfield
Bit inversion operator.
Detailed Description
template<typename Bit>
class eagine::bitfield< Bit >
Class for manipulating and testing a group of enumeration-based bits.
Member Function Documentation
clear() [1/2]
template<typename Bit > auto eagine::bitfield< Bit >::clear () -> bitfield& inline noexcept
Clears all bits.
Postcondition
is_empty()
clear() [2/2]
template<typename Bit > auto eagine::bitfield< Bit >::clear (const bit_type b) -> bitfield& inline noexcept
Clears the specified bit.
See also
set
has()
template<typename Bit > constexpr auto eagine::bitfield< Bit >::has (const bit_type bit) const inline constexpr noexcept
Tests if the specified bit is set.
See also
has_not
has_only
has_all
has_any
has_none
has_at_most
Referenced by eagine::app::input_setup::has(), eagine::bitfield< Bit >::has_all(), eagine::bitfield< Bit >::has_any(), and eagine::msgbus::remote_node_changes::new_instance().
has_all()
template<typename Bit > template<typename... B> constexpr auto eagine::bitfield< Bit >::has_all (const bit_type bit, B... bits) const -> bool requires(all_are_same_v<bit_type, B...>) inline constexpr noexcept
Tests if all of the specified bits are set.
See also
has
has_not
has_only
has_any
has_none
has_at_most
has_any()
template<typename Bit > template<typename... B> constexpr auto eagine::bitfield< Bit >::has_any (const bit_type bit, B... bits) const -> bool requires(all_are_same_v<bit_type, B...>) inline constexpr noexcept
Tests if any of the specified bits are set.
See also
has
has_not
has_only
has_all
has_none
has_at_most
has_at_most()
template<typename Bit > constexpr auto eagine::bitfield< Bit >::has_at_most (const bit_type bit) const inline constexpr noexcept
Tests if at most the specified bit is set (or is empty).
See also
has
has_not
has_only
has_all
has_any
has_none
has_none()
template<typename Bit > template<typename... B> constexpr auto eagine::bitfield< Bit >::has_none (const bit_type bit, B... bits) const -> bool requires(all_are_same_v<bit_type, B...>) inline constexpr noexcept
Tests if none of the specified bits are set.
See also
has
has_not
has_only
has_all
has_any
has_at_most
has_not()
template<typename Bit > constexpr auto eagine::bitfield< Bit >::has_not (const bit_type bit) const inline constexpr noexcept
Tests if the specified bit is not set.
See also
has
has_all
has_any
has_only
has_none
has_at_most
Referenced by eagine::bitfield< Bit >::has_none().
has_only()
template<typename Bit > constexpr auto eagine::bitfield< Bit >::has_only (const bit_type bit) const inline constexpr noexcept
Tests if only the specified bit is set.
See also
has
has_not
has_all
has_any
has_none
has_at_most
Referenced by eagine::bitfield< Bit >::has_at_most().
operator bool()
template<typename Bit > constexpr eagine::bitfield< Bit >::operator bool () const inline explicit constexpr noexcept
Indicates that some of the bits are set.
See also
is_empty
operator value_type()
template<typename Bit > constexpr eagine::bitfield< Bit >::operator value_type () const inline explicit constexpr noexcept
Explicit conversion to the underlying integer value type.
See also
bits
set()
template<typename Bit > auto eagine::bitfield< Bit >::set (const bit_type b) -> bitfield& inline noexcept
Sets the specified bit.
See also
clear
The documentation for this class was generated from the following file:
eagine/bitfield.hpp
Copyright © 2015-2022 Matúš Chochlík.
<chochlik -at -gmail.com>
Documentation generated on Wed May 18 2022 by Doxygen (version 1.9.1).