eagine::console_entry Class Reference
EAGine (0.87.0) a C++ wrapper for rendering APIs
eagine::console_entry Class Reference
Class representing a single log entry / message.
#include <eagine/console/entry.hpp>
Public Member Functions
console_entry (const identifier source_id, const console_entry_id_t parent_id, const console_entry_id_t entry_id, const console_entry_kind kind, const string_view format, console_backend *backend) noexcept
Constructor.
console_entry (console_entry &&)=delete
Not moveable.
console_entry (const console_entry &)=delete
Not copyable.
auto operator= (console_entry &&)=delete
Not copy assignable.
auto operator= (const console_entry &)=delete
Not move assignable.
~console_entry () noexcept
Destructor. Passed the actual entry to the backend.
auto id () const noexcept -> console_entry_id_t
Returns the id of this entry.
auto parent_id () const noexcept -> console_entry_id_t
Returns the id of the parent entry.
auto separate () noexcept -> auto &
Adds a separator after this entry message is printed.
auto arg (const identifier name, const identifier tag, const identifier value) noexcept -> auto &
Adds a new message argument with identifier value.
auto arg (const identifier name, const identifier value) noexcept -> auto &
Adds a new message argument with identifier value.
auto arg (const identifier name, const identifier tag, const bool value) noexcept -> auto &
Adds a new message argument with boolean value.
auto arg (const identifier name, const identifier tag, const std::signed_integral auto value) noexcept -> auto &
Adds a new message argument with signed integer value.
auto arg (const identifier name, const identifier tag, const std::unsigned_integral auto value) noexcept -> auto &
Adds a new message argument with unsigned integer value.
auto arg (const identifier name, const identifier tag, const std::floating_point auto value) noexcept -> auto &
Adds a new message argument with floating-point value.
template<typename R , typename P >
auto arg (const identifier name, const identifier tag, const std::chrono::duration< R, P > value) noexcept -> auto &
Adds a new message argument with time duration value.
auto arg (const identifier name, const identifier tag, const string_view value) noexcept -> auto &
Adds a new message argument with string value.
auto arg (const identifier name, const identifier tag, const memory::const_block value) noexcept -> auto &
Adds a new message argument with BLOB value.
auto arg (const identifier name, const memory::const_block value) noexcept -> auto &
Adds a new message argument with BLOB value.
template<typename Func >
auto arg_func (Func function) -> auto &
Adds a new message argument adapted by the specified function.
template<typename T >
auto arg (const identifier name, T &&value) noexcept -> console_entry &requires(has_entry_adapter_v< std::decay_t< T >>)
Adds a new message argument with adaptable-type value.
template<typename F , typename T , typename P , typename L >
auto arg (const identifier name, const identifier tag, valid_if_or_fallback< F, T, P, L > &&opt) noexcept -> console_entry &requires(has_entry_function_v< console_entry, std::decay_t< T >> &&has_entry_function_v< console_entry, std::decay_t< F >>)
Adds a new message argument with valid_if_or_fallback value.
Detailed Description
Class representing a single log entry / message.
Note
Do not use directly, use console instead.
Member Function Documentation
arg() [1/12]
auto eagine::console_entry::arg (const identifier name, const identifier tag, const bool value) -> auto& inline noexcept
Adds a new message argument with boolean value.
Parameters
name the argument name identifier. Used in message substitution.
tag the argument type identifier. Used in value formatting.
value the value of the argument.
arg() [2/12]
auto eagine::console_entry::arg (const identifier name, const identifier tag, const identifier value) -> auto& inline noexcept
Adds a new message argument with identifier value.
Parameters
name the argument name identifier. Used in message substitution.
tag the argument type identifier. Used in value formatting.
value the value of the argument.
Referenced by arg().
arg() [3/12]
auto eagine::console_entry::arg (const identifier name, const identifier tag, const memory::const_block value) -> auto& inline noexcept
Adds a new message argument with BLOB value.
Parameters
name the argument name identifier. Used in message substitution.
tag the argument type identifier. Used in value formatting.
value the value of the argument.
Referenced by arg().
arg() [4/12]
template<typename R , typename P > auto eagine::console_entry::arg (const identifier name, const identifier tag, const std::chrono::duration< R, P > value) -> auto& inline noexcept
Adds a new message argument with time duration value.
Parameters
name the argument name identifier. Used in message substitution.
tag the argument type identifier. Used in value formatting.
value the value of the argument.
arg() [5/12]
auto eagine::console_entry::arg (const identifier name, const identifier tag, const std::floating_point auto value) -> auto& inline noexcept
Adds a new message argument with floating-point value.
Parameters
name the argument name identifier. Used in message substitution.
tag the argument type identifier. Used in value formatting.
value the value of the argument.
arg() [6/12]
auto eagine::console_entry::arg (const identifier name, const identifier tag, const std::signed_integral auto value) -> auto& inline noexcept
Adds a new message argument with signed integer value.
Parameters
name the argument name identifier. Used in message substitution.
tag the argument type identifier. Used in value formatting.
value the value of the argument.
arg() [7/12]
auto eagine::console_entry::arg (const identifier name, const identifier tag, const std::unsigned_integral auto value) -> auto& inline noexcept
Adds a new message argument with unsigned integer value.
Parameters
name the argument name identifier. Used in message substitution.
tag the argument type identifier. Used in value formatting.
value the value of the argument.
arg() [8/12]
auto eagine::console_entry::arg (const identifier name, const identifier tag, const string_view value) -> auto& inline noexcept
Adds a new message argument with string value.
Parameters
name the argument name identifier. Used in message substitution.
tag the argument type identifier. Used in value formatting.
value the value of the argument.
arg() [9/12]
template<typename F , typename T , typename P , typename L > auto eagine::console_entry::arg (const identifier name, const identifier tag, valid_if_or_fallback< F, T, P, L > && opt) -> console_entry& requires(has_entry_function_v<console_entry, std::decay_t<T>>&& has_entry_function_v<console_entry, std::decay_t<F>>) inline noexcept
Adds a new message argument with valid_if_or_fallback value.
Parameters
name the argument name identifier. Used in message substitution.
tag the argument type identifier. Used in value formatting.
opt the value of the argument.
See also
valid_if_or_fallback
arg() [10/12]
auto eagine::console_entry::arg (const identifier name, const identifier value) -> auto& inline noexcept
Adds a new message argument with identifier value.
Parameters
name the argument name identifier. Used in message substitution.
value the value of the argument.
arg() [11/12]
auto eagine::console_entry::arg (const identifier name, const memory::const_block value) -> auto& inline noexcept
Adds a new message argument with BLOB value.
Parameters
name the argument name identifier. Used in message substitution.
value the value of the argument.
arg() [12/12]
template<typename T > auto eagine::console_entry::arg (const identifier name, T && value) -> console_entry& requires(has_entry_adapter_v<std::decay_t<T>>) inline noexcept
Adds a new message argument with adaptable-type value.
Parameters
name the argument name identifier. Used in message substitution.
value the value of the argument.
See also
has_log_entry_adapter_v
id()
auto eagine::console_entry::id () const -> console_entry_id_t inline noexcept
Returns the id of this entry.
See also
parent_id
Referenced by ~console_entry().
parent_id()
auto eagine::console_entry::parent_id () const -> console_entry_id_t inline noexcept
Returns the id of the parent entry.
See also
id
Referenced by ~console_entry().
The documentation for this class was generated from the following file:
eagine/console/entry.hpp
Copyright © 2015-2022 Mat Chochlk.
<chochlik -at -gmail.com>
Documentation generated on Wed May 18 2022 by Doxygen (version 1.9.1).