eagine::oglplus::orbiting_camera Class Reference
EAGine (0.87.0) a C++ wrapper for rendering APIs
eagine::oglplus::orbiting_camera Class Reference
Class representing a camera orbiting around its target.
#include <eagine/oglplus/camera.hpp>
Public Member Functions
auto set_target (const vec3 target) noexcept -> auto &
Sets the target position.
auto set_fov (const radians_t< float > angle) noexcept -> auto &
Sets the y-axis FOV angle.
auto set_near (valid_if_positive< float > dist) noexcept -> auto &
Sets the distance of the near plane.
auto set_far (valid_if_positive< float > dist) noexcept -> auto &
Sets the distance of the far plane.
auto set_orbit_min (valid_if_positive< float > orbit) noexcept -> auto &
Set minimal orbit value.
auto set_orbit_max (valid_if_positive< float > orbit) noexcept -> auto &
Set maximal orbit value.
auto set_orbit_factor (const float factor) noexcept -> auto &
Set the factor for calculating the orbit between min and max.
auto set_azimuth (const radians_t< float > turns) noexcept -> auto &
Sets the azimuth angle (longitude)
auto set_elevation (const radians_t< float > pitch) noexcept -> auto &
Sets the elevation angle (latitude)
auto near () const noexcept -> float
Returns the near distance.
auto far () const noexcept -> float
Returns the far distance.
auto midpoint () const noexcept -> float
Returns the midpoint distance between near and far range.
auto fov () const noexcept -> radians_t< float >
Returns the y-axis FOV angle.
auto orbit () const noexcept -> float
Returns the orbit altitude value.
auto skybox_distance () const noexcept -> float
Returns the prefered distance to the farthest part of a skybox.
auto azimuth () const noexcept -> radians_t< float >
Returns the azimuth angle (longitude).
auto elevation () const noexcept -> radians_t< float >
Returns the elevation angle (latitude).
auto target () const noexcept -> vec3
Returns the target position.
auto target_to_camera_direction () const noexcept -> vec3
Returns the target-to-camera direction vector.
auto camera_to_target_direction () const noexcept -> vec3
Returns the camera-to-target direction vector.
auto position () const noexcept -> vec3
Returns the position of the camera.
auto perspective_matrix (const float aspect) const noexcept
Returns the perspective matrix for the given aspect ratio.
auto transform_matrix () const noexcept
Returns the camera transformation matrix.
auto matrix (const float aspect) const noexcept
Returns the camera matrix (perspective * projection).
auto target_plane_point (const float ndcx, const float ndcy, const float aspect) const noexcept -> optionally_valid< vec3 >
Returns the 3D position of a point (in NDC) on the target plane.
auto pointer_ray (const float ndcx, const float ndcy, const float aspect) const noexcept -> optionally_valid< line >
Returns a ray from the camera through a point on the target plane.
Detailed Description
Class representing a camera orbiting around its target.
Examples
oglplus/022_octree.cpp.
Member Function Documentation
azimuth()
auto eagine::oglplus::orbiting_camera::azimuth () const -> radians_t<float> inline noexcept
Returns the azimuth angle (longitude).
See also
orbit
elevation
camera_to_target_direction()
auto eagine::oglplus::orbiting_camera::camera_to_target_direction () const -> vec3 inline noexcept
Returns the camera-to-target direction vector.
See also
target_to_camera_direction
elevation()
auto eagine::oglplus::orbiting_camera::elevation () const -> radians_t<float> inline noexcept
Returns the elevation angle (latitude).
See also
orbit
azimuth
far()
auto eagine::oglplus::orbiting_camera::far () const -> float inline noexcept
Returns the far distance.
See also
near
midpoint
skybox_distance
Referenced by midpoint(), and skybox_distance().
midpoint()
auto eagine::oglplus::orbiting_camera::midpoint () const -> float inline noexcept
Returns the midpoint distance between near and far range.
See also
near
far
skybox_distance
near()
auto eagine::oglplus::orbiting_camera::near () const -> float inline noexcept
Returns the near distance.
See also
far
midpoint
Referenced by midpoint().
orbit()
auto eagine::oglplus::orbiting_camera::orbit () const -> float inline noexcept
Returns the orbit altitude value.
See also
azimuth
elevation
near
far
Referenced by skybox_distance().
position()
auto eagine::oglplus::orbiting_camera::position () const -> vec3 inline noexcept
Returns the position of the camera.
See also
target
skybox_distance()
auto eagine::oglplus::orbiting_camera::skybox_distance () const -> float inline noexcept
Returns the prefered distance to the farthest part of a skybox.
See also
near
midpoint
far
orbit
target()
auto eagine::oglplus::orbiting_camera::target () const -> vec3 inline noexcept
Returns the target position.
See also
position
target_to_camera_direction()
EAGINE_LIB_FUNC auto eagine::oglplus::orbiting_camera::target_to_camera_direction () const -> vec3 noexcept
Returns the target-to-camera direction vector.
See also
camera_to_target_direction
Referenced by camera_to_target_direction().
The documentation for this class was generated from the following files:
eagine/oglplus/camera.hpp
eagine/oglplus/camera.inl
Copyright © 2015-2022 Matúš Chochlík.
<chochlik -at -gmail.com>
Documentation generated on Wed May 18 2022 by Doxygen (version 1.9.1).