eagine::app::execution_context Class Reference
EAGine (0.87.0) a C++ wrapper for rendering APIs
eagine::app::execution_context Class Reference
Class holding shared video/audio rendering application support objects.
#include <eagine/app/context.hpp>
Public Member Functions
auto result () const noexcept -> int
Returns the application execution result.
auto options () const noexcept -> const launch_options &
Returns a reference to the launch options.
auto buffer () const noexcept -> memory::buffer &
Returns a references to a multi-purpose memory buffer.
auto state () const noexcept -> const context_state_view &
Returns a reference to the context state view.
auto prepare (std::unique_ptr< launchpad > pad) -> execution_context &
Prepares the application launch pad object.
auto is_running () noexcept -> bool
Indicates if the application is running its main loop.
void stop_running () noexcept
Stops the main application loop.
void update () noexcept
Updates this execution context (once per a single main loop iteration).
void clean_up () noexcept
Cleans up this execution context and managed objects.
auto run () noexcept -> execution_context &
Starts the main application loop (will block until stopped).
auto enough_run_time () const noexcept -> bool
Indicates if the application ran long enough.
auto enough_frames (const span_size_t frame_no) const noexcept -> bool
Indicates if the application rendered enough frames.
auto video_ctx_count () const noexcept
Returns the count of created video contexts.
auto video_ctx (const span_size_t index=0) const noexcept -> video_context *
Returns the video context at the specified index.
auto audio_ctx_count () const noexcept
Returns the count of created audio contexts.
auto audio_ctx (const span_size_t index=0) const noexcept -> audio_context *
Returns the audio context at the specified index.
auto connect_input (const message_id input_id, const input_handler handler) -> execution_context &
Connect the specified logical input to a callable handler reference.
auto connect_input (const input_slot &input) -> auto &
Connect the specified input slot.
auto connect_inputs () -> execution_context &
Connect generic, reusable application logical input slots.
auto add_ui_button (const std::string &label, const message_id id) -> execution_context &
Add a UI button with the specified label and id.
auto map_input (const message_id input_id, const identifier mapping_id, const message_id signal_id, const input_setup setup) -> execution_context &
Map a specified logical input to a physical input signal.
auto map_input (const message_id input_id, const message_id signal_id, const input_setup setup) -> execution_context &
Map a specified logical input to a physical input signal.
auto map_inputs (const identifier mapping_id) -> execution_context &
Binds generic application inputs to default physical input signals.
auto map_inputs () -> execution_context &
Binds generic application inputs to default physical input signals.
auto setup_inputs (const identifier mapping_id) -> execution_context &
Sets-up (connects handlers and binds to signals) default inputs.
auto setup_inputs () -> execution_context &
Sets-up (connects handlers and binds to signals) default inputs.
auto switch_input_mapping (const identifier mapping_id) -> execution_context &
Switches to the input mapping with the specified id.
auto switch_input_mapping () -> auto &
Switches to the default input mapping.
void random_uniform (span< byte > dest)
Generates random uniformly-distributed bytes into dest.
void random_uniform_01 (span< float > dest)
Generates random uniformly-distributed floats in <0, 1> into dest.
auto random_uniform_01 () -> float
Generates random uniformly-distributed float in <0, 1>.
auto random_uniform_11 () -> float
Generates random uniformly-distributed float in <-1, 1>.
void random_normal (span< float > dest)
Generates random normally-distributed floats into dest.
Public Member Functions inherited from eagine::main_ctx_object
main_ctx_object (const identifier obj_id, main_ctx_parent parent) noexcept
Initialization from object id and parent.
auto as_parent () noexcept -> main_ctx_object_parent_info
Returns this as main_ctx_object_parent_info.
auto main_context () const noexcept -> main_ctx &
Returns a reference to the main context singleton.
auto process_instance_id () const noexcept -> process_instance_id_t
Returns the process id.
auto app_config () const noexcept -> application_config &
Returns a reference to the application config object.
template<typename T >
auto cfg_init (const string_view key, T initial, const string_view tag={}) noexcept -> T
Reads and returns the configuration value identified by key.
template<typename Extractable , typename T >
auto cfg_extr (const string_view key, T initial, const string_view tag={}, const type_identity< Extractable >={}) noexcept -> T
Reads and returns the configuration value identified by key.
auto cio () const noexcept -> const console &
Returns a reference to the console object.
auto cio_print (const console_entry_kind kind, const string_view format) const noexcept -> console_entry
Shorthand for cio().print(...)
auto cio_print (const string_view format) const noexcept -> console_entry
Shorthand for cio().print(...)
auto cio_warning (const string_view format) const noexcept -> console_entry
Shorthand for cio().warning(...)
auto cio_error (const string_view format) const noexcept -> console_entry
Shorthand for cio().error(...)
auto progress () const noexcept -> const activity_progress &
Returns a reference to the root activity object.
auto bus () const noexcept -> message_bus &
Returns a reference to the message bus object.
Public Member Functions inherited from eagine::named_logging_object< main_ctx_log_backend_getter >
named_logging_object (const identifier id, main_ctx_log_backend_getter backend_getter) noexcept
Constructor from identifier and backend_getter object.
named_logging_object (const identifier id, const named_logging_object &parent) noexcept
Constructor from logger id and parent logging object.
constexpr named_logging_object () noexcept=default
Construct logging object without backend.
named_logging_object (named_logging_object &&temp) noexcept
Move constructor.
named_logging_object (const named_logging_object &that) noexcept
Copy constructor.
auto operator= (named_logging_object &&) noexcept -> named_logging_object &=default
Move assignment operator.
auto operator= (const named_logging_object &) -> named_logging_object &=default
Copy assignment operator.
constexpr auto object_id () const noexcept
Returns the identifier of this logging object.
void object_description (const string_view display_name, const string_view description) noexcept
Sets the human-readable name and description of this object.
auto log_fatal (const string_view format) const noexcept
Create a log message entry for fatal error, with specified format.
auto log_error (const string_view format) const noexcept
Create a log message entry for error, with specified format.
auto log_warning (const string_view format) const noexcept
Create a log message entry for warning, with specified format.
auto log_info (const string_view format) const noexcept
Create a log message entry for information, with specified format.
auto log_stat (const string_view format) const noexcept
Create a log message entry for statistic, with specified format.
auto log_debug (const string_view format) const noexcept
Create a log message entry for debugging, with specified format.
auto log_trace (const string_view format) const noexcept
Create a log message entry for tracing, with specified format.
auto log_backtrace (const string_view format) const noexcept
Create a log message entry for backtracing, with specified format.
auto log_debug_stream () const noexcept
Returns a log entry stream for debug messages.
auto log_error_stream () const noexcept
Returns a log entry stream for error messages.
auto log_chart_sample (const identifier series, const float value) const noexcept -> const named_logging_object &
Stores a new value in the specified chart data series.
auto log_chart_sample (const identifier series, const tagged_quantity< T, U > &qty) const noexcept -> const named_logging_object &requires(std::is_convertible_v< T, float >)
Stores a new value in the specified chart data series.
auto log_chart_sample (const identifier series, const valid_if< T, P > &opt_value) const noexcept -> const named_logging_object &
Stores a new value in the specified chart data series.
Public Member Functions inherited from eagine::basic_logger< BackendGetter >
auto backend () const noexcept
Returns a pointer to the backend of this logger object.
auto instance_id () const noexcept -> logger_instance_id
Returns the unique id of this logger instance.
Additional Inherited Members
Public Types inherited from eagine::named_logging_object< main_ctx_log_backend_getter >
using entry_type = std::conditional_t< is_log_level_enabled_v< severity >, log_entry, no_log_entry >
The entry type for the specified log_event_severity.
Public Types inherited from eagine::basic_logger< BackendGetter >
template<log_event_severity severity>
using entry_type = std::conditional_t< is_log_level_enabled_v< severity >, log_entry, no_log_entry >
The entry type for the specified log_event_severity.
Detailed Description
Class holding shared video/audio rendering application support objects.
See also
video_context
audio_context
launch_options
Member Function Documentation
connect_input()
auto eagine::app::execution_context::connect_input (const input_slot & input) -> auto& inline
Connect the specified input slot.
See also
input_slot
Referenced by connect_inputs(), and eagine::app::orbiting_camera::connect_inputs().
is_running()
EAGINE_LIB_FUNC auto eagine::app::execution_context::is_running () -> bool noexcept
Indicates if the application is running its main loop.
See also
stop_running
Referenced by run().
stop_running()
void eagine::app::execution_context::stop_running () noexcept
Stops the main application loop.
See also
is_running
Referenced by eagine::app::video_context::commit().
The documentation for this class was generated from the following files:
eagine/app/context.hpp
eagine/app/context.inl
Copyright © 2015-2022 Mat Chochlk.
<chochlik -at -gmail.com>
Documentation generated on Wed May 18 2022 by Doxygen (version 1.9.1).