eagine::app::orbiting_camera Class Reference
EAGine (0.87.0) a C++ wrapper for rendering APIs
eagine::app::orbiting_camera Class Reference
Extension of orbiting camera wrapper.
#include <eagine/app/camera.hpp>
Public Member Functions
auto matrix (video_context &vc) const noexcept
Construction from a reference to a video context.
auto has_changed () noexcept
Inddicates if the camera has changed and resets the flag.
auto mark_changed () noexcept -> orbiting_camera &
Inddicates that the camera has changed.
auto update_orbit (const float inc) noexcept -> orbiting_camera &
Does a generic orbit update with given increment.
auto update_turns (const float inc) noexcept -> orbiting_camera &
Does a generic azimuth update with given increment.
auto update_pitch (const float inc) noexcept -> orbiting_camera &
Does a generic elevation update with given increment.
auto set_pitch_max (const radians_t< float > max) noexcept -> auto &
Sets the maximum value for the pitch (elevation) angle.
auto set_pitch_min (const radians_t< float > min) noexcept -> auto &
Sets the minimum value for the pitch (elevation) angle.
auto idle_update (const context_state_view &, const valid_if_positive< float > &divisor=2.F) noexcept -> orbiting_camera &
Does a generic combined update when the user does not provide input.
auto idle_update (const execution_context &, const valid_if_positive< float > &divisor=2.F) noexcept -> orbiting_camera &
Does a generic combined update when the user does not provide input.
auto pressure_input () noexcept -> input_slot
Returns the input slot for handling cursor pressure input signals. This can be bound for example to mouse button press input signal.
auto dampening_input () noexcept -> input_slot
Returns the input slot for handling motion dampening input signals. This can be bound for example to control or shift key press input signal.
auto altitude_change_input () noexcept -> input_slot
Returns the input slot for handling orbit change input signals. This can be bound for example to mouse wheel scroll input signal.
auto longitude_change_input () noexcept -> input_slot
Returns the input slot for handling azimuth change input signals. This can be bound for example to left/right arrow key press input signals.
auto latitude_change_input () noexcept -> input_slot
Returns the input slot for handling elevation change input signals. This can be bound for example to up/down arrow key press input signals.
auto connect_inputs (execution_context &ec) -> orbiting_camera &
Connects the camera input slots to the execution context.
auto basic_input_mapping (execution_context &ec, const identifier mapping_id) -> orbiting_camera &
Specifies a named key binding for the camera input slots.
auto basic_input_mapping (execution_context &ec) -> auto &
Specifies the default key binding for the camera input slots.
auto matrix (const float aspect) const noexcept
Returns the camera matrix (perspective * projection).
Public Member Functions inherited from eagine::oglplus::orbiting_camera
auto set_target (const vec3 target) noexcept -> auto &
Sets the target position.
auto set_fov (const radians_t< float > angle) noexcept -> auto &
Sets the y-axis FOV angle.
auto set_near (valid_if_positive< float > dist) noexcept -> auto &
Sets the distance of the near plane.
auto set_far (valid_if_positive< float > dist) noexcept -> auto &
Sets the distance of the far plane.
auto set_orbit_min (valid_if_positive< float > orbit) noexcept -> auto &
Set minimal orbit value.
auto set_orbit_max (valid_if_positive< float > orbit) noexcept -> auto &
Set maximal orbit value.
auto set_orbit_factor (const float factor) noexcept -> auto &
Set the factor for calculating the orbit between min and max.
auto set_azimuth (const radians_t< float > turns) noexcept -> auto &
Sets the azimuth angle (longitude)
auto set_elevation (const radians_t< float > pitch) noexcept -> auto &
Sets the elevation angle (latitude)
auto near () const noexcept -> float
Returns the near distance.
auto far () const noexcept -> float
Returns the far distance.
auto midpoint () const noexcept -> float
Returns the midpoint distance between near and far range.
auto fov () const noexcept -> radians_t< float >
Returns the y-axis FOV angle.
auto orbit () const noexcept -> float
Returns the orbit altitude value.
auto skybox_distance () const noexcept -> float
Returns the prefered distance to the farthest part of a skybox.
auto azimuth () const noexcept -> radians_t< float >
Returns the azimuth angle (longitude).
auto elevation () const noexcept -> radians_t< float >
Returns the elevation angle (latitude).
auto target () const noexcept -> vec3
Returns the target position.
auto target_to_camera_direction () const noexcept -> vec3
Returns the target-to-camera direction vector.
auto camera_to_target_direction () const noexcept -> vec3
Returns the camera-to-target direction vector.
auto position () const noexcept -> vec3
Returns the position of the camera.
auto perspective_matrix (const float aspect) const noexcept
Returns the perspective matrix for the given aspect ratio.
auto transform_matrix () const noexcept
Returns the camera transformation matrix.
auto matrix (const float aspect) const noexcept
Returns the camera matrix (perspective * projection).
auto target_plane_point (const float ndcx, const float ndcy, const float aspect) const noexcept -> optionally_valid< vec3 >
Returns the 3D position of a point (in NDC) on the target plane.
auto pointer_ray (const float ndcx, const float ndcy, const float aspect) const noexcept -> optionally_valid< line >
Returns a ray from the camera through a point on the target plane.
Detailed Description
Extension of orbiting camera wrapper.
Member Function Documentation
altitude_change_input()
auto eagine::app::orbiting_camera::altitude_change_input () -> input_slot inline noexcept
Returns the input slot for handling orbit change input signals. This can be bound for example to mouse wheel scroll input signal.
See also
connect_inputs
basic_input_mapping
Referenced by connect_inputs().
basic_input_mapping() [1/2]
auto eagine::app::orbiting_camera::basic_input_mapping (execution_context & ec) -> auto& inline
Specifies the default key binding for the camera input slots.
See also
connect_inputs
basic_input_mapping() [2/2]
EAGINE_LIB_FUNC auto eagine::app::orbiting_camera::basic_input_mapping (execution_context & ec, const identifier mapping_id) -> orbiting_camera&
Specifies a named key binding for the camera input slots.
See also
connect_inputs
Referenced by basic_input_mapping().
connect_inputs()
EAGINE_LIB_FUNC auto eagine::app::orbiting_camera::connect_inputs (execution_context & ec) -> orbiting_camera&
Connects the camera input slots to the execution context.
See also
basic_input_mapping
dampening_input()
auto eagine::app::orbiting_camera::dampening_input () -> input_slot inline noexcept
Returns the input slot for handling motion dampening input signals. This can be bound for example to control or shift key press input signal.
See also
connect_inputs
basic_input_mapping
Referenced by connect_inputs().
has_changed()
auto eagine::app::orbiting_camera::has_changed () inline noexcept
Inddicates if the camera has changed and resets the flag.
See also
mark_changed
idle_update() [1/2]
EAGINE_LIB_FUNC auto eagine::app::orbiting_camera::idle_update (const context_state_view & state, const valid_if_positive< float > & divisor = 2.F) -> orbiting_camera& noexcept
Does a generic combined update when the user does not provide input.
See also
update_orbit
update_turns
update_pitch
idle_update() [2/2]
EAGINE_LIB_FUNC auto eagine::app::orbiting_camera::idle_update (const execution_context & ec, const valid_if_positive< float > & divisor = 2.F) -> orbiting_camera& noexcept
Does a generic combined update when the user does not provide input.
See also
update_orbit
update_turns
update_pitch
latitude_change_input()
auto eagine::app::orbiting_camera::latitude_change_input () -> input_slot inline noexcept
Returns the input slot for handling elevation change input signals. This can be bound for example to up/down arrow key press input signals.
See also
connect_inputs
basic_input_mapping
Referenced by connect_inputs().
longitude_change_input()
auto eagine::app::orbiting_camera::longitude_change_input () -> input_slot inline noexcept
Returns the input slot for handling azimuth change input signals. This can be bound for example to left/right arrow key press input signals.
See also
connect_inputs
basic_input_mapping
Referenced by connect_inputs().
mark_changed()
auto eagine::app::orbiting_camera::mark_changed () -> orbiting_camera& inline noexcept
Inddicates that the camera has changed.
See also
has_changed
pressure_input()
auto eagine::app::orbiting_camera::pressure_input () -> input_slot inline noexcept
Returns the input slot for handling cursor pressure input signals. This can be bound for example to mouse button press input signal.
See also
connect_inputs
basic_input_mapping
Referenced by connect_inputs().
set_pitch_max()
auto eagine::app::orbiting_camera::set_pitch_max (const radians_t< float > max) -> auto& inline noexcept
Sets the maximum value for the pitch (elevation) angle.
See also
set_pitch_min
set_pitch_min()
auto eagine::app::orbiting_camera::set_pitch_min (const radians_t< float > min) -> auto& inline noexcept
Sets the minimum value for the pitch (elevation) angle.
See also
set_pitch_max
The documentation for this class was generated from the following files:
eagine/app/camera.hpp
eagine/app/camera.inl
Copyright © 2015-2022 Mat Chochlk.
<chochlik -at -gmail.com>
Documentation generated on Wed May 18 2022 by Doxygen (version 1.9.1).