eagine::msgbus::sudoku_tiles< S > Class Template Reference
EAGine (0.87.0) a C++ wrapper for rendering APIs
eagine::msgbus::sudoku_tiles< S > Class Template Reference
Message bus
#include <eagine/msgbus/service/sudoku.hpp>
Public Types
using Coord = std::tuple< int, int >
The board coordinate/key type.
Public Member Functions
auto width () const noexcept -> int
Returns the width (in cells) of the tiling.
auto height () const noexcept -> int
Returns the height (in cells) of the tiling.
auto cell_count () const noexcept -> int
Total count of tiles in this tiling.
constexpr auto cells_per_tile_side () const noexcept -> int
Returns how many cells are on the side of a single tile.
constexpr auto cells_per_tile () const noexcept -> int
Returns how many cells are in a single tile.
auto get_board (const Coord coord) const noexcept -> const basic_sudoku_board< S > *
Get the board at the specified coordinate if it is solved.
auto get_board (const int x, const int y) const noexcept
Get the board at the specified coordinate if it is solved.
auto set_board (Coord coord, basic_sudoku_board< S > board) noexcept -> bool
Sets the board at the specified coordinate.
auto get_fragment (Coord coord) const noexcept -> sudoku_fragment_view< S >
Return a view of the fragment at the specified board coordinate.
void set_extent (const Coord min, const Coord max) noexcept
Sets the extent (number of tiles in x and y dimension) of the tiling.
void set_extent (const Coord max) noexcept
Sets the extent (number of tiles in x and y dimension) of the tiling.
auto is_in_extent (const int x, const int y) const noexcept -> bool
Indicates in the specified coordinate is in the extent of this tiling.
auto boards_extent (const Coord min, const Coord max) const noexcept -> std::tuple< int, int, int, int >
Returns the extent between min and max in units of boards.
auto boards_extent () const noexcept
Returns the extent of this tiling in units of boards.
auto are_complete (const Coord min, const Coord max) const noexcept -> bool
Indicates if the boards between the min and max coordinates are solved.
auto are_complete () const noexcept -> bool
Indicates if the boards in this tiling's extent are solved.
auto print (std::ostream &out, const Coord min, const Coord max, const basic_sudoku_board_traits< S > &traits) const noexcept -> std::ostream &
Prints the current tiling using the specified sudoku board traits.
auto print_progress (std::ostream &out, const Coord min, const Coord max) const noexcept -> std::ostream &
Shows which tiles are solved and which unsolved.
auto print (std::ostream &out, const Coord min, const Coord max) const noexcept -> std::ostream &
Prints the current tiling using the specified sudoku board traits.
auto print (std::ostream &out, const basic_sudoku_board_traits< S > &traits) const noexcept -> auto &
Prints the current tiling using the specified sudoku board traits.
auto print (std::ostream &out) const noexcept -> auto &
Prints the current tiling using the specified sudoku board traits.
auto print_progress (std::ostream &out) const noexcept -> auto &
Shows which tiles are solved and which unsolved.
auto reset () noexcept -> auto &
Resets all pending tilings.
Detailed Description
template<unsigned S>
class eagine::msgbus::sudoku_tiles< S >
@brie Class representing a set of related Sudoku tiles.
See also
sudoku_tiling
Member Function Documentation
cell_count()
template<unsigned S> auto eagine::msgbus::sudoku_tiles< S >::cell_count () const -> int inline noexcept
Total count of tiles in this tiling.
See also
width
height
cells_per_tile
cells_per_tile()
template<unsigned S> constexpr auto eagine::msgbus::sudoku_tiles< S >::cells_per_tile () const -> int inline constexpr noexcept
Returns how many cells are in a single tile.
See also
cells_per_tile_side
cells_per_tile_side()
template<unsigned S> constexpr auto eagine::msgbus::sudoku_tiles< S >::cells_per_tile_side () const -> int inline constexpr noexcept
Returns how many cells are on the side of a single tile.
See also
cells_per_tile
Referenced by eagine::msgbus::sudoku_tiles< S >::cells_per_tile().
height()
template<unsigned S> auto eagine::msgbus::sudoku_tiles< S >::height () const -> int inline noexcept
Returns the height (in cells) of the tiling.
See also
width
cell_count
Referenced by eagine::msgbus::sudoku_tiles< S >::cell_count().
is_in_extent()
template<unsigned S> auto eagine::msgbus::sudoku_tiles< S >::is_in_extent (const int x, const int y) const -> bool inline noexcept
Indicates in the specified coordinate is in the extent of this tiling.
See also
set_extent
set_extent()
template<unsigned S> void eagine::msgbus::sudoku_tiles< S >::set_extent (const Coord max) inline noexcept
Sets the extent (number of tiles in x and y dimension) of the tiling.
See also
is_in_extent
width()
template<unsigned S> auto eagine::msgbus::sudoku_tiles< S >::width () const -> int inline noexcept
Returns the width (in cells) of the tiling.
See also
height
cell_count
Referenced by eagine::msgbus::sudoku_tiles< S >::cell_count().
The documentation for this class was generated from the following file:
eagine/msgbus/service/sudoku.hpp
Copyright © 2015-2022 Matúš Chochlík.
<chochlik -at -gmail.com>
Documentation generated on Wed May 18 2022 by Doxygen (version 1.9.1).