eagine::msgbus::endpoint Class Reference
EAGine (0.87.0) a C++ wrapper for rendering APIs
eagine::msgbus::endpoint Class Reference
Message bus
Message bus client endpoint that can send and receive messages.
#include <eagine/msgbus/endpoint.hpp>
Public Types
using fetch_handler = connection::fetch_handler
Alias for message fetch handler callable reference.
using method_handler = basic_callable_ref< bool(const message_context &, const stored_message &) noexcept, true >
Alias for callable handling received messages.
Public Types inherited from eagine::named_logging_object< main_ctx_log_backend_getter >
using entry_type = std::conditional_t< is_log_level_enabled_v< severity >, log_entry, no_log_entry >
The entry type for the specified log_event_severity.
Public Types inherited from eagine::basic_logger< BackendGetter >
template<log_event_severity severity>
using entry_type = std::conditional_t< is_log_level_enabled_v< severity >, log_entry, no_log_entry >
The entry type for the specified log_event_severity.
Public Member Functions
endpoint (main_ctx_object obj) noexcept
Construction with a reference to parent main context object.
endpoint (const identifier id, main_ctx_parent parent) noexcept
Construction with an enpoint id and parent main context object.
endpoint (const endpoint &)=delete
Not copy constructible.
auto operator= (endpoint &&)=delete
Not move assignable.
auto operator= (const endpoint &)=delete
Not copy assignable.
auto ctx () noexcept -> context &
Returns a reference to the message bus context.
auto set_id (const identifier id) noexcept -> auto &
Assigns the unique id of this endpoint.
auto preconfigure_id (const identifier_t id) noexcept -> auto &
Preconfigures the unique id of this endpoint.
auto has_preconfigured_id () const noexcept -> bool
Indicates if this endpoint has a preconfigured id (or should request one).
auto has_id () const noexcept -> bool
Indicates if this endpoint has valid id (set manually or from the bus).
auto get_preconfigured_id () const noexcept
Returns the preconfigured id of this endpoint.
auto get_id () const noexcept
Returns the unique id of this endpoint.
void add_certificate_pem (const memory::const_block blk) noexcept
Adds endpoint certificate in a PEM-encoded memory block.
void add_ca_certificate_pem (const memory::const_block blk) noexcept
Adds CA certificate in a PEM-encoded memory block.
auto add_connection (std::unique_ptr< connection > conn) noexcept -> bool final
Adds a connection for communication with a message bus router.
auto is_usable () const noexcept -> bool
Tests if this has all prerequisites for sending and receiving messages.
auto max_data_size () const noexcept -> valid_if_positive< span_size_t >
Returns the maximum data block size that the endpoint can send.
void flush_outbox () noexcept
Sends any pending outgoing messages if possible.
auto update () noexcept -> work_done
Updates the internal state, sends and receives pending messages.
void finish () noexcept
Says to the message bus that this endpoint is disconnecting.
void subscribe (const message_id) noexcept
Subscribes to messages with the specified id/type.
void unsubscribe (const message_id) noexcept
Unsubscribes from messages with the specified id/type.
auto post (const message_id msg_id, const message_view &message) noexcept -> bool
Enqueues a message with the specified id/type for sending.
auto post_callable () noexcept -> callable_ref< bool(message_id, const message_view &) noexcept >
Creates a callable that calls post on this enpoint.
auto post_signed (const message_id, const message_view message) noexcept -> bool
Signs and enqueues a message with the specified id/type for sending.
template<typename T >
auto post_value (const message_id msg_id, T &value, const message_info &info={}) noexcept -> bool
Serializes the specified value and enqueues it for sending in message.
auto post_blob (const message_id msg_id, const identifier_t target_id, const blob_id_t target_blob_id, const memory::const_block blob, const std::chrono::seconds max_time, const message_priority priority) noexcept -> message_sequence_t
Enqueues a BLOB that is larger than max_data_size for sending.
auto broadcast_blob (const message_id msg_id, const memory::const_block blob, const std::chrono::seconds max_time, const message_priority priority) noexcept -> bool
Enqueues a BLOB that is larger than max_data_size for broadcast.
auto broadcast_blob (const message_id msg_id, const memory::const_block blob, const std::chrono::seconds max_time) noexcept -> bool
Enqueues a BLOB that is larger than max_data_size for broadcast.
auto post_certificate (const identifier_t target_id, const blob_id_t) noexcept -> bool
Posts the certificate of this enpoint to the specified remote.
auto broadcast_certificate () noexcept -> bool
Broadcasts the certificate of this enpoint to the whole bus.
auto say_not_a_router () noexcept -> bool
Posts a message saying that this is not a router bus node.
auto say_still_alive () noexcept -> bool
Posts a message saying that this endpoint is alive.
auto say_bye () noexcept -> bool
Posts a message saying that this endpoint is about to disconnect.
void post_meta_message (const message_id meta_msg_id, const message_id msg_id) noexcept
Post a message with another message type as its content.
void post_meta_message_to (const identifier_t target_id, const message_id meta_msg_id, const message_id msg_id) noexcept
Post a message with another message type as its content to target.
void say_subscribes_to (const message_id) noexcept
Broadcasts a message that this subscribes to message with given id.
void say_subscribes_to (const identifier_t target_id, const message_id) noexcept
Posts a message that this subscribes to message with given id.
void say_unsubscribes_from (const message_id) noexcept
Broadcasts a message that this unsubscribes from message with given type.
void say_not_subscribed_to (const identifier_t target_id, const message_id) noexcept
Posts a message that this is not subscribed to message with given type.
void query_subscriptions_of (const identifier_t target_id) noexcept
Posts a message requesting all subscriptions of a target node.
void query_subscribers_of (const message_id) noexcept
Posts a message requesting all subscribers of a given message type.
void clear_block_list () noexcept
Sends a message to router to clear its block filter for this endpoint.
void block_message_type (const message_id) noexcept
Sends a message to router to start blocking message type for this endpoint.
void clear_allow_list () noexcept
Sends a message to router to clear its allow filter for this endpoint.
void allow_message_type (const message_id) noexcept
Sends a message to router to start blocking message type for this endpoint.
void query_certificate_of (const identifier_t endpoint_id) noexcept
Sends a message requesting remote endpoint certificate.
auto respond_to (const message_info &info, const message_id msg_id, message_view message) noexcept -> bool
Posts a message as a response to another received message.
auto respond_to (const message_info &info, const message_id msg_id) noexcept -> bool
Posts a message as a response to another received message.
auto process_one (const message_id msg_id, const method_handler handler) noexcept -> bool
Processes a single received message of specified type with a handler.
template<typename Class , bool(Class::*)(const message_context &, const stored_message &) MemFnPtr>
auto process_one (const message_id msg_id, const member_function_constant< bool(Class::*)(const message_context &, const stored_message &), MemFnPtr > method, Class *instance) noexcept -> bool
Processes a single received message of specified type with a method.
auto process_all (const message_id msg_id, const method_handler handler) noexcept -> span_size_t
Processes all received messages of specified type with a handler.
auto process_everything (const method_handler handler) noexcept -> span_size_t
Processes all received messages regardles of type with a handler.
auto flow_average_message_age () const noexcept -> std::chrono::microseconds
Returns the average message age in the connected router.
Public Member Functions inherited from eagine::interface< connection_user >
constexpr interface (const interface &)=delete
Not copyable.
auto operator= (interface &&)=delete
Not move assignable.
auto operator= (const interface &)=delete
Not copy assignable.
Public Member Functions inherited from eagine::main_ctx_object
main_ctx_object (const identifier obj_id, main_ctx_parent parent) noexcept
Initialization from object id and parent.
auto as_parent () noexcept -> main_ctx_object_parent_info
Returns this as main_ctx_object_parent_info.
auto main_context () const noexcept -> main_ctx &
Returns a reference to the main context singleton.
auto process_instance_id () const noexcept -> process_instance_id_t
Returns the process id.
auto app_config () const noexcept -> application_config &
Returns a reference to the application config object.
template<typename T >
auto cfg_init (const string_view key, T initial, const string_view tag={}) noexcept -> T
Reads and returns the configuration value identified by key.
template<typename Extractable , typename T >
auto cfg_extr (const string_view key, T initial, const string_view tag={}, const type_identity< Extractable >={}) noexcept -> T
Reads and returns the configuration value identified by key.
auto cio () const noexcept -> const console &
Returns a reference to the console object.
auto cio_print (const console_entry_kind kind, const string_view format) const noexcept -> console_entry
Shorthand for cio().print(...)
auto cio_print (const string_view format) const noexcept -> console_entry
Shorthand for cio().print(...)
auto cio_warning (const string_view format) const noexcept -> console_entry
Shorthand for cio().warning(...)
auto cio_error (const string_view format) const noexcept -> console_entry
Shorthand for cio().error(...)
auto progress () const noexcept -> const activity_progress &
Returns a reference to the root activity object.
auto bus () const noexcept -> message_bus &
Returns a reference to the message bus object.
Public Member Functions inherited from eagine::named_logging_object< main_ctx_log_backend_getter >
named_logging_object (const identifier id, main_ctx_log_backend_getter backend_getter) noexcept
Constructor from identifier and backend_getter object.
named_logging_object (const identifier id, const named_logging_object &parent) noexcept
Constructor from logger id and parent logging object.
constexpr named_logging_object () noexcept=default
Construct logging object without backend.
named_logging_object (named_logging_object &&temp) noexcept
Move constructor.
named_logging_object (const named_logging_object &that) noexcept
Copy constructor.
auto operator= (named_logging_object &&) noexcept -> named_logging_object &=default
Move assignment operator.
auto operator= (const named_logging_object &) -> named_logging_object &=default
Copy assignment operator.
constexpr auto object_id () const noexcept
Returns the identifier of this logging object.
void object_description (const string_view display_name, const string_view description) noexcept
Sets the human-readable name and description of this object.
auto log_fatal (const string_view format) const noexcept
Create a log message entry for fatal error, with specified format.
auto log_error (const string_view format) const noexcept
Create a log message entry for error, with specified format.
auto log_warning (const string_view format) const noexcept
Create a log message entry for warning, with specified format.
auto log_info (const string_view format) const noexcept
Create a log message entry for information, with specified format.
auto log_stat (const string_view format) const noexcept
Create a log message entry for statistic, with specified format.
auto log_debug (const string_view format) const noexcept
Create a log message entry for debugging, with specified format.
auto log_trace (const string_view format) const noexcept
Create a log message entry for tracing, with specified format.
auto log_backtrace (const string_view format) const noexcept
Create a log message entry for backtracing, with specified format.
auto log_debug_stream () const noexcept
Returns a log entry stream for debug messages.
auto log_error_stream () const noexcept
Returns a log entry stream for error messages.
auto log_chart_sample (const identifier series, const float value) const noexcept -> const named_logging_object &
Stores a new value in the specified chart data series.
auto log_chart_sample (const identifier series, const tagged_quantity< T, U > &qty) const noexcept -> const named_logging_object &requires(std::is_convertible_v< T, float >)
Stores a new value in the specified chart data series.
auto log_chart_sample (const identifier series, const valid_if< T, P > &opt_value) const noexcept -> const named_logging_object &
Stores a new value in the specified chart data series.
Public Member Functions inherited from eagine::basic_logger< BackendGetter >
auto backend () const noexcept
Returns a pointer to the backend of this logger object.
auto instance_id () const noexcept -> logger_instance_id
Returns the unique id of this logger instance.
Static Public Member Functions
static constexpr auto is_valid_id (const identifier_t id) noexcept -> bool
Tests if the specified id is a valid endpoint id.
Public Attributes
signal< void(const identifier_t) noexcept > id_assigned
Triggered when the id is confirmed or assigned to this endpoint.
signal< void(const bool) noexcept > connection_established
Triggered when this endpoint's connection is established.
signal< void() noexcept > connection_lost
Triggered when this endpoint's connection is lost.
Additional Inherited Members
Protected Member Functions inherited from eagine::interface< connection_user >
constexpr interface () noexcept=default
Default constructible by derived.
constexpr interface (interface &&) noexcept=default
Move constructible by derived.
Detailed Description
Message bus client endpoint that can send and receive messages.
See also
static_subscriber
subscriber
Member Typedef Documentation
method_handler
using eagine::msgbus::endpoint::method_handler = basic_callable_ref< bool(const message_context&, const stored_message&) noexcept, true>
Alias for callable handling received messages.
See also
process_one
process_all
Member Function Documentation
add_ca_certificate_pem()
EAGINE_LIB_FUNC void eagine::msgbus::endpoint::add_ca_certificate_pem (const memory::const_block blk) noexcept
Adds CA certificate in a PEM-encoded memory block.
See also
add_certificate_pem
add_certificate_pem()
EAGINE_LIB_FUNC void eagine::msgbus::endpoint::add_certificate_pem (const memory::const_block blk) noexcept
Adds endpoint certificate in a PEM-encoded memory block.
See also
add_ca_certificate_pem
allow_message_type()
EAGINE_LIB_FUNC void eagine::msgbus::endpoint::allow_message_type (const message_id msg_id) noexcept
Sends a message to router to start blocking message type for this endpoint.
See also
clear_allow_list
block_message_type
block_message_type()
EAGINE_LIB_FUNC void eagine::msgbus::endpoint::block_message_type (const message_id msg_id) noexcept
Sends a message to router to start blocking message type for this endpoint.
See also
clear_block_list
allow_message_type
broadcast_blob() [1/2]
auto eagine::msgbus::endpoint::broadcast_blob (const message_id msg_id, const memory::const_block blob, const std::chrono::seconds max_time) -> bool inline noexcept
Enqueues a BLOB that is larger than max_data_size for broadcast.
See also
post
post_signed
post_value
max_data_size
broadcast_blob() [2/2]
auto eagine::msgbus::endpoint::broadcast_blob (const message_id msg_id, const memory::const_block blob, const std::chrono::seconds max_time, const message_priority priority) -> bool inline noexcept
Enqueues a BLOB that is larger than max_data_size for broadcast.
See also
post
post_signed
post_value
max_data_size
Referenced by broadcast_blob().
clear_allow_list()
EAGINE_LIB_FUNC void eagine::msgbus::endpoint::clear_allow_list () noexcept
Sends a message to router to clear its allow filter for this endpoint.
See also
allow_message_type
clear_block_list
clear_block_list()
EAGINE_LIB_FUNC void eagine::msgbus::endpoint::clear_block_list () noexcept
Sends a message to router to clear its block filter for this endpoint.
See also
block_message_type
clear_allow_list
ctx()
auto eagine::msgbus::endpoint::ctx () -> context& inline noexcept
Returns a reference to the message bus context.
See also
msgbus::context
Referenced by eagine::msgbus::subscriber_base::verify_bits().
get_id()
auto eagine::msgbus::endpoint::get_id () const inline noexcept
Returns the unique id of this endpoint.
See also
set_id
has_id
is_valid_id
get_preconfigured_id()
auto eagine::msgbus::endpoint::get_preconfigured_id () const inline noexcept
Returns the preconfigured id of this endpoint.
See also
preconfigure_id
has_preconfigured_id
is_valid_id
Referenced by update().
has_id()
auto eagine::msgbus::endpoint::has_id () const -> bool inline noexcept
Indicates if this endpoint has valid id (set manually or from the bus).
See also
set_id
get_id
is_valid_id
Referenced by flush_outbox(), post(), and update().
has_preconfigured_id()
auto eagine::msgbus::endpoint::has_preconfigured_id () const -> bool inline noexcept
Indicates if this endpoint has a preconfigured id (or should request one).
See also
preconfigure_id
get_preconfigured_id
is_valid_id
Referenced by update().
post()
auto eagine::msgbus::endpoint::post (const message_id msg_id, const message_view & message) -> bool inline noexcept
Enqueues a message with the specified id/type for sending.
See also
post_signed
post_value
post_blob
post_callable
Referenced by post_meta_message(), post_meta_message_to(), and respond_to().
post_blob()
auto eagine::msgbus::endpoint::post_blob (const message_id msg_id, const identifier_t target_id, const blob_id_t target_blob_id, const memory::const_block blob, const std::chrono::seconds max_time, const message_priority priority) -> message_sequence_t inline noexcept
Enqueues a BLOB that is larger than max_data_size for sending.
See also
post
post_signed
post_value
max_data_size
Referenced by broadcast_blob().
post_callable()
auto eagine::msgbus::endpoint::post_callable () -> callable_ref<bool(message_id, const message_view&) noexcept> inline noexcept
Creates a callable that calls post on this enpoint.
See also
post
post_meta_message()
EAGINE_LIB_FUNC void eagine::msgbus::endpoint::post_meta_message (const message_id meta_msg_id, const message_id msg_id) noexcept
Post a message with another message type as its content.
See also
post
post_meta_message_to
default_serialize
post_meta_message_to()
EAGINE_LIB_FUNC void eagine::msgbus::endpoint::post_meta_message_to (const identifier_t target_id, const message_id meta_msg_id, const message_id msg_id) noexcept
Post a message with another message type as its content to target.
See also
post
post_meta_message
default_serialize
post_signed()
EAGINE_LIB_FUNC auto eagine::msgbus::endpoint::post_signed (const message_id msg_id, const message_view message) -> bool noexcept
Signs and enqueues a message with the specified id/type for sending.
See also
post
post_value
post_value()
template<typename T > auto eagine::msgbus::endpoint::post_value (const message_id msg_id, T & value, const message_info & info = {}) -> bool inline noexcept
Serializes the specified value and enqueues it for sending in message.
See also
post
post_signed
default_serialize
preconfigure_id()
auto eagine::msgbus::endpoint::preconfigure_id (const identifier_t id) -> auto& inline noexcept
Preconfigures the unique id of this endpoint.
See also
set_id
has_preconfigured_id
get_preconfigured_id
process_all()
EAGINE_LIB_FUNC auto eagine::msgbus::endpoint::process_all (const message_id msg_id, const method_handler handler) -> span_size_t noexcept
Processes all received messages of specified type with a handler.
See also
process_one
process_everything
process_one() [1/2]
template<typename Class , bool(Class::*)(const message_context &, const stored_message &) MemFnPtr> auto eagine::msgbus::endpoint::process_one (const message_id msg_id, const member_function_constant< bool(Class::*)(const message_context &, const stored_message &), MemFnPtr > method, Class * instance) -> bool inline noexcept
Processes a single received message of specified type with a method.
See also
process_all
process_everything
process_one() [2/2]
EAGINE_LIB_FUNC auto eagine::msgbus::endpoint::process_one (const message_id msg_id, const method_handler handler) -> bool noexcept
Processes a single received message of specified type with a handler.
See also
process_all
process_everything
query_subscribers_of()
EAGINE_LIB_FUNC void eagine::msgbus::endpoint::query_subscribers_of (const message_id msg_id) noexcept
Posts a message requesting all subscribers of a given message type.
See also
query_subscribers_of
say_subscribes_to
Referenced by eagine::msgbus::subscriber_base::query_subscribers_of().
query_subscriptions_of()
EAGINE_LIB_FUNC void eagine::msgbus::endpoint::query_subscriptions_of (const identifier_t target_id) noexcept
Posts a message requesting all subscriptions of a target node.
See also
query_subscribers_of
say_subscribes_to
Referenced by eagine::msgbus::subscriber_base::query_subscriptions_of().
respond_to()
auto eagine::msgbus::endpoint::respond_to (const message_info & info, const message_id msg_id, message_view message) -> bool inline noexcept
Posts a message as a response to another received message.
See also
message_info::setup_response
Referenced by respond_to().
say_bye()
EAGINE_LIB_FUNC auto eagine::msgbus::endpoint::say_bye () -> bool noexcept
Posts a message saying that this endpoint is about to disconnect.
See also
post
say_still_alive
Referenced by finish().
say_not_a_router()
auto eagine::msgbus::endpoint::say_not_a_router () -> bool noexcept
Posts a message saying that this is not a router bus node.
See also
post
say_not_subscribed_to()
EAGINE_LIB_FUNC void eagine::msgbus::endpoint::say_not_subscribed_to (const identifier_t target_id, const message_id msg_id) noexcept
Posts a message that this is not subscribed to message with given type.
See also
post_meta_message
say_subscribes_to
say_not_subscribed_to
say_still_alive()
EAGINE_LIB_FUNC auto eagine::msgbus::endpoint::say_still_alive () -> bool noexcept
Posts a message saying that this endpoint is alive.
See also
post
say_bye
Referenced by update().
say_subscribes_to() [1/2]
EAGINE_LIB_FUNC void eagine::msgbus::endpoint::say_subscribes_to (const identifier_t target_id, const message_id msg_id) noexcept
Posts a message that this subscribes to message with given id.
See also
post_meta_message_to
say_unsubscribes_from
say_not_subscribed_to
say_subscribes_to() [2/2]
EAGINE_LIB_FUNC void eagine::msgbus::endpoint::say_subscribes_to (const message_id msg_id) noexcept
Broadcasts a message that this subscribes to message with given id.
See also
post_meta_message
say_unsubscribes_from
say_not_subscribed_to
say_unsubscribes_from()
EAGINE_LIB_FUNC void eagine::msgbus::endpoint::say_unsubscribes_from (const message_id msg_id) noexcept
Broadcasts a message that this unsubscribes from message with given type.
See also
post_meta_message
say_subscribes_to
say_not_subscribed_to
set_id()
auto eagine::msgbus::endpoint::set_id (const identifier id) -> auto& inline noexcept
Assigns the unique id of this endpoint.
See also
preconfigure_id
has_id
get_id
Note
Do not set manually, use preconfigure_id instead.
The documentation for this class was generated from the following files:
eagine/msgbus/endpoint.hpp
eagine/msgbus/endpoint.inl
Copyright © 2015-2022 Mat Chochlk.
<chochlik -at -gmail.com>
Documentation generated on Wed May 18 2022 by Doxygen (version 1.9.1).