eagine::timeout Class Reference
EAGine (0.87.0) a C++ wrapper for rendering APIs
eagine::timeout Class Reference
Time and duration utilities
Class representing a timeout since construction or reset.
#include <eagine/timeout.hpp>
Public Types
using duration_type = _clock::duration
Alias for the duration type used by this timeout.
Public Member Functions
timeout () noexcept
Default construction. Saves current time. Immediately expires.
timeout (const _clock::duration duration, const _clock::duration initial) noexcept
Construction from the default and initial timeout duration.
timeout (const _clock::duration duration, const nothing_t) noexcept
Construction from the default and zero initial timeout duration.
timeout (const _clock::duration duration) noexcept
Construction from the default duration.
template<typename R , typename P >
timeout (const std::chrono::duration< R, P > duration) noexcept
Construction from the default duration.
auto reset () noexcept -> auto &
Resets the timeout using the previously specified duration.
auto reset (const _clock::duration duration, const _clock::duration initial) noexcept -> auto &
Resets the timeout using the specified duration values.
auto reset (const _clock::duration duration, const nothing_t) noexcept -> auto &
Resets the timeout using the specified duration values.
auto reset (const _clock::duration duration) noexcept -> auto &
Resets the timeout using the specified duration value.
auto elapsed_time () const noexcept -> duration_type
Returns the time since reset as clocks duration type.
auto is_expired () const noexcept -> bool
Indicates if the timeout is expired.
operator bool () const noexcept
Indicates if the timeout is expired.
auto period () const noexcept -> const auto &
Returns the timeout period.
Detailed Description
Class representing a timeout since construction or reset.
See also
time_measure
referencing_timeout
resetting_timeout
Constructor & Destructor Documentation
timeout() [1/5]
eagine::timeout::timeout () inline noexcept
Default construction. Saves current time. Immediately expires.
Postcondition
is_expired()
timeout() [2/5]
eagine::timeout::timeout (const _clock::duration duration, const _clock::duration initial) inline noexcept
Construction from the default and initial timeout duration.
See also
reset
period
Referenced by timeout().
timeout() [3/5]
eagine::timeout::timeout (const _clock::duration duration, const nothing_t) inline noexcept
Construction from the default and zero initial timeout duration.
See also
reset
period
timeout() [4/5]
eagine::timeout::timeout (const _clock::duration duration) inline noexcept
Construction from the default duration.
See also
reset
period
timeout() [5/5]
template<typename R , typename P > eagine::timeout::timeout (const std::chrono::duration< R, P > duration) inline noexcept
Construction from the default duration.
See also
reset
period
Member Function Documentation
is_expired()
auto eagine::timeout::is_expired () const -> bool inline noexcept
Indicates if the timeout is expired.
See also
reset
period
Referenced by eagine::msgbus::remote_host::is_alive(), eagine::msgbus::remote_instance::is_alive(), operator bool(), and eagine::resetting_timeout::operator bool().
operator bool()
eagine::timeout::operator bool () const inline explicit noexcept
Indicates if the timeout is expired.
See also
is_expired
period()
auto eagine::timeout::period () const -> const auto& inline noexcept
Returns the timeout period.
See also
reset
is_expired
reset() [1/2]
auto eagine::timeout::reset (const _clock::duration duration) -> auto& inline noexcept
Resets the timeout using the specified duration value.
See also
is_expired
reset() [2/2]
auto eagine::timeout::reset (const _clock::duration duration, const nothing_t) -> auto& inline noexcept
Resets the timeout using the specified duration values.
Postcondition
is_expired()
Referenced by eagine::msgbus::remote_node::set_ping_interval().
The documentation for this class was generated from the following file:
eagine/timeout.hpp
Copyright © 2015-2022 Matúš Chochlík.
<chochlik -at -gmail.com>
Documentation generated on Wed May 18 2022 by Doxygen (version 1.9.1).