eagine::msgbus::remote_node_tracker Class Reference
EAGine (0.87.0) a C++ wrapper for rendering APIs
eagine::msgbus::remote_node_tracker Class Reference
Message bus
Class tracking the state of remote message bus nodes.
#include <eagine/msgbus/remote_node.hpp>
Public Member Functions
remote_node_tracker () noexcept
Default constructor.
auto get_node (const identifier_t node_id) noexcept -> remote_node_state &
Finds and returns the state information about a remote bus node.
auto remove_node (const identifier_t node_id) noexcept -> bool
Removes tracked node with the specified id.
auto get_host (const host_id_t) noexcept -> remote_host_state &
Finds and returns the state information about a remote host.
auto get_host (const host_id_t) const noexcept -> remote_host_state
Finds and returns the state information about a remote host.
auto get_instance (const process_instance_id_t) noexcept -> remote_instance_state &
Finds and returns the information about a remote instance (process).
auto get_instance (const process_instance_id_t) const noexcept -> remote_instance_state
Finds and returns the information about a remote instance (process).
auto get_connection (const identifier_t node_id1, const identifier_t node_id2) noexcept -> node_connection_state &
Finds and returns the information about remote node connections.
auto get_connection (const identifier_t node_id1, const identifier_t node_id2) const noexcept -> node_connection_state
Finds and returns the information about remote node connections.
template<typename Function >
void for_each_host (Function func)
Calls a function on each tracked remote host.
template<typename Function >
void for_each_host_state (Function func)
Calls a function on each tracked remote host.
template<typename Function >
void for_each_node (Function func)
Calls a function on each tracked remote bus node.
template<typename Function >
void for_each_node_state (Function func)
Calls a function on each tracked remote bus node.
template<typename Function >
void for_each_instance_state (Function func)
Calls a function on each tracked remote bus instance.
template<typename Function >
void for_each_instance_node_state (const process_instance_id_t inst_id, Function func)
Calls a function on tracked remote bus nodes of an instance (process).
template<typename Function >
void for_each_host_node_state (const host_id_t host_id, Function func)
Calls a function on tracked remote bus nodes of a remote host.
template<typename Function >
void for_each_connection (Function func) const
Calls a function on tracked connections between bus nodes.
Detailed Description
Class tracking the state of remote message bus nodes.
See also
remote_node_changes
remote_host_changes
Member Function Documentation
for_each_connection()
template<typename Function > void eagine::msgbus::remote_node_tracker::for_each_connection (Function func) const
Calls a function on tracked connections between bus nodes.
See also
node_connection_state
for_each_node_state
The function is called with (const node_connection&) as argument.
Referenced by eagine::msgbus::remote_node::connections().
for_each_host()
template<typename Function > void eagine::msgbus::remote_node_tracker::for_each_host (Function func)
Calls a function on each tracked remote host.
See also
remote_host
for_each_host_state
for_each_node
The function is called with (host_id_t, const remote_host&) as arguments.
for_each_host_node_state()
template<typename Function > void eagine::msgbus::remote_node_tracker::for_each_host_node_state (const host_id_t host_id, Function func)
Calls a function on tracked remote bus nodes of a remote host.
See also
remote_node_state
for_each_node_state
for_each_instance_node_state
The function is called with (host_id_t, const remote_node_state&) as arguments. This function is subject to change without notice. Prefer using for_each_node.
for_each_host_state()
template<typename Function > void eagine::msgbus::remote_node_tracker::for_each_host_state (Function func)
Calls a function on each tracked remote host.
See also
remote_host_state
for_each_host
for_each_node
The function is called with (host_id_t, const remote_host_state&) as arguments. This function is subject to change without notice. Prefer using for_each_host.
for_each_instance_node_state()
template<typename Function > void eagine::msgbus::remote_node_tracker::for_each_instance_node_state (const process_instance_id_t inst_id, Function func)
Calls a function on tracked remote bus nodes of an instance (process).
See also
remote_node_state
for_each_node_state
for_each_host_node_state
The function is called with (host_id_t, const remote_node_state&) as arguments. This function is subject to change without notice. Prefer using for_each_node.
for_each_instance_state()
template<typename Function > void eagine::msgbus::remote_node_tracker::for_each_instance_state (Function func)
Calls a function on each tracked remote bus instance.
See also
remote_instance_state
for_each_node_state
for_each_host_state
The function is called with (process_instance_id_t, const remote_instance_state&) as arguments. This function is subject to change without notice.
for_each_node()
template<typename Function > void eagine::msgbus::remote_node_tracker::for_each_node (Function func)
Calls a function on each tracked remote bus node.
See also
remote_node
for_each_node_state
for_each_host
The function is called with (host_id_t, const remote_node&) as arguments.
for_each_node_state()
template<typename Function > void eagine::msgbus::remote_node_tracker::for_each_node_state (Function func)
Calls a function on each tracked remote bus node.
See also
remote_node_state
for_each_node
for_each_host
The function is called with (host_id_t, const remote_node_state&) as arguments. This function is subject to change without notice. Prefer using for_each_node.
get_connection() [1/2]
EAGINE_LIB_FUNC auto eagine::msgbus::remote_node_tracker::get_connection (const identifier_t node_id1, const identifier_t node_id2) const -> node_connection_state noexcept
Finds and returns the information about remote node connections.
See also
get_node
get_host
get_instance
for_each_connection
get_connection() [2/2]
EAGINE_LIB_FUNC auto eagine::msgbus::remote_node_tracker::get_connection (const identifier_t node_id1, const identifier_t node_id2) -> node_connection_state& noexcept
Finds and returns the information about remote node connections.
See also
get_node
get_host
get_instance
for_each_connection
Referenced by eagine::msgbus::node_connections::get().
get_host() [1/2]
EAGINE_LIB_FUNC auto eagine::msgbus::remote_node_tracker::get_host (const host_id_t host_id) const -> remote_host_state noexcept
Finds and returns the state information about a remote host.
See also
get_node
get_instance
get_connection
for_each_host
Referenced by eagine::msgbus::remote_instance::host(), and eagine::msgbus::remote_node::host().
get_host() [2/2]
EAGINE_LIB_FUNC auto eagine::msgbus::remote_node_tracker::get_host (const host_id_t host_id) -> remote_host_state& noexcept
Finds and returns the state information about a remote host.
See also
get_node
get_instance
get_connection
for_each_host
Referenced by eagine::msgbus::node_tracker< Base >::get_host().
get_instance() [1/2]
EAGINE_LIB_FUNC auto eagine::msgbus::remote_node_tracker::get_instance (const process_instance_id_t instance_id) const -> remote_instance_state noexcept
Finds and returns the information about a remote instance (process).
See also
get_node
get_host
get_connection
Referenced by eagine::msgbus::remote_node::instance().
get_instance() [2/2]
EAGINE_LIB_FUNC auto eagine::msgbus::remote_node_tracker::get_instance (const process_instance_id_t instance_id) -> remote_instance_state& noexcept
Finds and returns the information about a remote instance (process).
See also
get_node
get_host
get_connection
Referenced by eagine::msgbus::node_tracker< Base >::get_instance().
get_node()
EAGINE_LIB_FUNC auto eagine::msgbus::remote_node_tracker::get_node (const identifier_t node_id) -> remote_node_state& noexcept
Finds and returns the state information about a remote bus node.
See also
get_host
get_instance
get_connection
for_each_node
remove_node
Referenced by get_connection(), eagine::msgbus::node_tracker< Base >::get_node(), eagine::msgbus::node_connections::origin(), and eagine::msgbus::node_connections::remote().
remove_node()
EAGINE_LIB_FUNC auto eagine::msgbus::remote_node_tracker::remove_node (const identifier_t node_id) -> bool noexcept
Removes tracked node with the specified id.
See also
get_node
The documentation for this class was generated from the following files:
eagine/msgbus/remote_node.hpp
eagine/msgbus/remote_node.inl
Copyright © 2015-2022 Mat Chochlk.
<chochlik -at -gmail.com>
Documentation generated on Wed May 18 2022 by Doxygen (version 1.9.1).