eagine::memory::basic_span< ValueType, Pointer, SizeType > Class Template Reference
EAGine (0.87.0) a C++ wrapper for rendering APIs
eagine::memory::basic_span< ValueType, Pointer, SizeType > Class Template Reference
Type utilities
Non-owning view of a contiguous range of memory with ValueType elements.
#include <eagine/memory/span.hpp>
Public Types
using value_type = ValueType
The element value type.
using size_type = SizeType
The element count type.
using address_type = basic_address< std::is_const_v< ValueType > >
The memory address type.
using pointer = Pointer
The pointer type.
using iterator = Pointer
The iterator type.
using const_iterator = Pointer
The const iterator type.
using reverse_iterator = std::reverse_iterator< iterator >
The reverse iterator type.
Public Member Functions
constexpr basic_span (pointer addr, const size_type len) noexcept
Construction from pointer and length.
constexpr basic_span (const address_type addr, const size_type len) noexcept
Construction from memory address and length.
constexpr basic_span (pointer b, pointer e) noexcept
Construction from a pair of pointers.
constexpr basic_span (const address_type ba, const address_type be) noexcept
Construction from a pair of memory addresses.
constexpr basic_span () noexcept=default
Default constructor. Constructs an empty span.
constexpr basic_span (const basic_span &) noexcept=default
Copy constructor.
constexpr basic_span (basic_span &&) noexcept=default
Move constructor.
auto operator= (const basic_span &) noexcept -> basic_span &=default
Copy assignment operator.
auto operator= (basic_span &&) noexcept -> basic_span &=default
Move assignment operator.
template<typename T , typename P , typename S , typename = enable_if_convertible<T, P, S>, typename = enable_if_different<T, P, S>>
constexpr basic_span (basic_span< T, P, S > that) noexcept
Converting copy constructor from span of compatible elements.
template<typename T , typename P , typename S , typename = enable_if_convertible<T, P, S>, typename = enable_if_different<T, P, S>>
auto operator= (basic_span< T, P, S > that) noexcept -> auto &
Converting copy assignment from span of compatible elements.
auto reset () noexcept -> auto &
Resets this span.
auto reset (pointer addr, const size_type length) noexcept -> auto &
Resets this span with a new pointer and length.
auto reset (const address_type addr, const size_type length) noexcept -> auto &
Resets this span with a new memory address and length.
auto reset (pointer b, pointer e) noexcept -> auto &
Resets this span with a pair or pointers.
constexpr operator bool () const noexcept
Indicates that the span is not empty.
constexpr auto is_empty () const noexcept -> bool
Indicates that the span is empty.
constexpr auto empty () const noexcept -> bool
Indicates that the span is empty.
constexpr auto is_zero_terminated () const noexcept -> bool
Indicates that the span is terminated with value T(0) if applicable.
constexpr auto size () const noexcept -> size_type
Returns the number of elements in the span.
constexpr auto data () const noexcept -> pointer
Returns a pointer to the start of the span.
constexpr auto begin () const noexcept -> iterator
Returns an interator to the start of the span.
constexpr auto end () const noexcept -> iterator
Returns a iterator past the end of the span.
constexpr auto rbegin () const noexcept
Returns a reverse interator to the end of the span.
constexpr auto rend () const noexcept
Returns a reverse interator past the begin of the span.
constexpr auto addr () const noexcept -> address_type
Returns the memory address of the start of the span.
constexpr auto begin_addr () const noexcept -> address_type
Returns the memory address of the start of the span.
constexpr auto end_addr () const noexcept -> address_type
Returns the memory address past the end of the span.
template<typename X >
auto is_aligned_as () const noexcept -> bool
Checks if the start of the span is aligned as the alignment of X.
auto encloses (const pointer p) const noexcept -> bool
Indicates if this span encloses the specified address.
auto encloses (const const_address a) const noexcept -> bool
Indicates if this span encloses the specified address.
template<typename Ts , typename Ps , typename Ss >
auto contains (basic_span< Ts, Ps, Ss > that) const noexcept -> bool
Indicates if this span encloses another span.
template<typename Ts , typename Ps , typename Ss >
auto overlaps (const basic_span< Ts, Ps, Ss > &that) const noexcept -> bool
Indicates if this span overlaps with another span.
constexpr auto ref (const size_type index) const noexcept -> std::add_const_t< value_type > &
Returns a const reference to value at the specified index.
auto ref (const size_type index) noexcept -> value_type &
Returns a reference to value at the specified index.
auto front () const noexcept -> const value_type &
Returns a const reference to value at the front of the span.
auto front () noexcept -> value_type &
Returns a reference to value at the front of the span.
auto back () const noexcept -> const value_type &
Returns a const reference to value at the back of the span.
auto back () noexcept -> value_type &
Returns a const reference to value at the back of the span.
template<typename Int >
constexpr auto element (const Int index) const noexcept -> std::add_const_t< value_type > &requires(std::is_integral_v< Int >)
Returns a const reference to value at the specified index.
template<typename Int >
auto element (const Int index) noexcept -> value_type &requires(std::is_integral_v< Int >)
Returns a reference to value at the specified index.
template<typename Int >
auto operator[] (const Int index) noexcept -> value_type &requires(std::is_integral_v< Int >)
Array subscript operator.
template<typename Int >
constexpr auto operator[] (const Int index) const noexcept -> std::add_const_t< value_type > &requires(std::is_integral_v< Int >)
Array subscript operator.
Related Functions
(Note that these are not member functions.)
template<typename T , typename P , typename S , typename Output >
static auto list_to_stream (Output &out, const memory::basic_span< T, P, S > s) -> Output &
Helper function for pretty-printing spans as lists into output streams.
template<typename Input , typename T , typename P , typename S >
static auto read_from_stream (Input &in, memory::basic_span< T, P, S > s) -> auto &
Helper function for raw-reading spans from output streams.
template<typename Output , typename T , typename P , typename S >
static auto write_to_stream (Output &out, const memory::basic_span< T, P, S > s) -> auto &
Helper function for raw-reading spans into output streams.
template<typename T , typename P , typename S >
static auto operator<< (std::ostream &out, const memory::basic_span< T, P, S > s) -> std::ostream &requires(!std::is_same_v< std::remove_const_t< T >, char >)
Operator for printing generic element spans into output streams.
template<typename T , typename P , typename S >
static auto operator<< (std::ostream &out, const memory::basic_span< T, P, S > s) -> std::ostream &requires(std::is_same_v< std::remove_const_t< T >, char >)
Operator for printing spans of string characters into output streams.
template<typename T , typename P , typename S >
static auto make_span_getter (span_size_t &i, const memory::basic_span< T, P, S > spn)
Makes a callable that returns consecutive span elements starting at i.
template<typename T , typename P , typename S , typename Transform >
static auto make_span_getter (span_size_t &i, const memory::basic_span< T, P, S > spn, const Transform transform)
Makes a callable getting consecutive, transformed span elements starting at i.
template<typename T , typename P , typename S >
static auto make_span_putter (span_size_t &i, memory::basic_span< T, P, S > spn)
Makes a callable setting consecutive elements of a span starting at i.
template<typename T , typename P , typename S , typename Transform >
static auto make_span_putter (span_size_t &i, memory::basic_span< T, P, S > spn, Transform transform)
Makes a callable setting consecutive elements of a span starting at i.
Detailed Description
template<typename ValueType, typename Pointer = ValueType*, typename SizeType = span_size_t>
class eagine::memory::basic_span< ValueType, Pointer, SizeType >
Non-owning view of a contiguous range of memory with ValueType elements.
Template Parameters
ValueType the type of elements assumed in the covered memory range.
Pointer the pointer type used to point to the start of the span.
SizeType the integer type used to count the elements in the span.
See also
basic_block
basic_split_span
This template is similar to std::span but allows to specify other pointer types besides ValueType*, for example basic_offset_ptr, etc. and to specify the size type.
Constructor & Destructor Documentation
basic_span()
template<typename ValueType , typename Pointer = ValueType*, typename SizeType = span_size_t> constexpr eagine::memory::basic_span< ValueType, Pointer, SizeType >::basic_span () constexpr default noexcept
Default constructor. Constructs an empty span.
Postcondition
is_empty()
size() == 0
Referenced by eagine::file_contents::block(), eagine::data_compressor::compress(), eagine::data_compressor::decompress(), eagine::valtree::compound_interface::find(), eagine::get_data_with_size(), eagine::msgbus::context::get_own_signature(), eagine::msgbus::context::get_remote_certificate_pem(), eagine::msgbus::message_view::signature(), eagine::msgbus::stored_message::signature(), and eagine::store_data_with_size().
Member Function Documentation
back() [1/2]
template<typename ValueType , typename Pointer = ValueType*, typename SizeType = span_size_t> auto eagine::memory::basic_span< ValueType, Pointer, SizeType >::back () const -> const value_type& inline noexcept
Returns a const reference to value at the back of the span.
See also
front
Precondition
!is_empty()
back() [2/2]
template<typename ValueType , typename Pointer = ValueType*, typename SizeType = span_size_t> auto eagine::memory::basic_span< ValueType, Pointer, SizeType >::back () -> value_type& inline noexcept
Returns a const reference to value at the back of the span.
See also
front
Precondition
!is_empty()
contains()
template<typename ValueType , typename Pointer = ValueType*, typename SizeType = span_size_t> template<typename Ts , typename Ps , typename Ss > auto eagine::memory::basic_span< ValueType, Pointer, SizeType >::contains (basic_span< Ts, Ps, Ss > that) const -> bool inline noexcept
Indicates if this span encloses another span.
See also
encloses
overlaps
data()
template<typename ValueType , typename Pointer = ValueType*, typename SizeType = span_size_t> constexpr auto eagine::memory::basic_span< ValueType, Pointer, SizeType >::data () const -> pointer inline constexpr noexcept
Returns a pointer to the start of the span.
See also
begin
end
size
Referenced by eagine::oglplus::glsl_string_ref::glsl_string_ref(), eagine::memory::buffer::data(), eagine::oglplus::gl_api_traits::link_function(), eagine::eglplus::egl_api_traits::link_function(), eagine::oalplus::al_api_traits::link_function(), eagine::oalplus::alc_api_traits::link_function(), eagine::oalplus::al_api_traits::load_constant(), and eagine::oalplus::alc_api_traits::load_constant().
element() [1/2]
template<typename ValueType , typename Pointer = ValueType*, typename SizeType = span_size_t> template<typename Int > constexpr auto eagine::memory::basic_span< ValueType, Pointer, SizeType >::element (const Int index) const -> std::add_const_t<value_type>& requires(std::is_integral_v<Int>) inline constexpr noexcept
Returns a const reference to value at the specified index.
Precondition
0 <= index < size()
element() [2/2]
template<typename ValueType , typename Pointer = ValueType*, typename SizeType = span_size_t> template<typename Int > auto eagine::memory::basic_span< ValueType, Pointer, SizeType >::element (const Int index) -> value_type& requires(std::is_integral_v<Int>) inline noexcept
Returns a reference to value at the specified index.
Precondition
0 <= index < size()
empty()
template<typename ValueType , typename Pointer = ValueType*, typename SizeType = span_size_t> constexpr auto eagine::memory::basic_span< ValueType, Pointer, SizeType >::empty () const -> bool inline constexpr noexcept
Indicates that the span is empty.
See also
is_empty
size
Referenced by eagine::memory::owned_block::~owned_block(), eagine::msgbus::remote_node::has_endpoint_info(), eagine::substitute_variable_into(), and eagine::substitute_variables_into().
encloses() [1/2]
template<typename ValueType , typename Pointer = ValueType*, typename SizeType = span_size_t> auto eagine::memory::basic_span< ValueType, Pointer, SizeType >::encloses (const const_address a) const -> bool inline noexcept
Indicates if this span encloses the specified address.
See also
contains
encloses() [2/2]
template<typename ValueType , typename Pointer = ValueType*, typename SizeType = span_size_t> auto eagine::memory::basic_span< ValueType, Pointer, SizeType >::encloses (const pointer p) const -> bool inline noexcept
Indicates if this span encloses the specified address.
See also
contains
front() [1/2]
template<typename ValueType , typename Pointer = ValueType*, typename SizeType = span_size_t> auto eagine::memory::basic_span< ValueType, Pointer, SizeType >::front () const -> const value_type& inline noexcept
Returns a const reference to value at the front of the span.
See also
back
Precondition
!is_empty()
front() [2/2]
template<typename ValueType , typename Pointer = ValueType*, typename SizeType = span_size_t> auto eagine::memory::basic_span< ValueType, Pointer, SizeType >::front () -> value_type& inline noexcept
Returns a reference to value at the front of the span.
See also
back
Precondition
!is_empty()
Referenced by eagine::data_compressor::compress().
is_empty()
template<typename ValueType , typename Pointer = ValueType*, typename SizeType = span_size_t> constexpr auto eagine::memory::basic_span< ValueType, Pointer, SizeType >::is_empty () const -> bool inline constexpr noexcept
Indicates that the span is empty.
See also
size
Referenced by eagine::memory::basic_span< ValueType, Pointer, SizeType >::operator bool().
operator bool()
template<typename ValueType , typename Pointer = ValueType*, typename SizeType = span_size_t> constexpr eagine::memory::basic_span< ValueType, Pointer, SizeType >::operator bool () const inline explicit constexpr noexcept
Indicates that the span is not empty.
See also
is_empty
size
operator[]() [1/2]
template<typename ValueType , typename Pointer = ValueType*, typename SizeType = span_size_t> template<typename Int > constexpr auto eagine::memory::basic_span< ValueType, Pointer, SizeType >::operator[] (const Int index) const -> std::add_const_t<value_type>& requires(std::is_integral_v<Int>) inline constexpr noexcept
Array subscript operator.
See also
element
operator[]() [2/2]
template<typename ValueType , typename Pointer = ValueType*, typename SizeType = span_size_t> template<typename Int > auto eagine::memory::basic_span< ValueType, Pointer, SizeType >::operator[] (const Int index) -> value_type& requires(std::is_integral_v<Int>) inline noexcept
Array subscript operator.
See also
element
overlaps()
template<typename ValueType , typename Pointer = ValueType*, typename SizeType = span_size_t> template<typename Ts , typename Ps , typename Ss > auto eagine::memory::basic_span< ValueType, Pointer, SizeType >::overlaps (const basic_span< Ts, Ps, Ss > & that) const -> bool inline noexcept
Indicates if this span overlaps with another span.
See also
encloses
contains
ref() [1/2]
template<typename ValueType , typename Pointer = ValueType*, typename SizeType = span_size_t> constexpr auto eagine::memory::basic_span< ValueType, Pointer, SizeType >::ref (const size_type index) const -> std::add_const_t<value_type>& inline constexpr noexcept
Returns a const reference to value at the specified index.
Precondition
index < size()
ref() [2/2]
template<typename ValueType , typename Pointer = ValueType*, typename SizeType = span_size_t> auto eagine::memory::basic_span< ValueType, Pointer, SizeType >::ref (const size_type index) -> value_type& inline noexcept
Returns a reference to value at the specified index.
Precondition
index < size()
reset()
template<typename ValueType , typename Pointer = ValueType*, typename SizeType = span_size_t> auto eagine::memory::basic_span< ValueType, Pointer, SizeType >::reset () -> auto& inline noexcept
Resets this span.
Postcondition
is_empty()
Referenced by eagine::memory::owned_block::operator=(), eagine::memory::block_owner::release_block(), eagine::substitute_variable_into(), and eagine::substitute_variables_into().
size()
template<typename ValueType , typename Pointer = ValueType*, typename SizeType = span_size_t> constexpr auto eagine::memory::basic_span< ValueType, Pointer, SizeType >::size () const -> size_type inline constexpr noexcept
Returns the number of elements in the span.
See also
is_empty
Referenced by eagine::oglplus::glsl_string_ref::glsl_string_ref(), eagine::memory::basic_span< ValueType, Pointer, SizeType >::back(), eagine::memory::buffer::capacity(), eagine::data_compressor::compress(), eagine::memory::basic_span< ValueType, Pointer, SizeType >::empty(), eagine::memory::basic_span< ValueType, Pointer, SizeType >::end(), eagine::deserializer_data_source::fetch_all(), eagine::memory::basic_span< ValueType, Pointer, SizeType >::front(), eagine::memory::basic_span< ValueType, Pointer, SizeType >::is_empty(), eagine::program_arg::is_long_tag(), eagine::program_arg::is_prefixed_tag(), eagine::program_arg::is_short_tag(), eagine::oglplus::gl_api_traits::link_function(), eagine::eglplus::egl_api_traits::link_function(), eagine::oalplus::al_api_traits::link_function(), eagine::oalplus::alc_api_traits::link_function(), eagine::oalplus::al_api_traits::load_constant(), eagine::oalplus::alc_api_traits::load_constant(), eagine::basic_string_path::pop_back(), eagine::memory::basic_span< ValueType, Pointer, SizeType >::ref(), eagine::block_data_sink::remaining_size(), eagine::block_data_sink::replace_with(), eagine::deserializer_data_source::scan_until(), eagine::msgbus::stored_message::store_and_sign(), eagine::store_data_with_size(), eagine::substitute_variable_into(), eagine::substitute_variables(), eagine::substitute_variables_into(), and eagine::block_data_sink::write().
Friends And Related Function Documentation
operator<<()
template<typename T , typename P , typename S > static auto operator<< (std::ostream & out, const memory::basic_span< T, P, S > s) -> std::ostream& requires(std::is_same_v<std::remove_const_t<T>, char>) related
Operator for printing spans of string characters into output streams.
See also
write_to_stream
The documentation for this class was generated from the following file:
eagine/memory/span.hpp
Copyright © 2015-2022 Mat Chochlk.
<chochlik -at -gmail.com>
Documentation generated on Wed May 18 2022 by Doxygen (version 1.9.1).