eagine::memory::buffer Class Reference
EAGine (0.87.0) a C++ wrapper for rendering APIs
eagine::memory::buffer Class Reference
Memory utilities
Reallocatable owning byte buffer.
#include <eagine/memory/buffer.hpp>
Public Types
using size_type = typename block::size_type
Buffer size type.
using pointer = typename block::pointer
Pointer type.
Public Member Functions
constexpr buffer () noexcept=default
Default constructor.
buffer (const span_size_t align) noexcept
Constructor with explicit alignment specification.
buffer (shared_byte_allocator alloc) noexcept
Constructor with injected allocator.
buffer (const span_size_t align, shared_byte_allocator alloc) noexcept
Constructor with explicit alignment specification and allocator.
buffer (buffer &&temp) noexcept
Move constructor.
auto operator= (buffer &&temp) noexcept -> buffer &
Move assignment operator.
buffer (const buffer &)=delete
Not copyable.
auto operator= (const buffer &)=delete
Not copy assignable.
auto addr () const noexcept
Returns the memory address of the start of the allocated space.
auto data () const noexcept -> pointer
Returns the pointer to the start of the allocated space.
constexpr auto size () const noexcept -> span_size_t
Returns the size of the buffer in bytes.
constexpr auto empty () const noexcept
Indicates that the buffer is empty.
constexpr auto capacity () const noexcept -> span_size_t
Returns the capacity of this buffer.
auto reserve (const span_size_t new_size) noexcept -> auto &
Pre-allocate the specified number of bytes.
auto resize (const span_size_t new_size) noexcept -> auto &
Resizes the buffer to the specified number of bytes.
auto ensure (const span_size_t new_size) noexcept -> auto &
Ensure that the buuffer has at least the specified size in bytes.
auto enlarge_by (const span_size_t inc_size) noexcept -> auto &
Enlarges the buffer by the specified number of bytes.
auto clear () noexcept -> auto &
Clears the buffer.
void free () noexcept
Deallocates the buffer.
operator block () noexcept
Implicit conversion to block.
operator const_block () const noexcept
Implicit conversion to const_block.
Detailed Description
Reallocatable owning byte buffer.
See also
block
Member Function Documentation
capacity()
constexpr auto eagine::memory::buffer::capacity () const -> span_size_t inline constexpr noexcept
Returns the capacity of this buffer.
See also
reserve
resize
Referenced by reserve().
clear()
auto eagine::memory::buffer::clear () -> auto& inline noexcept
Clears the buffer.
See also
size
resize
reserve
free
Postcondition
empty()
empty()
constexpr auto eagine::memory::buffer::empty () const inline constexpr noexcept
Indicates that the buffer is empty.
See also
size
capacity
enlarge_by()
auto eagine::memory::buffer::enlarge_by (const span_size_t inc_size) -> auto& inline noexcept
Enlarges the buffer by the specified number of bytes.
See also
size
resize
reserve
ensure
ensure()
auto eagine::memory::buffer::ensure (const span_size_t new_size) -> auto& inline noexcept
Ensure that the buuffer has at least the specified size in bytes.
See also
size
resize
reserve
enlarge_by
free()
void eagine::memory::buffer::free () inline noexcept
Deallocates the buffer.
See also
size
resize
reserve
clear
Postcondition
empty() && capacity() == 0
Referenced by operator=().
reserve()
auto eagine::memory::buffer::reserve (const span_size_t new_size) -> auto& inline noexcept
Pre-allocate the specified number of bytes.
See also
capacity
resize
Referenced by resize().
resize()
auto eagine::memory::buffer::resize (const span_size_t new_size) -> auto& inline noexcept
Resizes the buffer to the specified number of bytes.
See also
size
ensure
reserve
Referenced by clear(), enlarge_by(), ensure(), eagine::istream_data_source::pop(), and eagine::istream_data_source::top().
size()
constexpr auto eagine::memory::buffer::size () const -> span_size_t inline constexpr noexcept
Returns the size of the buffer in bytes.
See also
empty
capacity
Referenced by empty(), enlarge_by(), ensure(), eagine::istream_data_source::pop(), and eagine::istream_data_source::top().
The documentation for this class was generated from the following file:
eagine/memory/buffer.hpp
Copyright © 2015-2022 Matúš Chochlík.
<chochlik -at -gmail.com>
Documentation generated on Wed May 18 2022 by Doxygen (version 1.9.1).