eagine::msgbus::remote_host Class Reference
EAGine (0.87.0) a C++ wrapper for rendering APIs
eagine::msgbus::remote_host Class Reference
Message bus
Class providing information about a remote host of bus nodes.
#include <eagine/msgbus/remote_node.hpp>
Public Member Functions
operator bool () const noexcept
Indicates if this is not-empty and has actual information.
auto id () const noexcept -> valid_if_not_zero< host_id_t >
Returns the unique host id.
auto is_alive () const noexcept -> bool
Indicates if the remote host is reachable/alive.
auto name () const noexcept -> valid_if_not_empty< string_view >
Returns the name of the remote host.
auto cpu_concurrent_threads () const noexcept -> valid_if_positive< span_size_t >
Returns the number of concurrent threads supported at the host.
auto short_average_load () const noexcept -> valid_if_nonnegative< float >
Returns the short average load on the remote host.
auto short_average_load_change () const noexcept -> optionally_valid< float >
Returns the change in short average load on the remote host.
auto long_average_load () const noexcept -> valid_if_nonnegative< float >
Returns the long average load on the remote host.
auto long_average_load_change () const noexcept -> optionally_valid< float >
Returns the change in long average load on the remote host.
auto total_ram_size () const noexcept -> valid_if_positive< span_size_t >
Returns the total RAM size on the remote host.
auto free_ram_size () const noexcept -> valid_if_positive< span_size_t >
Returns the free RAM size on the remote host.
auto free_ram_size_change () const noexcept -> optionally_valid< span_size_t >
Returns the change in free RAM size on the remote host.
auto ram_usage () const noexcept -> valid_if_nonnegative< float >
Returns the RAM usage on the remote host (0.0, 1.0).
auto ram_usage_change () const noexcept -> optionally_valid< float >
Returns the change in RAM usage on the remote host (-1.0, 1.0).
auto total_swap_size () const noexcept -> valid_if_positive< span_size_t >
Returns the total swap size on the remote host.
auto free_swap_size () const noexcept -> valid_if_nonnegative< span_size_t >
Returns the free swap size on the remote host.
auto free_swap_size_change () const noexcept -> optionally_valid< span_size_t >
Returns the change in free swap size on the remote host.
auto swap_usage () const noexcept -> valid_if_nonnegative< float >
Returns the swap usage on the remote host (0.0, 1.0).
auto swap_usage_change () const noexcept -> optionally_valid< float >
Returns the change in swap usage on the remote host (-1.0, 1.0).
auto min_temperature () const noexcept -> valid_if_positive< kelvins_t< float >>
Returns the minimum temperature recorded on the remote host.
auto max_temperature () const noexcept -> valid_if_positive< kelvins_t< float >>
Returns the maximum temperature recorded on the remote host.
auto min_temperature_change () const noexcept -> optionally_valid< kelvins_t< float >>
Returns the change in minimum temperature on the remote host.
auto max_temperature_change () const noexcept -> optionally_valid< kelvins_t< float >>
Returns the change in maximum temperature on the remote host.
auto power_supply () const noexcept -> power_supply_kind
Returns the power supply kind used on the remote host.
Detailed Description
Class providing information about a remote host of bus nodes.
See also
remote_node_tracker
remote_node
remote_instance
node_connection
Member Function Documentation
free_ram_size()
EAGINE_LIB_FUNC auto eagine::msgbus::remote_host::free_ram_size () const -> valid_if_positive<span_size_t> noexcept
Returns the free RAM size on the remote host.
See also
total_ram_size
free_swap_size
free_ram_size_change
ram_usage
system_info::free_ram_size
Referenced by ram_usage().
free_ram_size_change()
EAGINE_LIB_FUNC auto eagine::msgbus::remote_host::free_ram_size_change () const -> optionally_valid<span_size_t> noexcept
Returns the change in free RAM size on the remote host.
See also
free_ram_size
Referenced by ram_usage_change().
free_swap_size()
EAGINE_LIB_FUNC auto eagine::msgbus::remote_host::free_swap_size () const -> valid_if_nonnegative<span_size_t> noexcept
Returns the free swap size on the remote host.
See also
total_swap_size
free_ram_size
free_swap_size_change
swap_usage
system_info::total_ram_size
Referenced by swap_usage().
free_swap_size_change()
EAGINE_LIB_FUNC auto eagine::msgbus::remote_host::free_swap_size_change () const -> optionally_valid<span_size_t> noexcept
Returns the change in free swap size on the remote host.
See also
free_swap_size
Referenced by swap_usage_change().
long_average_load()
EAGINE_LIB_FUNC auto eagine::msgbus::remote_host::long_average_load () const -> valid_if_nonnegative<float> noexcept
Returns the long average load on the remote host.
See also
short_average_load
system_info::long_average_load
long_average_load_change()
EAGINE_LIB_FUNC auto eagine::msgbus::remote_host::long_average_load_change () const -> optionally_valid<float> noexcept
Returns the change in long average load on the remote host.
See also
long_average_load
max_temperature()
EAGINE_LIB_FUNC auto eagine::msgbus::remote_host::max_temperature () const -> valid_if_positive<kelvins_t<float>> noexcept
Returns the maximum temperature recorded on the remote host.
See also
min_temperature
max_temperature_change
max_temperature_change()
EAGINE_LIB_FUNC auto eagine::msgbus::remote_host::max_temperature_change () const -> optionally_valid<kelvins_t<float>> noexcept
Returns the change in maximum temperature on the remote host.
See also
max_temperature
min_temperature()
EAGINE_LIB_FUNC auto eagine::msgbus::remote_host::min_temperature () const -> valid_if_positive<kelvins_t<float>> noexcept
Returns the minimum temperature recorded on the remote host.
See also
max_temperature
min_temperature_change
min_temperature_change()
EAGINE_LIB_FUNC auto eagine::msgbus::remote_host::min_temperature_change () const -> optionally_valid<kelvins_t<float>> noexcept
Returns the change in minimum temperature on the remote host.
See also
min_temperature
ram_usage()
auto eagine::msgbus::remote_host::ram_usage () const -> valid_if_nonnegative<float> inline noexcept
Returns the RAM usage on the remote host (0.0, 1.0).
See also
ram_usage_change
total_ram_size
free_ram_size
ram_usage_change()
auto eagine::msgbus::remote_host::ram_usage_change () const -> optionally_valid<float> inline noexcept
Returns the change in RAM usage on the remote host (-1.0, 1.0).
See also
ram_usage
short_average_load()
EAGINE_LIB_FUNC auto eagine::msgbus::remote_host::short_average_load () const -> valid_if_nonnegative<float> noexcept
Returns the short average load on the remote host.
See also
long_average_load
short_average_load_change
system_info::short_average_load
short_average_load_change()
EAGINE_LIB_FUNC auto eagine::msgbus::remote_host::short_average_load_change () const -> optionally_valid<float> noexcept
Returns the change in short average load on the remote host.
See also
short_average_load
swap_usage()
auto eagine::msgbus::remote_host::swap_usage () const -> valid_if_nonnegative<float> inline noexcept
Returns the swap usage on the remote host (0.0, 1.0).
See also
total_swap_size
free_swap_size
swap_usage_change()
auto eagine::msgbus::remote_host::swap_usage_change () const -> optionally_valid<float> inline noexcept
Returns the change in swap usage on the remote host (-1.0, 1.0).
See also
swap_usage
total_ram_size()
EAGINE_LIB_FUNC auto eagine::msgbus::remote_host::total_ram_size () const -> valid_if_positive<span_size_t> noexcept
Returns the total RAM size on the remote host.
See also
free_ram_size
total_swap_size
ram_usage
system_info::total_ram_size
Referenced by ram_usage(), and ram_usage_change().
total_swap_size()
EAGINE_LIB_FUNC auto eagine::msgbus::remote_host::total_swap_size () const -> valid_if_positive<span_size_t> noexcept
Returns the total swap size on the remote host.
See also
free_swap_size
total_ram_size
free_swap_size_change
ram_usage
swap_usage
system_info::total_swap_size
Referenced by swap_usage(), and swap_usage_change().
The documentation for this class was generated from the following files:
eagine/msgbus/remote_node.hpp
eagine/msgbus/remote_node.inl
Copyright © 2015-2022 Mat Chochlk.
<chochlik -at -gmail.com>
Documentation generated on Wed May 18 2022 by Doxygen (version 1.9.1).