eagine::oglplus::vertex_attrib_bindings Class Reference
EAGine (0.87.0) a C++ wrapper for rendering APIs
eagine::oglplus::vertex_attrib_bindings Class Reference
Shape generators and loaders
Class that specifies bindings between attribute variant and array index.
#include <eagine/oglplus/shapes/bindings.hpp>
Public Member Functions
vertex_attrib_bindings (const shape_generator &shape)
Constructor matching supported attributes from a shape generator.
vertex_attrib_bindings (std::initializer_list< shapes::vertex_attrib_variant > vavs)
Constructor matching supported attributes from a shape generator.
auto attrib_count () const -> span_size_t
Returns the number of attributes in the binding.
auto attrib_variant (span_size_t index) const -> shapes::vertex_attrib_variant
Returns the attribute variant bound to specified index.
auto attrib_kinds () const -> shapes::vertex_attrib_kinds
Returns the attribute kind bits for all attributes in this binding.
auto location (shapes::vertex_attrib_variant vav) -> vertex_attrib_location
Returns the index at which the specified attribute variant is bound.
auto position_loc (span_size_t idx=0) -> vertex_attrib_location
Returns the index at which the position variant is bound.
auto normal_loc (span_size_t idx=0) -> vertex_attrib_location
Returns the index at which the normal variant is bound.
auto tangent_loc (span_size_t idx=0) -> vertex_attrib_location
Returns the index at which the tangent variant is bound.
auto bitangent_loc (span_size_t idx=0) -> vertex_attrib_location
Returns the index at which the bitangent variant is bound.
auto pivot_loc (span_size_t idx=0) -> vertex_attrib_location
Returns the index at which the shape pivot variant is bound.
auto vertex_pivot_loc (span_size_t idx=0) -> vertex_attrib_location
Returns the index at which the vertex pivot variant is bound.
auto box_coord_loc (span_size_t idx=0) -> vertex_attrib_location
Returns the index at which the box_coord variant is bound.
auto face_coord_loc (span_size_t idx=0) -> vertex_attrib_location
Returns the index at which the face_coord variant is bound.
auto wrap_coord_loc (span_size_t idx=0) -> vertex_attrib_location
Returns the index at which the wrap_coord variant is bound.
auto color_loc (span_size_t idx=0) -> vertex_attrib_location
Returns the index at which the color variant is bound.
auto weight_loc (span_size_t idx=0) -> vertex_attrib_location
Returns the index at which the weight variant is bound.
auto occlusion_loc (span_size_t idx=0) -> vertex_attrib_location
Returns the index at which the occlusion variant is bound.
Detailed Description
Class that specifies bindings between attribute variant and array index.
See also
generator
geometry
Member Function Documentation
attrib_count()
auto eagine::oglplus::vertex_attrib_bindings::attrib_count () const -> span_size_t inline
Returns the number of attributes in the binding.
See also
attrib_variant
Referenced by attrib_variant(), and eagine::oglplus::geometry::init().
attrib_variant()
auto eagine::oglplus::vertex_attrib_bindings::attrib_variant (span_size_t index) const -> shapes::vertex_attrib_variant inline
Returns the attribute variant bound to specified index.
See also
attrib_count
location
Precondition
index < attrib_count()
bitangent_loc()
auto eagine::oglplus::vertex_attrib_bindings::bitangent_loc (span_size_t idx = 0) -> vertex_attrib_location inline
Returns the index at which the bitangent variant is bound.
See also
location
box_coord_loc()
auto eagine::oglplus::vertex_attrib_bindings::box_coord_loc (span_size_t idx = 0) -> vertex_attrib_location inline
Returns the index at which the box_coord variant is bound.
See also
location
color_loc()
auto eagine::oglplus::vertex_attrib_bindings::color_loc (span_size_t idx = 0) -> vertex_attrib_location inline
Returns the index at which the color variant is bound.
See also
location
face_coord_loc()
auto eagine::oglplus::vertex_attrib_bindings::face_coord_loc (span_size_t idx = 0) -> vertex_attrib_location inline
Returns the index at which the face_coord variant is bound.
See also
location
location()
auto eagine::oglplus::vertex_attrib_bindings::location (shapes::vertex_attrib_variant vav) -> vertex_attrib_location inline
Returns the index at which the specified attribute variant is bound.
See also
attrib_variant
Referenced by bitangent_loc(), box_coord_loc(), color_loc(), face_coord_loc(), normal_loc(), occlusion_loc(), pivot_loc(), position_loc(), tangent_loc(), vertex_pivot_loc(), weight_loc(), and wrap_coord_loc().
normal_loc()
auto eagine::oglplus::vertex_attrib_bindings::normal_loc (span_size_t idx = 0) -> vertex_attrib_location inline
Returns the index at which the normal variant is bound.
See also
location
occlusion_loc()
auto eagine::oglplus::vertex_attrib_bindings::occlusion_loc (span_size_t idx = 0) -> vertex_attrib_location inline
Returns the index at which the occlusion variant is bound.
See also
location
pivot_loc()
auto eagine::oglplus::vertex_attrib_bindings::pivot_loc (span_size_t idx = 0) -> vertex_attrib_location inline
Returns the index at which the shape pivot variant is bound.
See also
location
position_loc()
auto eagine::oglplus::vertex_attrib_bindings::position_loc (span_size_t idx = 0) -> vertex_attrib_location inline
Returns the index at which the position variant is bound.
See also
location
tangent_loc()
auto eagine::oglplus::vertex_attrib_bindings::tangent_loc (span_size_t idx = 0) -> vertex_attrib_location inline
Returns the index at which the tangent variant is bound.
See also
location
vertex_pivot_loc()
auto eagine::oglplus::vertex_attrib_bindings::vertex_pivot_loc (span_size_t idx = 0) -> vertex_attrib_location inline
Returns the index at which the vertex pivot variant is bound.
See also
location
weight_loc()
auto eagine::oglplus::vertex_attrib_bindings::weight_loc (span_size_t idx = 0) -> vertex_attrib_location inline
Returns the index at which the weight variant is bound.
See also
location
wrap_coord_loc()
auto eagine::oglplus::vertex_attrib_bindings::wrap_coord_loc (span_size_t idx = 0) -> vertex_attrib_location inline
Returns the index at which the wrap_coord variant is bound.
See also
location
The documentation for this class was generated from the following file:
eagine/oglplus/shapes/bindings.hpp
Copyright © 2015-2022 Matúš Chochlík.
<chochlik -at -gmail.com>
Documentation generated on Wed May 18 2022 by Doxygen (version 1.9.1).