eagine::build_info Class Reference
EAGine (0.87.0) a C++ wrapper for rendering APIs
eagine::build_info Class Reference
Program utilities and main context
Class providing basic system information.
#include <eagine/build_info.hpp>
Public Member Functions
auto install_prefix () const noexcept -> valid_if_not_empty< string_view >
Paths to the install directory.
auto config_dir_path () const noexcept -> valid_if_not_empty< string_view >
Paths to the install prefix configuration directory.
auto version_tuple () const noexcept -> const std::tuple< int, int, int, int > &
Returns the project version numbers in a single tuple.
auto version_major () const noexcept -> valid_if_nonnegative< int >
Returns the project major version number.
auto version_minor () const noexcept -> valid_if_nonnegative< int >
Returns the project minor version number.
auto version_patch () const noexcept -> valid_if_nonnegative< int >
Returns the project patch number.
auto version_commit () const noexcept -> valid_if_nonnegative< int >
Returns the project commit number.
auto has_version () const noexcept -> bool
Indicates if major and minor version numbers are known.
auto version_at_least (int major, int minor) const -> tribool
Checks if the project build version is at least as specified.
auto version_at_least (int major, int minor, int patch) const -> tribool
Checks if the project build version is at least as specified.
auto version_at_least (int major, int minor, int patch, int commit) const -> tribool
Checks if the project build version is at least as specified.
Detailed Description
Class providing basic system information.
Member Function Documentation
config_dir_path()
EAGINE_LIB_FUNC auto eagine::build_info::config_dir_path () const -> valid_if_not_empty<string_view> noexcept
Paths to the install prefix configuration directory.
See also
install_prefix
has_version()
auto eagine::build_info::has_version () const -> bool inline noexcept
Indicates if major and minor version numbers are known.
See also
version_major
version_minor
install_prefix()
EAGINE_LIB_FUNC auto eagine::build_info::install_prefix () const -> valid_if_not_empty<string_view> noexcept
Paths to the install directory.
See also
config_dir_path
version_commit()
auto eagine::build_info::version_commit () const -> valid_if_nonnegative<int> inline noexcept
Returns the project commit number.
See also
version_tuple
version_major
version_minor
version_patch
Referenced by version_at_least().
version_major()
auto eagine::build_info::version_major () const -> valid_if_nonnegative<int> inline noexcept
Returns the project major version number.
See also
version_tuple
version_minor
version_patch
version_commit
Referenced by has_version(), and version_at_least().
version_minor()
auto eagine::build_info::version_minor () const -> valid_if_nonnegative<int> inline noexcept
Returns the project minor version number.
See also
version_tuple
version_major
version_patch
version_commit
Referenced by has_version(), and version_at_least().
version_patch()
auto eagine::build_info::version_patch () const -> valid_if_nonnegative<int> inline noexcept
Returns the project patch number.
See also
version_tuple
version_major
version_minor
version_commit
Referenced by version_at_least().
version_tuple()
auto eagine::build_info::version_tuple () const -> const std::tuple<int, int, int, int>& inline noexcept
Returns the project version numbers in a single tuple.
See also
version_major
version_minor
version_patch
version_commit
Referenced by version_commit(), version_major(), version_minor(), and version_patch().
The documentation for this class was generated from the following files:
eagine/build_info.hpp
eagine/build_info.inl
Copyright © 2015-2022 Matúš Chochlík.
<chochlik -at -gmail.com>
Documentation generated on Wed May 18 2022 by Doxygen (version 1.9.1).