eagine::basic_valid_if< T, Policy, DoLog, P > Class Template Reference
EAGine (0.87.0) a C++ wrapper for rendering APIs
eagine::basic_valid_if< T, Policy, DoLog, P > Class Template Reference
Conditionally valid values
Basic template for conditionally-valid values.
#include <eagine/valid_if/base.hpp>
Public Member Functions
auto policy () noexcept -> Policy &
Returns a reference to this object's policy.
auto policy () const noexcept -> const Policy &
Returns a const reference to this object's policy.
constexpr basic_valid_if () noexcept(std::is_nothrow_default_constructible_v< T >)=default
Default constructor.
constexpr basic_valid_if (T val) noexcept(std::is_nothrow_move_constructible_v< T >) requires(!std
Constructor initializing the stored value by val.
constexpr basic_valid_if (T val, Policy plcy) noexcept(noexcept(std::is_nothrow_move_constructible_v< value_type > &&std::is_nothrow_move_constructible_v< Policy >)) requires(!std
Constructor initializing the stored value and policy.
basic_valid_if (basic_valid_if &&that) noexcept(std::is_nothrow_move_constructible_v< value_type > &&std::is_nothrow_move_constructible_v< Policy >)
Move constructor.
constexpr basic_valid_if (const basic_valid_if &that) noexcept(std::is_nothrow_copy_constructible_v< T > &&std::is_nothrow_copy_constructible_v< Policy >)
Copy constructor.
auto operator= (basic_valid_if &&that) noexcept(std::is_nothrow_move_assignable_v< value_type > &&std::is_nothrow_move_assignable_v< Policy >) -> auto &
Move assignment operator.
auto operator= (const basic_valid_if &that) noexcept(std::is_nothrow_copy_constructible_v< value_type > &&std::is_nothrow_copy_constructible_v< Policy >) -> auto &
Copy assignment operator.
auto operator= (const value_type &value) noexcept(std::is_nothrow_copy_assignable_v< value_type >) -> auto &
Copies value into this instance.
~basic_valid_if () noexcept=default
The destructor.
constexpr auto is_valid (const_reference val, P... p) const noexcept -> bool
Checks if val is valid according to this object's policy.
constexpr auto is_valid (P... p) const noexcept
Checks if the stored value is valid according to policy.
constexpr auto has_value (P... p) const noexcept
Checks if the stored value is valid according to policy.
operator bool () const noexcept
Indicates if the stored value is valid according to policy.
constexpr auto operator== (const value_type &v) const -> tribool
Equality comparison of the stored value with v.
constexpr auto operator!= (const value_type &v) const -> tribool
Non-equality comparison of the stored value with v.
constexpr auto operator< (const value_type &v) const -> tribool
Less-than comparison of the stored value with v.
constexpr auto operator> (const value_type &v) const -> tribool
Greater-than comparison of the stored value with v.
constexpr auto operator<= (const value_type &v) const -> tribool
Less-equal comparison of the stored value with v.
constexpr auto operator>= (const value_type &v) const -> tribool
Greater-equal comparison of the stored value with v.
template<typename Func >
auto call_if_invalid (Func func, P... p) -> auto &
Calls the specified function if the stored value is invalid.
void throw_if_invalid (P... p) const
Throws an exception if the stored value is invalid.
auto value (P... p) -> T &
Returns the stored value if it is valid otherwise throws.
auto value (P... p) const -> const T &
Returns the stored value if it is valid, otherwise throws.
auto value_or (reference fallback, P... p) noexcept -> auto &
Returns the stored value if valid, otherwise returns fallback.
constexpr auto value_or (const_reference fallback, P... p) const noexcept -> auto &
Returns the stored value if valid, otherwise returns fallback.
constexpr auto value_anyway () const noexcept -> const auto &
Returns the stored value regardless of its validity.
constexpr auto value_anyway () noexcept -> auto &
Returns the stored value regardless of its validity.
template<typename Func >
auto then (const Func &func) const -> basic_valid_if< std::invoke_result_t< Func, T >, valid_flag_policy, typename valid_flag_policy::do_log > requires(!std::is_same_v< std::invoke_result_t< Func, T >, void >)
Calls the specified function if the stored value is valid.
template<typename Func >
auto operator| (const Func &func) const
Calls the specified function if the stored valus is valid.
template<typename Func >
constexpr auto transformed (Func func, P... p) const noexcept -> basic_valid_if< std::invoke_result_t< Func, T, bool >, valid_flag_policy, typename valid_flag_policy::do_log >
Calls a binary transforming function on {value, is_valid()} pair.
auto operator/ (const_reference fallback) const noexcept -> const_reference
Returns the stored value if valid, returns fallback otherwise.
auto operator* () const noexcept -> const_reference
Returns the stored value, throws if it is invalid.
auto operator-> () const noexcept -> const_pointer
Returns pointer to the stored value, throws if it is invalid.
Friends
constexpr friend auto operator== (const basic_valid_if &a, const basic_valid_if &b) noexcept -> bool
Equality comparison.
Detailed Description
template<typename T, typename Policy, typename DoLog, typename... P>
class eagine::basic_valid_if< T, Policy, DoLog, P >
Basic template for conditionally-valid values.
Template Parameters
T type of the stored, conditionally valid value.
Policy indicates under what conditions is the stored value valid.
Examples
eagine/valid_if.cpp.
Member Function Documentation
call_if_invalid()
template<typename T , typename Policy , typename DoLog , typename... P> template<typename Func > auto eagine::basic_valid_if< T, Policy, DoLog, P >::call_if_invalid (Func func, P... p) -> auto& inline
Calls the specified function if the stored value is invalid.
Parameters
func the function to be called.
p additional parameters for the policy validity check function.
has_value()
template<typename T , typename Policy , typename DoLog , typename... P> constexpr auto eagine::basic_valid_if< T, Policy, DoLog, P >::has_value (P... p) const inline constexpr noexcept
Checks if the stored value is valid according to policy.
Parameters
p additional parameters for the policy validity check function.
is_valid() [1/2]
template<typename T , typename Policy , typename DoLog , typename... P> constexpr auto eagine::basic_valid_if< T, Policy, DoLog, P >::is_valid (const_reference val, P... p) const -> bool inline constexpr noexcept
Checks if val is valid according to this object's policy.
Parameters
p additional parameters for the policy validity check function.
is_valid() [2/2]
template<typename T , typename Policy , typename DoLog , typename... P> constexpr auto eagine::basic_valid_if< T, Policy, DoLog, P >::is_valid (P... p) const inline constexpr noexcept
Checks if the stored value is valid according to policy.
Parameters
p additional parameters for the policy validity check function.
Referenced by eagine::program_args::is_valid().
operator bool()
template<typename T , typename Policy , typename DoLog , typename... P> eagine::basic_valid_if< T, Policy, DoLog, P >::operator bool () const inline explicit noexcept
Indicates if the stored value is valid according to policy.
See also
is_valid
operator*()
template<typename T , typename Policy , typename DoLog , typename... P> auto eagine::basic_valid_if< T, Policy, DoLog, P >::operator* () const -> const_reference inline noexcept
Returns the stored value, throws if it is invalid.
See also
basic_valid_if::value
Exceptions
std::runtime_error
operator->()
template<typename T , typename Policy , typename DoLog , typename... P> auto eagine::basic_valid_if< T, Policy, DoLog, P >::operator-> () const -> const_pointer inline noexcept
Returns pointer to the stored value, throws if it is invalid.
See also
basic_valid_if::value
Exceptions
std::runtime_error
operator/()
template<typename T , typename Policy , typename DoLog , typename... P> auto eagine::basic_valid_if< T, Policy, DoLog, P >::operator/ (const_reference fallback) const -> const_reference inline noexcept
Returns the stored value if valid, returns fallback otherwise.
See also
basic_valid_if::value_or
operator|()
template<typename T , typename Policy , typename DoLog , typename... P> template<typename Func > auto eagine::basic_valid_if< T, Policy, DoLog, P >::operator| (const Func & func) const inline
Calls the specified function if the stored valus is valid.
Parameters
func the function to call.
See also
then
then()
template<typename T , typename Policy , typename DoLog , typename... P> template<typename Func > auto eagine::basic_valid_if< T, Policy, DoLog, P >::then (const Func & func) const -> basic_valid_if< std::invoke_result_t<Func, T>, valid_flag_policy, typename valid_flag_policy:: do_log> requires(!std::is_same_v<std::invoke_result_t<Func, T>, void>) inline
Calls the specified function if the stored value is valid.
Parameters
func the function to be called.
throw_if_invalid()
template<typename T , typename Policy , typename DoLog , typename... P> void eagine::basic_valid_if< T, Policy, DoLog, P >::throw_if_invalid (P... p) const inline
Throws an exception if the stored value is invalid.
Parameters
p additional parameters for the policy validity check function.
Exceptions
std::runtime_error
Referenced by eagine::basic_valid_if< T, Policy, DoLog, P >::value().
transformed()
template<typename T , typename Policy , typename DoLog , typename... P> template<typename Func > constexpr auto eagine::basic_valid_if< T, Policy, DoLog, P >::transformed (Func func, P... p) const -> basic_valid_if< std::invoke_result_t<Func, T, bool>, valid_flag_policy, typename valid_flag_policy::do_log> inline constexpr noexcept
Calls a binary transforming function on {value, is_valid()} pair.
Parameters
func the function to be called.
value() [1/2]
template<typename T , typename Policy , typename DoLog , typename... P> auto eagine::basic_valid_if< T, Policy, DoLog, P >::value (P... p) -> T& inline
Returns the stored value if it is valid otherwise throws.
Parameters
p additional parameters for the policy validity check function.
Exceptions
std::runtime_error
value() [2/2]
template<typename T , typename Policy , typename DoLog , typename... P> auto eagine::basic_valid_if< T, Policy, DoLog, P >::value (P... p) const -> const T& inline
Returns the stored value if it is valid, otherwise throws.
Parameters
p additional parameters for the policy validity check function.
Exceptions
std::runtime_error
Referenced by eagine::substitute_variables_into().
value_or() [1/2]
template<typename T , typename Policy , typename DoLog , typename... P> constexpr auto eagine::basic_valid_if< T, Policy, DoLog, P >::value_or (const_reference fallback, P... p) const -> auto& inline constexpr noexcept
Returns the stored value if valid, otherwise returns fallback.
Parameters
p additional parameters for the policy validity check function.
Referenced by eagine::program_args::is_valid().
value_or() [2/2]
template<typename T , typename Policy , typename DoLog , typename... P> auto eagine::basic_valid_if< T, Policy, DoLog, P >::value_or (reference fallback, P... p) -> auto& inline noexcept
Returns the stored value if valid, otherwise returns fallback.
Parameters
p additional parameters for the policy validity check function.
The documentation for this class was generated from the following file:
eagine/valid_if/base.hpp
Copyright © 2015-2022 Mat Chochlk.
<chochlik -at -gmail.com>
Documentation generated on Wed May 18 2022 by Doxygen (version 1.9.1).