eagine::msgbus::message_view Class Reference
EAGine (0.87.0) a C++ wrapper for rendering APIs
eagine::msgbus::message_view Class Reference
Message bus
Combines message information and a non-owning view to message content.
#include <eagine/msgbus/message.hpp>
Public Member Functions
constexpr message_view () noexcept=default
Default constructor.
constexpr message_view (const memory::const_block init) noexcept
Construction from a const memory block.
constexpr message_view (memory::block init) noexcept
Construction from a mutable memory block.
constexpr message_view (const string_view init) noexcept
Construction from a string view.
constexpr message_view (const message_info info, memory::const_block init) noexcept
Construction from a message info and a const memory block.
auto is_signed () const noexcept -> bool
Indicates if the header or the content is signed.
auto data () const noexcept -> memory::const_block
Returns a const view of the storage buffer.
auto signature () const noexcept -> memory::const_block
Returns the message signature.
auto content () const noexcept -> memory::const_block
Returns a const view of the data content of the message.
auto text_content () const noexcept
Returns the content as a const string view.
Public Member Functions inherited from eagine::msgbus::message_info
auto too_many_hops () const noexcept -> bool
Indicates that the message made too many hops.
auto add_hop () noexcept -> auto &
Increments the hop counter.
auto too_old () const noexcept -> bool
Indicates that the message is too old.
auto add_age (const message_age age) noexcept -> auto &
Adds to the age seconds counter.
auto age () const noexcept -> message_age
Returns the message age.
auto set_priority (const message_priority new_priority) noexcept -> auto &
Sets the priority of this message.
auto set_source_id (const identifier_t id) noexcept -> auto &
Sets the source endpoint identifier.
auto set_target_id (const identifier_t id) noexcept -> auto &
Sets the target endpoint identifier.
auto has_serializer_id (const identifier id) const noexcept -> bool
Tests if a data serializer with the specified id was used.
auto set_serializer_id (const identifier id) noexcept -> auto &
Sets the id of the used data content serializer.
auto set_sequence_no (const message_sequence_t no) noexcept -> auto &
Sets the sequence number of this message (has message-type specific meaning).
auto setup_response (const message_info &info) noexcept -> auto &
Sets the target id to be the source id from info, copies sequence number.
Additional Inherited Members
Public Types inherited from eagine::msgbus::message_info
using sequence_t = message_sequence_t
Alias for the sequence number type.
using hop_count_t = std::int8_t
Alias for type used to store the message hop count.
using age_t = std::int8_t
Alias for type used to store the message age in quarter seconds.
Public Attributes inherited from eagine::msgbus::message_info
identifier_t source_id
Returns the source endpoint identifier.
identifier_t target_id
Returns the target endpoint identifier.
identifier_t serializer_id
Returns the identifier of the used serializer.
sequence_t sequence_no
The message sequence number.
hop_count_t hop_count
The message hop counter.
age_t age_quarter_seconds
The message age in quarter seconds.
message_priority priority
The message priority.
message_crypto_flags crypto_flags
The message cryptography flags.
Detailed Description
Combines message information and a non-owning view to message content.
Member Function Documentation
content()
auto eagine::msgbus::message_view::content () const -> memory::const_block inline noexcept
Returns a const view of the data content of the message.
See also
signature
text_content
const_content
Referenced by text_content().
is_signed()
auto eagine::msgbus::message_view::is_signed () const -> bool inline noexcept
Indicates if the header or the content is signed.
See also
signature
Referenced by content(), and signature().
signature()
auto eagine::msgbus::message_view::signature () const -> memory::const_block inline noexcept
Returns the message signature.
See also
is_signed
content
text_content()
auto eagine::msgbus::message_view::text_content () const inline noexcept
Returns the content as a const string view.
See also
content
The documentation for this class was generated from the following file:
eagine/msgbus/message.hpp
Copyright © 2015-2022 Matúš Chochlík.
<chochlik -at -gmail.com>
Documentation generated on Wed May 18 2022 by Doxygen (version 1.9.1).