eagine::msgbus::posix_mqueue Class Reference
EAGine (0.87.0) a C++ wrapper for rendering APIs
eagine::msgbus::posix_mqueue Class Reference
Message bus
Class wrapping a POSIX message queue.
#include <eagine/msgbus/posix_mqueue.hpp>
Public Types
using receive_handler = callable_ref< void(unsigned, span< const char >) noexcept >
Alias for received message handler.
Public Types inherited from eagine::named_logging_object< main_ctx_log_backend_getter >
using entry_type = std::conditional_t< is_log_level_enabled_v< severity >, log_entry, no_log_entry >
The entry type for the specified log_event_severity.
Public Types inherited from eagine::basic_logger< BackendGetter >
template<log_event_severity severity>
using entry_type = std::conditional_t< is_log_level_enabled_v< severity >, log_entry, no_log_entry >
The entry type for the specified log_event_severity.
Public Member Functions
posix_mqueue (posix_mqueue &&temp) noexcept
Move constructible.
posix_mqueue (const posix_mqueue &)=delete
Not copy constructible.
auto operator= (posix_mqueue &&temp)=delete
Not move assignable.
auto operator= (const posix_mqueue &)=delete
Not copy assignable.
auto get_name () const noexcept -> string_view
Returns the unique name of this queue.
auto set_name (std::string name) noexcept -> auto &
Sets the unique name of the queue.
auto set_name (const identifier id) noexcept -> auto &
Sets the unique name of the queue.
posix_mqueue (main_ctx_parent parent, std::string name) noexcept
Constructs the queue and sets the specified name.
auto error_message () const noexcept -> std::string
Returns the error message of the last failed operation.
auto had_error () const noexcept -> bool
Indicates if there a previous operation finished with an error.
auto needs_retry () const noexcept -> bool
Indicates if a previous operation on the queue needs to be retried.
constexpr auto is_open () const noexcept -> bool
Indicates if this message queue is open.
constexpr auto is_usable () const noexcept -> bool
Indicates if this message queue can be used.
auto unlink () noexcept -> auto &
Unlinks the OS queue objects.
auto create () noexcept -> auto &
Creates new OS queue objects.
auto open () noexcept -> auto &
Opens existing OS queue objects.
auto close () noexcept -> posix_mqueue &
Closes the OS queue objects.
auto max_data_size () noexcept -> valid_if_positive< span_size_t >
Returns the absolute maximum block size that can be sent in a message.
auto data_size () noexcept -> span_size_t
Returns the maximum block size that can be sent in a message.
auto send (const unsigned priority, const span< const char > blk) noexcept -> auto &
Sends a block of data with the specified priority.
auto receive (memory::span< char > blk, const receive_handler handler) noexcept -> bool
Receives messages and calls the specified handler on them.
Public Member Functions inherited from eagine::main_ctx_object
main_ctx_object (const identifier obj_id, main_ctx_parent parent) noexcept
Initialization from object id and parent.
auto as_parent () noexcept -> main_ctx_object_parent_info
Returns this as main_ctx_object_parent_info.
auto main_context () const noexcept -> main_ctx &
Returns a reference to the main context singleton.
auto process_instance_id () const noexcept -> process_instance_id_t
Returns the process id.
auto app_config () const noexcept -> application_config &
Returns a reference to the application config object.
template<typename T >
auto cfg_init (const string_view key, T initial, const string_view tag={}) noexcept -> T
Reads and returns the configuration value identified by key.
template<typename Extractable , typename T >
auto cfg_extr (const string_view key, T initial, const string_view tag={}, const type_identity< Extractable >={}) noexcept -> T
Reads and returns the configuration value identified by key.
auto cio () const noexcept -> const console &
Returns a reference to the console object.
auto cio_print (const console_entry_kind kind, const string_view format) const noexcept -> console_entry
Shorthand for cio().print(...)
auto cio_print (const string_view format) const noexcept -> console_entry
Shorthand for cio().print(...)
auto cio_warning (const string_view format) const noexcept -> console_entry
Shorthand for cio().warning(...)
auto cio_error (const string_view format) const noexcept -> console_entry
Shorthand for cio().error(...)
auto progress () const noexcept -> const activity_progress &
Returns a reference to the root activity object.
auto bus () const noexcept -> message_bus &
Returns a reference to the message bus object.
Public Member Functions inherited from eagine::named_logging_object< main_ctx_log_backend_getter >
named_logging_object (const identifier id, main_ctx_log_backend_getter backend_getter) noexcept
Constructor from identifier and backend_getter object.
named_logging_object (const identifier id, const named_logging_object &parent) noexcept
Constructor from logger id and parent logging object.
constexpr named_logging_object () noexcept=default
Construct logging object without backend.
named_logging_object (named_logging_object &&temp) noexcept
Move constructor.
named_logging_object (const named_logging_object &that) noexcept
Copy constructor.
auto operator= (named_logging_object &&) noexcept -> named_logging_object &=default
Move assignment operator.
auto operator= (const named_logging_object &) -> named_logging_object &=default
Copy assignment operator.
constexpr auto object_id () const noexcept
Returns the identifier of this logging object.
void object_description (const string_view display_name, const string_view description) noexcept
Sets the human-readable name and description of this object.
auto log_fatal (const string_view format) const noexcept
Create a log message entry for fatal error, with specified format.
auto log_error (const string_view format) const noexcept
Create a log message entry for error, with specified format.
auto log_warning (const string_view format) const noexcept
Create a log message entry for warning, with specified format.
auto log_info (const string_view format) const noexcept
Create a log message entry for information, with specified format.
auto log_stat (const string_view format) const noexcept
Create a log message entry for statistic, with specified format.
auto log_debug (const string_view format) const noexcept
Create a log message entry for debugging, with specified format.
auto log_trace (const string_view format) const noexcept
Create a log message entry for tracing, with specified format.
auto log_backtrace (const string_view format) const noexcept
Create a log message entry for backtracing, with specified format.
auto log_debug_stream () const noexcept
Returns a log entry stream for debug messages.
auto log_error_stream () const noexcept
Returns a log entry stream for error messages.
auto log_chart_sample (const identifier series, const float value) const noexcept -> const named_logging_object &
Stores a new value in the specified chart data series.
auto log_chart_sample (const identifier series, const tagged_quantity< T, U > &qty) const noexcept -> const named_logging_object &requires(std::is_convertible_v< T, float >)
Stores a new value in the specified chart data series.
auto log_chart_sample (const identifier series, const valid_if< T, P > &opt_value) const noexcept -> const named_logging_object &
Stores a new value in the specified chart data series.
Public Member Functions inherited from eagine::basic_logger< BackendGetter >
auto backend () const noexcept
Returns a pointer to the backend of this logger object.
auto instance_id () const noexcept -> logger_instance_id
Returns the unique id of this logger instance.
Detailed Description
Class wrapping a POSIX message queue.
Member Typedef Documentation
receive_handler
using eagine::msgbus::posix_mqueue::receive_handler = callable_ref<void(unsigned, span<const char>) noexcept>
Alias for received message handler.
See also
receive
Constructor & Destructor Documentation
posix_mqueue()
eagine::msgbus::posix_mqueue::posix_mqueue (main_ctx_parent parent, std::string name) inline noexcept
Constructs the queue and sets the specified name.
See also
set_name
Member Function Documentation
close()
auto eagine::msgbus::posix_mqueue::close () -> posix_mqueue& inline noexcept
Closes the OS queue objects.
See also
create
open
unlink
create()
auto eagine::msgbus::posix_mqueue::create () -> auto& inline noexcept
Creates new OS queue objects.
See also
unlink
open
close
error_message()
auto eagine::msgbus::posix_mqueue::error_message () const -> std::string inline noexcept
Returns the error message of the last failed operation.
See also
had_error
get_name()
auto eagine::msgbus::posix_mqueue::get_name () const -> string_view inline noexcept
Returns the unique name of this queue.
See also
set_name
Referenced by create(), open(), receive(), and unlink().
had_error()
auto eagine::msgbus::posix_mqueue::had_error () const -> bool inline noexcept
Indicates if there a previous operation finished with an error.
See also
error_message
needs_retry
Referenced by is_usable().
is_open()
constexpr auto eagine::msgbus::posix_mqueue::is_open () const -> bool inline constexpr noexcept
Indicates if this message queue is open.
See also
is_usable
Referenced by close(), is_usable(), max_data_size(), receive(), and send().
is_usable()
constexpr auto eagine::msgbus::posix_mqueue::is_usable () const -> bool inline constexpr noexcept
Indicates if this message queue can be used.
See also
is_open
had_error
max_data_size()
auto eagine::msgbus::posix_mqueue::max_data_size () -> valid_if_positive<span_size_t> inline noexcept
Returns the absolute maximum block size that can be sent in a message.
See also
data_size
needs_retry()
auto eagine::msgbus::posix_mqueue::needs_retry () const -> bool inline noexcept
Indicates if a previous operation on the queue needs to be retried.
See also
had_error
Referenced by is_usable().
open()
auto eagine::msgbus::posix_mqueue::open () -> auto& inline noexcept
Opens existing OS queue objects.
See also
create
unlink
close
set_name() [1/2]
auto eagine::msgbus::posix_mqueue::set_name (const identifier id) -> auto& inline noexcept
Sets the unique name of the queue.
See also
get_name
set_name() [2/2]
auto eagine::msgbus::posix_mqueue::set_name (std::string name) -> auto& inline noexcept
Sets the unique name of the queue.
See also
get_name
Referenced by set_name().
unlink()
auto eagine::msgbus::posix_mqueue::unlink () -> auto& inline noexcept
Unlinks the OS queue objects.
See also
create
open
close
The documentation for this class was generated from the following file:
eagine/msgbus/posix_mqueue.hpp
Copyright © 2015-2022 Mat Chochlk.
<chochlik -at -gmail.com>
Documentation generated on Wed May 18 2022 by Doxygen (version 1.9.1).