String utilities
EAGine (0.87.0) a C++ wrapper for rendering APIs
String utilities
Classes
class eagine::basic_c_str< C, P, S, isConst >
Helper template for getting zero-terminated strings from string spans.
class eagine::basic_string_span< C, P, S >
Specialization of memory::basic_span for character string containers.
struct eagine::basic_view_less< Spn >
Comparator template for string span - string span comparisons.
struct eagine::basic_str_view_less< Str, Spn >
Comparator template for standard string - string span comparisons.
class eagine::fixed_size_string< N >
String with maximum fixed-size internal storage.
struct eagine::variable_substitution_options
Options for string variable substitution customization.
class eagine::string_variable_map
Class storing a map of variable names to values, doing string substitution.
class eagine::basic_string_path
Basic class storing paths made of string elements.
class eagine::format_string_and_list< N >
Helper class used in implementation of string variable substitution.
Typedefs
using eagine::string_span = basic_string_span< char >
Alias for mutable string spans.
using eagine::string_view = basic_string_span< const char >
Alias for const string views.
using eagine::str_view_less = basic_str_view_less< std::string, string_view >
Comparator template for standard string - string_view comparisons.
Functions
template<typename C , typename P , typename S >
static constexpr auto eagine::c_str (const memory::basic_span< C, P, S > s) -> basic_c_str< C, P, S > requires(std::is_convertible_v< memory::basic_span< C, P, S >, basic_string_span< C, P, S >>)
Functions that construct a basic_c_str from a basic_string_span.
template<typename C , typename P , typename S >
static constexpr auto eagine::std_view (const memory::basic_span< C, P, S > spn) noexcept -> std::basic_string_view< std::remove_const_t< C >>
Converts a basic_span of characters to string_span.
template<typename C , typename P , typename S >
static constexpr auto eagine::to_string (const memory::basic_span< C, P, S > spn) -> std::basic_string< std::remove_const_t< C >>
Converts a basic_span of characters to standard string.
template<typename C , typename T , typename A , typename P , typename S >
static constexpr auto eagine::assign_to (std::basic_string< C, T, A > &str, const memory::basic_span< const C, P, S > spn) -> auto &
Assigns the contents of a span of characters to a standard string.
template<typename C , typename T , typename A , typename P , typename S >
static constexpr auto eagine::append_to (std::basic_string< C, T, A > &str, const memory::basic_span< const C, P, S > spn) -> auto &
Appends the contents of a span of characters to a standard string.
template<span_size_t N>
static constexpr auto eagine::make_fixed_size_string (const char(&str)[N]) noexcept
Creates a fixed_size_string from a C-string literal.
template<span_size_t N1, span_size_t N2>
static constexpr auto eagine::operator+ (const fixed_size_string< N1 > &s1, const fixed_size_string< N2 > &s2) noexcept
Concatenation operator for fixed_size_string.
template<int I>
static constexpr auto eagine::to_fixed_size_string (const int_constant< I >) noexcept requires((I >=0) &&(I< 10))
Converts a single-digit decimal number into fixed_size_string.
template<int I>
static constexpr auto eagine::to_fixed_size_string (const int_constant< I >) noexcept requires(I > 9)
Converts a multi-digit decimal number into fixed_size_string.
auto eagine::substitute_variable_into (std::string &dst, string_view src, const string_view name, const string_view value, const variable_substitution_options={}) noexcept -> std::string &
Substitutes variable value from src into dst.
auto eagine::substitute_variables_into (std::string &dst, string_view src, const callable_ref< optionally_valid< string_view >(const string_view) noexcept > &translate, const variable_substitution_options={}) noexcept -> std::string &
Substitutes variable values by using translate, from src into dst.
auto eagine::substitute_variables (const string_view src, const callable_ref< optionally_valid< string_view >(const string_view) noexcept > &translate, const variable_substitution_options={}) noexcept -> std::string
Substitutes variable values by using translate, from src.
auto eagine::substitute_variables (const std::string &str, const span< const std::string > strings, const variable_substitution_options={}) noexcept -> std::string
Substitutes variable values by using translate, from src into dst.
auto eagine::substitute_variables (const std::string &str, const std::map< std::string, std::string, str_view_less > &dictionary, const variable_substitution_options={}) noexcept -> std::string
Substitutes variable values by using translate, from src.
template<span_size_t N>
static auto eagine::operator% (format_string_and_list< N > &&fsal, std::string &&val) noexcept -> format_string_and_list< N+1 >
Operator for adding variable name and value for string formatting.
static auto eagine::format (std::string &&fmt_str) noexcept -> format_string_and_list< 0 >
Takes a format string, returns an object for variable specification.
template<typename C , typename T , typename A , typename P1 , typename P2 , typename S1 , typename S2 >
auto eagine::string_replace (std::basic_string< C, T, A > &str, const memory::basic_span< const C, P1, S1 > from, const memory::basic_span< const C, P2, S2 > to) noexcept -> std::basic_string< C, T, A > &
Replaces all occurrences of from with to in the given string.
template<typename C , typename T , typename A , typename P1 , typename P2 , typename S1 , typename S2 >
auto eagine::string_replace (std::basic_string< C, T, A > &str, const span< const std::tuple< basic_string_span< const C, P1, S1 >, basic_string_span< const C, P2, S2 >>> dict) noexcept -> std::basic_string< C, T, A > &
Replaces all occurrences of the string specifed in the dictionary.
Detailed Description
Function Documentation
operator%()
template<span_size_t N> static auto eagine::operator% (format_string_and_list< N > && fsal, std::string && val) -> format_string_and_list<N + 1> inline static noexcept
Operator for adding variable name and value for string formatting.
See also
format
substitute_variable_into()
EAGINE_LIB_FUNC auto eagine::substitute_variable_into (std::string & dst, string_view src, const string_view name, const string_view value, const variable_substitution_options opts = {}) -> std::string& noexcept
Substitutes variable value from src into dst.
See also
substitute_variables
This function takes the format string src, finds variable reference using substitution options and substitutes the variable with the specified value into dst.
substitute_variables() [1/3]
EAGINE_LIB_FUNC auto eagine::substitute_variables (const std::string & str, const span< const std::string > strings, const variable_substitution_options opts = {}) -> std::string noexcept
Substitutes variable values by using translate, from src into dst.
See also
substitute_variables_into
This function takes the format string src, finds numeric variable references using substitution options and substitutes the variables with their values the strings span and returns the resulting string.
substitute_variables() [2/3]
EAGINE_LIB_FUNC auto eagine::substitute_variables (const std::string & str, const std::map< std::string, std::string, str_view_less > & dictionary, const variable_substitution_options opts = {}) -> std::string noexcept
Substitutes variable values by using translate, from src.
See also
substitute_variables_into
This function takes the format string src, finds variable references using substitution options and substitutes the variables with their values using the dictionary map and returns the resulting string.
Referenced by eagine::string_variable_map::operator()(), and eagine::string_variable_map::subst_variables().
substitute_variables() [3/3]
EAGINE_LIB_FUNC auto eagine::substitute_variables (const string_view src, const callable_ref< optionally_valid< string_view >(const string_view) noexcept > & translate, const variable_substitution_options opts = {}) -> std::string noexcept
Substitutes variable values by using translate, from src.
See also
substitute_variables_into
This function takes the format string src, finds variable references using substitution options and substitutes the variables with their values using the translation function and returns the resulting string.
Referenced by eagine::substitute_variables().
substitute_variables_into()
EAGINE_LIB_FUNC auto eagine::substitute_variables_into (std::string & dst, string_view src, const callable_ref< optionally_valid< string_view >(const string_view) noexcept > & translate, const variable_substitution_options opts = {}) -> std::string& noexcept
Substitutes variable values by using translate, from src into dst.
See also
substitute_variables
This function takes the format string src, finds variable references using substitution options and substitutes the variables with their values using the translation function into dst.
Referenced by eagine::substitute_variables(), and eagine::substitute_variables_into().
to_fixed_size_string()
template<int I> static constexpr auto eagine::to_fixed_size_string (const int_constant< I >) static constexpr noexcept
Converts a multi-digit decimal number into fixed_size_string.
Converts a negative decimal number into fixed_size_string.
Copyright © 2015-2022 Matúš Chochlík.
<chochlik -at -gmail.com>
Documentation generated on Wed May 18 2022 by Doxygen (version 1.9.1).