Message bus
EAGine (0.87.0) a C++ wrapper for rendering APIs
Message bus
Classes
class eagine::msgbus::context
Class holding common message bus utility objects.
struct eagine::msgbus::message_info
Structure storing information about a sigle message bus message.
class eagine::msgbus::message_view
Combines message information and a non-owning view to message content.
class eagine::msgbus::stored_message
Combines message information and an owned message content buffer.
class eagine::msgbus::message_storage
Class storing message bus messages.
class eagine::msgbus::direct_connection_state
Common shared state for a direct connection.
class eagine::msgbus::direct_connection_address
Class acting as the "address" of a direct connection.
class eagine::msgbus::direct_connection_info< Base >
Implementation of the connection_info interface for direct connections.
class eagine::msgbus::direct_client_connection
Implementation of client-side direct connection.
class eagine::msgbus::direct_server_connection
Implementation of server-side direct connection.
class eagine::msgbus::direct_acceptor
Implementation of acceptor for direct connections.
class eagine::msgbus::direct_connection_factory
Implementation of connection_factory for direct connections.
struct eagine::msgbus::router_topology_info
Structure holding part of router connection topology information.
struct eagine::msgbus::router_statistics
Structure holding router statistics information.
struct eagine::msgbus::bridge_topology_info
Structure holding part of bridge connection topology information.
struct eagine::msgbus::bridge_statistics
Structure holding bridge statistics information.
struct eagine::msgbus::endpoint_topology_info
Structure holding part of endpoint connection topology information.
struct eagine::msgbus::endpoint_statistics
Structure holding endpoint statistics information.
struct eagine::msgbus::endpoint_info
Message bus endpoint information.
struct eagine::msgbus::connection_statistics
Structure holding message bus connection statistics.
struct eagine::msgbus::message_flow_info
Structure holding message bus data flow information.
class eagine::msgbus::endpoint
Message bus client endpoint that can send and receive messages.
class eagine::msgbus::friend_of_endpoint
Base for classes that need access to enpoint internal functionality.
class eagine::msgbus::loopback_connection
Loopback implementation of connection. Used mainly for testing and development.
class eagine::msgbus::subscriber_base
Base class for message bus subscribers.
class eagine::msgbus::static_subscriber< N >
Template for subscribers with predefined count of handled message types.
class eagine::msgbus::subscriber
Template for subscribers with variable count of handled message types.
class eagine::msgbus::signal< void(Params...) noexcept >
Class that allows connecting and invoking callables with the specified signature.
class eagine::msgbus::signal_binding
Class that keeps a signam binding key and disconnects it when destroyed.
struct eagine::msgbus::acceptor
Interface for message bus connection acceptors.
struct eagine::msgbus::acceptor_user
Interface for classes that can use message bus connection acceptors.
struct eagine::msgbus::connection_factory
Interface for message bus connection and acceptor factories.
struct eagine::msgbus::connection_info
Basic interface for retrieving message bus connection information.
struct eagine::msgbus::connection
Interface for message bus connections.
struct eagine::msgbus::connection_user
Interface for classes that can use message bus connections.
struct eagine::msgbus::message_handler_map< MemFuncConst >
Represents a mapping from a message type id to member function constant.
struct eagine::msgbus::static_message_handler_map< MessageId, MemFuncConst >
Represents a mapping from a message type id to member function constant.
class eagine::msgbus::connection_setup
Class setting up connections based from configuration.
class eagine::msgbus::router_address
Class loading and managing message bus router address(es).
class eagine::msgbus::service_composition< Base >
Helper mixin class for message bus services composed of several parts.
class eagine::msgbus::subscriber_discovery< Base >
Service discovering information about endpoint status and subscriptions.
class eagine::msgbus::shutdown_target< Base >
Service allowing an endpoint to be shut down over the message bus.
class eagine::msgbus::shutdown_invoker< Base >
Service allowing to shut down other endpoints over the message bus.
struct eagine::msgbus::service_interface
Interface for message bus services.
class eagine::msgbus::promise< T >
Message bus promise class.
class eagine::msgbus::future< T >
Message bus future class.
class eagine::msgbus::pending_promises< T >
Class that makes new and tracks existing pending message bus promises.
class eagine::msgbus::network_topology< Base >
Service observing message bus node network topology.
class eagine::msgbus::resource_server< Base >
Service providing access to files and/or blobs over the message bus.
class eagine::msgbus::resource_manipulator< Base >
Service manipulating files over the message bus.
class eagine::msgbus::actor< N, Subscriber >
Base class for message bus actors with fixed number of message handlers.
class eagine::msgbus::host_info_provider< Base >
Service providing basic information about message bus endpoint's host.
class eagine::msgbus::host_info_consumer< Base >
Service consuming basic information about message bus endpoint's host.
class eagine::msgbus::pingable< Base >
Service responding to pings from the pinger counterpart.
class eagine::msgbus::pinger< Base >
Service sending to pings from the pingable counterparts.
class eagine::msgbus::build_info_provider< Base >
Service providing information about endpoint build version.
class eagine::msgbus::build_info_consumer< Base >
Service consuming information about endpoint build version.
class eagine::msgbus::system_info_provider< Base >
Service providing basic information about endpoint's host system.
class eagine::msgbus::system_info_consumer< Base >
Service consuming basic information about endpoint's host system.
class eagine::msgbus::registry
Class combining a local bus router and a set of endpoints.
class eagine::msgbus::sudoku_helper< Base >
Service helping to partially solve sudoku boards sent by sudoku_solver.
class eagine::msgbus::sudoku_solver< Base, Key >
Service solving sudoku boards with the help of helper service on message bus.
class eagine::msgbus::sudoku_fragment_view< S >
Class providing view to a solved fragment in sudoku_tiles.
class eagine::msgbus::sudoku_tiles< S >
class eagine::msgbus::sudoku_tiling< Base >
Service generating a sudoku tiling using helper message bus nodes.
class eagine::msgbus::node_tracker< Base >
Service that consumes bus topology information and provides it via an API.
struct eagine::msgbus::stream_info
Structure holding information about a data stream.
class eagine::msgbus::stream_endpoint< Base >
Base class for stream provider and consumer services.
class eagine::msgbus::stream_provider< Base >
Service providing encoded stream data.
class eagine::msgbus::stream_consumer< Base >
Service consuming encoded stream data.
class eagine::msgbus::stream_relay< Base >
Service relaying stream data between providers and consumers.
class eagine::msgbus::posix_mqueue
Class wrapping a POSIX message queue.
class eagine::msgbus::posix_mqueue_connection_info< Base >
Implementation of the connection_info interface for POSIX queue connection.
class eagine::msgbus::posix_mqueue_connection
Implementation of connection on top of POSIX message queues.
class eagine::msgbus::posix_mqueue_connector
Implementation of connection on top of POSIX message queues.
class eagine::msgbus::posix_mqueue_acceptor
Implementation of acceptor on top of POSIX message queues.
class eagine::msgbus::posix_mqueue_connection_factory
Implementation of connection_factory for POSIX message queue connections.
struct eagine::msgbus::remote_node_changes
Class providing and manipulating information about remote node changes.
struct eagine::msgbus::remote_instance_changes
Class providing and manipulating information about remote instance changes.
struct eagine::msgbus::remote_host_changes
Class providing and manipulating information about remote host changes.
class eagine::msgbus::remote_node_tracker
Class tracking the state of remote message bus nodes.
class eagine::msgbus::remote_host
Class providing information about a remote host of bus nodes.
class eagine::msgbus::remote_host_state
Class manipulating information about a remote host of bus nodes.
class eagine::msgbus::remote_instance
Class providing information about a remote instance running bus nodes.
class eagine::msgbus::remote_instance_state
Class manipulating information about a remote instance running bus nodes.
class eagine::msgbus::remote_node
Class providing information about a remote bus node.
class eagine::msgbus::remote_node_state
Class manipulating information about a remote bus node.
class eagine::msgbus::node_connection
Class providing information about connection between bus nodes.
class eagine::msgbus::node_connection_state
Class manipulating information about connection between bus nodes.
class eagine::msgbus::node_connections
Class providing information about connections from the perspective of a node.
class eagine::msgbus::ability_provider< Base >
Service providing information about message types handled by endpoint.
class eagine::msgbus::ability_tester< Base >
Service consuming information about message types handled by endpoint.
class eagine::msgbus::application_info_provider< Base >
Service providing basic information about endpoint's application.
class eagine::msgbus::application_info_consumer< Base >
Service consuming basic information about endpoint's application.
class eagine::msgbus::compiler_info_provider< Base >
Service providing information about endpoint compiler info.
class eagine::msgbus::compiler_info_consumer< Base >
Service consuming information about endpoint compiler info.
class eagine::msgbus::endpoint_info_provider< Base >
Service providing basic information about message bus endpoint.
class eagine::msgbus::endpoint_info_consumer< Base >
Service consuming basic information about message bus endpoint.
class eagine::msgbus::statistics_consumer< Base >
Service observing message bus node network statistics.
Macros
#define EAGINE_MSG_MAP(CLASS_ID, METHOD_ID, CLASS, METHOD)
Constructs an instance of static message handler map.
Typedefs
using eagine::msgbus::default_serializer_backend = portable_serializer_backend
Alias for default serialization backend for bus messages.
using eagine::msgbus::default_deserializer_backend = portable_deserializer_backend
Alias for default deserialization backend for bus messages.
using eagine::msgbus::message_timestamp = std::chrono::steady_clock::time_point
Alias for message timestamp type.
using eagine::msgbus::message_age = std::chrono::duration< float >
Alias for message age type.
using eagine::msgbus::message_crypto_flags = bitfield< message_crypto_flag >
Alias for message crypto flags bitfield.
using eagine::msgbus::message_sequence_t = std::uint32_t
Alias for message sequence number type.
using eagine::msgbus::verification_bits = bitfield< verification_bit >
Alias for a bus message verification bitfield.
using eagine::msgbus::connection_kinds = bitfield< connection_kind >
Alias for connection kind bitfield.
template<connection_addr_kind Kind>
using eagine::msgbus::connection_addr_kind_tag = std::integral_constant< connection_addr_kind, Kind >
Tag template alias for specifying connection address kind.
template<connection_protocol Proto>
using eagine::msgbus::connection_protocol_tag = std::integral_constant< connection_protocol, Proto >
Tag template alias for specifying connection protocol kind.
using eagine::msgbus::stream_protocol_tag = connection_protocol_tag< connection_protocol::stream >
Tag type for specifying stream connection protocols.
using eagine::msgbus::datagram_protocol_tag = connection_protocol_tag< connection_protocol::datagram >
Tag type for specifying datagram connection protocols.
using eagine::msgbus::ipv4_port = unsigned short int
Alias for IPv4 port number value type.
template<typename Base >
using eagine::msgbus::node_tracker_base = require_services< Base, pinger, system_info_consumer, common_info_consumers, statistics_consumer, network_topology, subscriber_discovery >
Alias for base service composition for the message bus node tracker.
template<typename Base = subscriber>
using eagine::msgbus::common_info_providers = require_services< Base, compiler_info_provider, build_info_provider, host_info_provider, application_info_provider, endpoint_info_provider >
Alias for a common composition of information provider services.
template<typename Base = subscriber>
using eagine::msgbus::common_info_consumers = require_services< Base, compiler_info_consumer, build_info_consumer, host_info_consumer, application_info_consumer, endpoint_info_consumer >
Alias for a common composition of information consumer services.
Enumerations
enum class eagine::power_supply_kind : std::uint8_t { eagine::unknown , eagine::battery , eagine::ac_supply }
System power supply kind.
enum class eagine::msgbus::message_priority : std::uint8_t {
eagine::msgbus::idle , eagine::msgbus::low , eagine::msgbus::normal , eagine::msgbus::high ,
eagine::msgbus::critical
}
Message priority enumeration.
enum class eagine::msgbus::message_crypto_flag : std::uint8_t { eagine::msgbus::asymmetric , eagine::msgbus::signed_header , eagine::msgbus::signed_content }
Message cryptography-related flag bits enumeration.
enum class eagine::msgbus::node_kind : std::uint8_t { eagine::msgbus::unknown , eagine::msgbus::endpoint , eagine::msgbus::bridge , eagine::msgbus::router }
Message bus node kind enumeration.
enum class eagine::msgbus::verification_bit : std::uint8_t {
eagine::msgbus::source_id , eagine::msgbus::source_certificate , eagine::msgbus::source_private_key , eagine::msgbus::message_id ,
eagine::msgbus::message_content
}
Bus message verification bits enumeration,.
enum class eagine::msgbus::connection_kind : std::uint8_t { eagine::msgbus::unknown , eagine::msgbus::in_process , eagine::msgbus::local_interprocess , eagine::msgbus::remote_interprocess }
Message bus connection kind bits enumeration.
enum class eagine::msgbus::connection_addr_kind { eagine::msgbus::none , eagine::msgbus::filepath , eagine::msgbus::ipv4 }
Message bus connection address kind enumeration.
enum class eagine::msgbus::connection_protocol { eagine::msgbus::stream , eagine::msgbus::datagram , eagine::msgbus::message }
Message bus connection protocol.
enum class eagine::msgbus::remote_node_change : std::uint16_t {
eagine::msgbus::kind , eagine::msgbus::instance_id , eagine::msgbus::host_id , eagine::msgbus::host_info ,
eagine::msgbus::build_info , eagine::msgbus::application_info , eagine::msgbus::endpoint_info , eagine::msgbus::methods_added ,
eagine::msgbus::methods_removed , eagine::msgbus::started_responding , eagine::msgbus::stopped_responding , eagine::msgbus::response_rate ,
eagine::msgbus::hardware_config , eagine::msgbus::sensor_values , eagine::msgbus::statistics , eagine::msgbus::connection_info
}
Enumeration of changes tracked about remote message bus nodes.
enum class eagine::msgbus::remote_instance_change : std::uint16_t {
eagine::msgbus::host_id , eagine::msgbus::started_responding , eagine::msgbus::stopped_responding , eagine::msgbus::build_info ,
eagine::msgbus::application_info , eagine::msgbus::statistics
}
Enumeration of changes tracked about remote message bus instances.
enum class eagine::msgbus::remote_host_change : std::uint16_t {
eagine::msgbus::hostname , eagine::msgbus::started_responding , eagine::msgbus::stopped_responding , eagine::msgbus::hardware_config ,
eagine::msgbus::sensor_values
}
Enumeration of changes tracked about remote message bus hosts.
Functions
template<typename T >
auto eagine::msgbus::default_serialize_buffer_size_for (const T &inst) noexcept
Returns count of bytes required for serialization of the specified object.
template<typename T >
auto eagine::msgbus::default_serialize_vector_for (const T &inst) noexcept
Returns a vector for the serialization of the specified object.
template<typename T >
auto eagine::msgbus::default_serialize_buffer_for (const T &inst) noexcept
Returns a suitable buffer for the serialization of the specified object.
template<typename Backend >
auto eagine::msgbus::serialize_message_header (const message_id msg_id, const message_view &msg, Backend &backend) noexcept -> serialization_errors requires(std::is_base_of_v< serializer_backend, Backend >)
Serializes a bus message header with the specified serializer backend.
template<typename Backend >
auto eagine::msgbus::serialize_message (const message_id msg_id, const message_view &msg, Backend &backend) noexcept -> serialization_errors requires(std::is_base_of_v< serializer_backend, Backend >)
Serializes a bus message with the specified serializer backend.
template<typename Backend >
auto eagine::msgbus::deserialize_message_header (identifier &class_id, identifier &method_id, stored_message &msg, Backend &backend) noexcept -> deserialization_errors requires(std::is_base_of_v< deserializer_backend, Backend >)
Deserializes a bus message header with the specified deserializer backend.
template<typename Backend >
auto eagine::msgbus::deserialize_message (identifier &class_id, identifier &method_id, stored_message &msg, Backend &backend) noexcept -> deserialization_errors requires(std::is_base_of_v< deserializer_backend, Backend >)
Deserializes a bus message with the specified deserializer backend.
template<typename Backend >
auto eagine::msgbus::deserialize_message (message_id &msg_id, stored_message &msg, Backend &backend) noexcept -> deserialization_errors requires(std::is_base_of_v< deserializer_backend, Backend >)
Deserializes a bus message with the specified deserializer backend.
auto eagine::msgbus::default_serialize_message_type (const message_id msg_id, memory::block blk) noexcept
Default-serializes the specified message id into a memory block.
auto eagine::msgbus::default_deserialize_message_type (message_id &msg_id, const memory::const_block blk) noexcept
Default-deserializes the specified message id from a memory block.
static constexpr auto eagine::msgbus::is_special_message (const message_id msg_id) noexcept
Indicates if the specified message id denotes a special message bus message.
static constexpr auto eagine::msgbus::broadcast_endpoint_id () noexcept -> identifier_t
Returns the special broadcast message bus endpoint id.
static constexpr auto eagine::msgbus::invalid_endpoint_id () noexcept -> identifier_t
Returns the special invalid message bus endpoint id.
static constexpr auto eagine::msgbus::is_valid_endpoint_id (const identifier_t id) noexcept -> bool
Indicates if the specified endpoint id is valid.
static auto eagine::msgbus::parse_ipv4_addr (const string_view addr_str) noexcept -> std::tuple< std::string, ipv4_port >
Parses a IPv4 hostname:port pair,.
Variables
constexpr const span_size_t eagine::msgbus::min_connection_data_size
The minimum guaranteed block size that can be sent through bus connections.
Detailed Description
Macro Definition Documentation
EAGINE_MSG_MAP
#define EAGINE_MSG_MAP (CLASS_ID, METHOD_ID, CLASS, METHOD)
Constructs an instance of static message handler map.
See also
eagine::msgbus::static_message_handler_map
eagine::msgbus::static_subscriber
eagine::msgbus::subscriber
EAGINE_MSG_TYPE
EAGINE_MEM_FUNC_T
Examples
eagine/msgbus/001_loopback.cpp, eagine/msgbus/002_direct.cpp, eagine/msgbus/006_ping.cpp, eagine/msgbus/006_pong.cpp, eagine/msgbus/009_fib_service.cpp, eagine/msgbus/010_fib_async.cpp, eagine/msgbus/010_fib_futures.cpp, eagine/msgbus/011_fibonacci.cpp, eagine/msgbus/012_fib_threads.cpp, and eagine/msgbus/013_conn_setup.cpp.
Typedef Documentation
common_info_consumers
template<typename Base = subscriber> using eagine::msgbus::common_info_consumers = typedef require_services< Base, compiler_info_consumer, build_info_consumer, host_info_consumer, application_info_consumer, endpoint_info_consumer>
Alias for a common composition of information consumer services.
See also
service_composition
common_info_providers
common_info_providers
template<typename Base = subscriber> using eagine::msgbus::common_info_providers = typedef require_services< Base, compiler_info_provider, build_info_provider, host_info_provider, application_info_provider, endpoint_info_provider>
Alias for a common composition of information provider services.
See also
service_composition
common_info_consumers
connection_protocol_tag
template<connection_protocol Proto> using eagine::msgbus::connection_protocol_tag = typedef std::integral_constant<connection_protocol, Proto>
Tag template alias for specifying connection protocol kind.
See also
stream_protocol_tag
datagram_protocol_tag
datagram_protocol_tag
using eagine::msgbus::datagram_protocol_tag = typedef connection_protocol_tag<connection_protocol::datagram>
Tag type for specifying datagram connection protocols.
See also
stream_protocol_tag
default_deserializer_backend
using eagine::msgbus::default_deserializer_backend = typedef portable_deserializer_backend
Alias for default deserialization backend for bus messages.
See also
default_serializer_backend
default_serializer_backend
using eagine::msgbus::default_serializer_backend = typedef portable_serializer_backend
Alias for default serialization backend for bus messages.
See also
default_deserializer_backend
message_age
using eagine::msgbus::message_age = typedef std::chrono::duration<float>
Alias for message age type.
See also
message_timestamp
Examples
eagine/msgbus/006_file_histogram.cpp.
message_timestamp
using eagine::msgbus::message_timestamp = typedef std::chrono::steady_clock::time_point
Alias for message timestamp type.
See also
message_age
node_tracker_base
template<typename Base > using eagine::msgbus::node_tracker_base = typedef require_services< Base, pinger, system_info_consumer, common_info_consumers, statistics_consumer, network_topology, subscriber_discovery>
Alias for base service composition for the message bus node tracker.
See also
node_tracker
service_composition
stream_protocol_tag
using eagine::msgbus::stream_protocol_tag = typedef connection_protocol_tag<connection_protocol::stream>
Tag type for specifying stream connection protocols.
See also
datagram_protocol_tag
Enumeration Type Documentation
connection_addr_kind
enum eagine::msgbus::connection_addr_kind strong
Message bus connection address kind enumeration.
See also
connection_addr_kind_tag
Enumerator
none
No public address.
filepath
Filesystem path.
ipv4
PIv4 address.
connection_kind
enum eagine::msgbus::connection_kind : std::uint8_t strong
Message bus connection kind bits enumeration.
See also
connection_kinds
Enumerator
unknown
Unknown connection kind.
in_process
In-process connection (cannot be used for inter-process communication).
local_interprocess
Inter-process connection for local communication.
remote_interprocess
Inter-process connection for remote communucation.
connection_protocol
enum eagine::msgbus::connection_protocol strong
Message bus connection protocol.
See also
connection_protocol_tag
Enumerator
stream
Reliable stream protocol.
datagram
Datagram protocol.
message
Message protocol.
message_crypto_flag
enum eagine::msgbus::message_crypto_flag : std::uint8_t strong
Message cryptography-related flag bits enumeration.
See also
message_crypto_flags
Enumerator
asymmetric
Assymetric cipher is used (symmetric otherwise).
signed_header
The message header is signed.
signed_content
The message content is signed.
message_priority
enum eagine::msgbus::message_priority : std::uint8_t strong
Message priority enumeration.
Enumerator
idle
Idle, sent only when no messages with higher priority are enqueued.
low
Low message priority.
normal
Normal, default message priority.
high
High, sent before messages with lower priority.
critical
Critical, sent as soon as possible.
node_kind
enum eagine::msgbus::node_kind : std::uint8_t strong
Message bus node kind enumeration.
Enumerator
unknown
Unknown node kind.
endpoint
Message bus client endpoint.
bridge
Message bus bridge.
router
Message bus router.
power_supply_kind
enum eagine::power_supply_kind : std::uint8_t strong
System power supply kind.
See also
system_info
Enumerator
unknown
Unknown power supply.
battery
Battery.
ac_supply
AC power supply.
remote_host_change
enum eagine::msgbus::remote_host_change : std::uint16_t strong
Enumeration of changes tracked about remote message bus hosts.
See also
remote_host_changes
remote_node_change
Enumerator
hostname
The host name has appeared or changed.
started_responding
Host started responding.
stopped_responding
Host stopped responding.
hardware_config
The hardware configuration information has appeared or changed.
sensor_values
New sensor values have appeared or changed.
remote_instance_change
enum eagine::msgbus::remote_instance_change : std::uint16_t strong
Enumeration of changes tracked about remote message bus instances.
See also
remote_instance_changes
remote_node_change
Enumerator
host_id
The host identifier has appeared or changed.
started_responding
Instance started responding.
stopped_responding
Instance stopped responding.
build_info
The build information has appeared or changed.
application_info
The application information has appeared or changed.
statistics
New statistics have appeared or changed.
remote_node_change
enum eagine::msgbus::remote_node_change : std::uint16_t strong
Enumeration of changes tracked about remote message bus nodes.
See also
remote_node_changes
remote_host_change
Enumerator
kind
The node kind has appeared or changed.
See also
node_kind
instance_id
The endpoint instance id has changed.
host_id
The host identifier has appeared or changed.
host_info
The host information has appeared or changed.
build_info
The build information has appeared or changed.
application_info
The application information has appeared or changed.
endpoint_info
The endpoint information has appeared or changed.
methods_added
New remotly callable methods have been added.
methods_removed
New remotly callable methods have been removed.
started_responding
Node started responding to pings.
stopped_responding
Node stopped responding to pings.
response_rate
Node ping response rate.
hardware_config
The hardware configuration information has appeared or changed.
sensor_values
New sensor values have appeared or changed.
statistics
New statistic values have appeared or changed.
connection_info
The bus connection information has appeared or changed.
verification_bit
enum eagine::msgbus::verification_bit : std::uint8_t strong
Bus message verification bits enumeration,.
See also
verification_bits
Enumerator
source_id
The source has been verified.
source_certificate
The source certificate has been verified.
source_private_key
The source private key has been verified.
message_id
The message type id has been verified.
message_content
The message content has been verified.
Function Documentation
default_deserialize_message_type()
auto eagine::msgbus::default_deserialize_message_type (message_id & msg_id, const memory::const_block blk) inline noexcept
Default-deserializes the specified message id from a memory block.
See also
default_deserializer_backend
default_deserialize
message_id
default_serialize_message_type()
auto eagine::msgbus::default_serialize_message_type (const message_id msg_id, memory::block blk) inline noexcept
Default-serializes the specified message id into a memory block.
See also
default_serializer_backend
default_serialize
message_id
deserialize_message() [1/2]
template<typename Backend > auto eagine::msgbus::deserialize_message (identifier & class_id, identifier & method_id, stored_message & msg, Backend & backend) -> deserialization_errors requires(std::is_base_of_v<deserializer_backend, Backend>) noexcept
Deserializes a bus message with the specified deserializer backend.
See also
deserialize_message_header
serialize_message
default_deserialize
deserialize_message() [2/2]
template<typename Backend > auto eagine::msgbus::deserialize_message (message_id & msg_id, stored_message & msg, Backend & backend) -> deserialization_errors requires(std::is_base_of_v<deserializer_backend, Backend>) noexcept
Deserializes a bus message with the specified deserializer backend.
See also
deserialize_message_header
serialize_message
deserialize_message_header()
template<typename Backend > auto eagine::msgbus::deserialize_message_header (identifier & class_id, identifier & method_id, stored_message & msg, Backend & backend) -> deserialization_errors requires(std::is_base_of_v<deserializer_backend, Backend>) noexcept
Deserializes a bus message header with the specified deserializer backend.
See also
deserialize_message
serialize_message_header
invalid_endpoint_id()
static constexpr auto eagine::msgbus::invalid_endpoint_id () -> identifier_t static constexpr noexcept
Returns the special invalid message bus endpoint id.
See also
is_valid_id
Referenced by eagine::msgbus::stream_endpoint< Base >::reset_stream_relay().
is_valid_endpoint_id()
static constexpr auto eagine::msgbus::is_valid_endpoint_id (const identifier_t id) -> bool static constexpr noexcept
Indicates if the specified endpoint id is valid.
See also
invalid_endpoint_id
Referenced by eagine::msgbus::stream_endpoint< Base >::has_stream_relay(), eagine::msgbus::endpoint::is_valid_id(), and eagine::msgbus::stream_endpoint< Base >::set_stream_relay().
serialize_message()
template<typename Backend > auto eagine::msgbus::serialize_message (const message_id msg_id, const message_view & msg, Backend & backend) -> serialization_errors requires(std::is_base_of_v<serializer_backend, Backend>) noexcept
Serializes a bus message with the specified serializer backend.
See also
serialize_message_header
deserialize_message
default_serialize
serialize_message_header()
template<typename Backend > auto eagine::msgbus::serialize_message_header (const message_id msg_id, const message_view & msg, Backend & backend) -> serialization_errors requires(std::is_base_of_v<serializer_backend, Backend>) noexcept
Serializes a bus message header with the specified serializer backend.
See also
serialize_message
deserialize_message_header
Copyright © 2015-2022 Mat Chochlk.
<chochlik -at -gmail.com>
Documentation generated on Wed May 18 2022 by Doxygen (version 1.9.1).