eagine Namespace Reference
EAGine (0.87.0) a C++ wrapper for rendering APIs
eagine Namespace Reference
Common code is placed in this namespace.
Namespaces
app
Application development framework code is placed in this namespace.
ecs
Entity-component system code is placed in this namespace.
eglplus
EGL API wrapper code is placed in this namespace.
math
Math-related code is placed in this namespace.
msgbus
Message bus code is placed in this namespace.
oalplus
OpenAL API wrapper code is placed in this namespace.
oglplus
OpenGL API wrapper code is placed in this namespace.
shapes
Shape generator and loader code is placed in this namespace.
sslplus
C++ wrapper core for the OpenSSL API is placed in this namespace.
valtree
Value-tree code is placed in this namespace.
Classes
class compiler_info
Class providing compiler and architecture information.
struct file_contents_intf
Interface for file content getter implementations.
class file_contents
Class providing access to the contents of a file.
class structured_file_content
Class loading a baked structured data from a file.
struct main_ctx_options
Structure storing customization options for main context.
class main_ctx
Class for a singleton object providing useful information and services.
class user_info
Class providing user-related information.
struct valid_if_not_empty_policy
Policy class for containers valid if their empty() member function return false.
struct anything
Type that can by constructed from single argument of any other type.
struct ok_traits
Traits used for customization of class ok for the specified Outcome.
class ok
Value typically wrapping function call result and success indicator.
struct type_identity
Template type used mostly for function type-tag dispatching.
struct get_type
Implementation detail of the type_t template.
struct valid_if_nonneg_policy
Policy class for values valid when they are non-negative.
class valid_if_or_fallback
Helper class storing both conditionally valid value and fallback.
class basic_c_str
Helper template for getting zero-terminated strings from string spans.
class on_scope_exit
Class executing a specified action on scope exit.
class func_on_scope_exit
Class storing a callable object and an instance of on_scope_exit.
struct application_config_value_loader
Internal interface for reloadable configuration values.
class application_config
Class for reading application configuration.
class application_config_value
Class wrapping values that can be loaded from application_config.
class application_config_value< T, As, false >
Class wrapping values that can be loaded from application_config.
class application_config_value< T, As, true >
Class wrapping values that can be reloaded from application_config.
class basic_string_span
Specialization of memory::basic_span for character string containers.
struct basic_view_less
Comparator template for string span - string span comparisons.
struct basic_str_view_less
Comparator template for standard string - string span comparisons.
struct valid_flag_policy
Policy for optionally valid values, indicated by a boolean flag.
class basic_valid_if
Basic template for conditionally-valid values.
struct nothing_t
Class representing "none" / "nothing" values.
struct selector
Template used to construct tag-types used mostly in tag-dispatching.
class base64dump
Class for encoding byte blocks into base64 format.
struct log_stream_info
Structure used to supply initial log stream information to a logger.
struct logger_backend
Interface for logging backend implementations.
struct console_options
Structure holding console customization options.
class identifier_encoding
Helper class implementing identifier encoding functionality.
struct default_identifier_char_set
Characted encoding table for identifier.
class identifier_name
Helper template for unpacking of identifier into a character string.
class basic_identifier
Basic template for limited length, packed string identifiers.
struct root_logger_options
Structure holding root logger customization options.
class basic_callable_ref
Declaration of class template storing a reference to a callable object.
struct main_ctx_setters
Interface for classes providing access to main context singletons.
struct main_ctx_getters
Interface for classes providing access to main context singletons.
class main_ctx_object_parent_info
Helper class used to initialize main context objects.
class program_arg
Class representing a single main function (command-line) argument.
class program_arg_iterator
Iterator type over program_arg instances.
class program_args
Class wrapping the main function arguments, providing a convenient API.
class basic_logger
Basic template for logger objects.
class named_logging_object
Basic template for logging objects.
class logger
Standalone logger object type.
class interface
Base template for abstract interfaces, implements common functionality.
class abstract
Base template for polymorphic classes, implements common functionality.
class main_ctx_log_backend_getter
Helper class used in the implementation of logging in main context object.
class main_ctx_object
Base class for main context objects.
struct indeterminate_t
Type of the indeterminate constant assignable to tribool.
class weakbool
Weak tri-state boolean value.
class tribool
Tri-state boolean value.
struct valid_if_in_list_policy
Policy for values valid if contained in object of Range type.
class protected_member
Class holding a single tagged data member.
class basic_callable_ref< RV(P...) noexcept(NE), NE >
Implementation of class template storing a reference to a callable object.
struct console_backend
Interface for console backend implementations.
class biteset
Sequence of unsigned integer values with specified number bits.
class biteset_value_proxy
Proxy class that can be used to access elements in a biteset.
class biteset_value_proxy_base
Base class for biteset value proxy.
class biteset_value_proxy< const biteset< N, B, T > >
Specialization of biteset proxy for const biteset values.
class biteset_value_proxy< biteset< N, B, T > >
Specialization of biteset proxy for mutable biteset values.
class biteset_iterator< biteset< N, B, T > >
Iterator type for biteset.
class fixed_size_string
String with maximum fixed-size internal storage.
struct static_message_id
Template with two identifier parameters representing class/method pair.
struct message_id
Class storing two identifier values representing class/method pair.
struct does_have_entry_adapter
Helper class used in implementation of has_entry_adapter_t.
class activity_progress
Class tracking the progress of a long-running activity.
class build_info
Class providing basic system information.
class data_compressor
Class implementing data compression and decompresson.
class root_logger
Class typically used as the per-application single root of logger hierarchy.
class system_info
Class providing basic system information.
class process_watchdog
Class implementing process watchdog functionality.
class default_progress_tracker_backend
Default implementation of activity progress backend implementations.
class console_entry
Class representing a single log entry / message.
class tagged_quantity
Value of type T with a specified unit or tag type U.
class log_entry
Class representing a single log entry / message.
struct no_log_entry
Do-nothing variant of log_entry with compatible API.
class stream_log_entry
Log entry helper containing an istream for creating the log message.
struct always_valid_policy
Policy for always valid values.
struct valid_if_le_size_ge0_policy
Policy for values valid if >= 0 and <= container.size().
struct valid_if_lt_size_ge0_policy
Policy for values valid if >= 0 and < container.size().
struct member_function_constant
Declaration of compile-time member function pointer wrappers.
struct member_function_constant< RV(C::*)(P...), Ptr >
Implementation of compile-time member function pointer wrappers.
class bitfield
Class for manipulating and testing a group of enumeration-based bits.
class byteset
Class storing a sequence of bytes converting them to and from unsigned integer.
class double_buffer
Class holding two instances of type T and allows to switch them.
class hexdump
Class for encoding byte blocks into hexdump-like format.
struct variable_substitution_options
Options for string variable substitution customization.
class string_variable_map
Class storing a map of variable names to values, doing string substitution.
struct progress_observer
Interface for classes observing activity progress.
struct progress_tracker_backend
Interface for activity progress backend implementations.
struct valid_if_ge0_le1_policy
Policy for values valid if between zero and one.
struct valid_if_positive_policy
Policy class for values valid when they are positive.
class basic_string_path
Basic class storing paths made of string elements.
class optional_reference_wrapper
Optional reference to an instance of type T.
class time_measure
Class that measures elapsed time since instance construction.
class timeout
Class representing a timeout since construction or reset.
class referencing_timeout
Class representing a timeout since construction or reset.
class resetting_timeout
Specialization of timeout that resets when tested for expiration.
struct valid_if_btwn_policy
Policy for values valid if between Min and Max.
struct valid_if_lt_policy
Policy class for values valid if less than Cmp.
struct valid_if_nz_policy
Policy class for values valid if not equal to zero.
struct valid_if_size_gt_policy
Policy class for containers valid if their size is larger than specified number.
class animated_value
Class representing a value animated between two points, with easing.
class signal_switch
Installs handlers for interrupt signals and flips switch on receipt.
class bindump
Class for encoding byte blocks into binary format.
struct mp_plus
Implementation of addition on types representing numbers.
struct mp_minus
Implementation of subtraction on types representing numbers.
struct mp_negate
Implementation of negation on types representing numbers.
class executable_module
Wrapper for a handle to dynamically linkable executable module.
class shared_executable_module
Reference counting handle to dynamically linkable executable module.
class embedded_resource
Class providing access to a const resource block embedded into the executable.
class interleaved_call
Callable class that interleaves calls to a function with a separator function.
class istream_data_source
Deserialization data source backed by an input stream.
class ostream_data_sink
Serialization data sink backed by an output stream.
class block_data_sink
Serialization data sink backed by a pre-allocated memory block.
class block_data_source
Deserialization data source backed by a pre-allocated memory block.
struct deserializer_backend
Interface for deserialization read backends.
class common_deserializer_backend
CRTP mixin implementing the common parts of deserializer backends.
struct serializer_backend
Interface for serialization write backends.
class common_serializer_backend
CRTP mixin implementing the common parts of serializer backends.
class serializer_backend_id
Base class partially implementing serializer and deserialized backends.
class packed_block_data_sink
Packing serialization data sink backed by a pre-allocated memory block.
class packed_block_data_source
Unpacking deserialization data source backed by a pre-allocated memory block.
struct deserializer_data_source
Abstract base class for deserialization data sources.
class string_serializer_backend
Cross-platform implementation of serializer backend using ASCII-only strings.
class string_deserializer_backend
Cross-platform implementation of deserializer backend using ASCII-only strings.
struct serializer_data_sink
Abstract base class for serialization data sinks.
struct valid_if_indicated_policy
Policy for values valid when non-boolean Indicator has Value.
class portable_serializer_backend
Cross-platform implementation serializer backend.
class portable_deserializer_backend
Cross-platform implementation of deserializer backend.
class format_string_and_list
Helper class used in implementation of string variable substitution.
class url
Class parsing and providing access to parts of an URL.
class value_with_history_storage
Base storage class for values and variables with history.
class value_with_history
Class for read-only values with history.
class variable_with_history
Class for mutable variables with history.
struct mp_list
Compile-time type list template.
struct mp_is_empty
Implements the is_empty operation on compile-time type lists.
struct mp_contains
Implements the contains operation on compile-time type lists.
struct mp_union_add
Implements the union operation on compile-time type lists.
struct never_valid_policy
Policy for never-valid values.
class basic_wrapping_container
Template used in implementation of containers with wrapped elements.
class basic_iterable_type
Template used in implementation of some iterators.
class basic_selfref_iterator
Iterator referencing the wrapped iterable type.
struct selfref_iterator
Default instantiation of basic_selfref_iterator.
class basic_transforming_iterator
Iterator transforming the referenced elements.
struct transforming_iterator
Default instantiation of basic_transforming_iterator.
class basic_noexcept_casting_iterator
Iterator type-casting the referenced elements.
struct noexcept_casting_iterator
Default instantiation of basic_noexcept_casting_iterator.
class reverse
Adapter reversing the iteration of elements in a Range.
class some_true
Class storing initially false value and logically or-ing other values.
class message_bus
Class providing access to basic message bus functionality.
class static_enum_map
Class mapping from an enumerator of an instantiation of a template.
struct valid_if_ge0_lt1_policy
Policy for values valid if greate or equal to zero, less than one.
struct valid_if_ne_policy
Policy class for values valid if not equal to Cmp.
class count_t
Class counting invocation of its call operator.
struct instead_of
struct valid_if_lt_size_policy
Policy class for values valid if less than container.size().
struct valid_if_within_limits_policy
Policy class for values valid if they are withing limits of other type.
Typedefs
template<typename T >
using valid_if_not_empty = valid_if< T, valid_if_not_empty_policy< std::remove_reference_t< T > >>
Specialization of valid_if, for values valid if not empty.
template<bool B>
using bool_constant = std::integral_constant< bool, B >
Alias for boolean constant type.
template<int I>
using int_constant = std::integral_constant< int, I >
Alias for signed int constant type.
template<unsigned U>
using unsigned_constant = std::integral_constant< unsigned, U >
Alias for unsigned int constant type.
template<std::size_t S>
using size_constant = std::integral_constant< std::size_t, S >
Alias for size_t constant type.
template<identifier_t Id>
using id_constant = std::integral_constant< identifier_t, Id >
Alias for identifier_t constant type.
template<typename T , typename F = void>
using type_t = typename get_type< T, F >::type
Template returning nested alias type of type T or void.
using byte = unsigned char
Byte type alias.
using std_align_t = std::size_t
Alignment type used by std.
using std_size_t = std::size_t
Size type used by std.
using span_size_t = std::ptrdiff_t
Signed span size type used by eagine.
using valid_span_size = valid_if_nonnegative< span_size_t >
Valid size type.
template<typename T >
using valid_if_nonnegative = valid_if< T, valid_if_nonneg_policy< std::remove_reference_t< T > >>
Specialization of valid_if, for values valid if non-negative.
template<typename T >
using extracted_type_t = std::remove_cv_t< typename extract_traits< std::remove_cv_t< std::remove_reference_t< T > >>::value_type >
Returns the value type of an extractable.
using identifier_t = std::uint64_t
The underlying integer type for eagine::identifier.
using process_instance_id_t = std::uint32_t
Unique process identifier type (does not necessarily match to OS PID).
using host_id_t = std::uint32_t
Unique host identifier type.
using long_identifier_t = __uint128_t
The underlying integer type for eagine::long_identifier.
template<typename T , typename Policy , typename DoLog = typename Policy::do_log>
using valid_if = basic_valid_if< T, Policy, DoLog >
Primary template for conditionally valid values.
template<typename T >
using optionally_valid = valid_if< T, valid_flag_policy >
Specialization of valid_if with flag indicating validity.
template<typename T , typename As = std::add_const_t<T>&>
using application_reconfig_value = application_config_value< T, As, true >
Class wrapping values that can be reloaded from application_config.
using string_span = basic_string_span< char >
Alias for mutable string spans.
using string_view = basic_string_span< const char >
Alias for const string views.
using str_view_less = basic_str_view_less< std::string, string_view >
Comparator template for standard string - string_view comparisons.
using default_selector_t = selector< 0U >
Type alias for the default overload selector type.
using construct_from_t = selector< 0xFU >
Type alias for the construct-from tag-dispatch selector.
using immediate_function_t = selector< 0x1FU >
Type alias for immediate function selector.
using identifier = basic_identifier< 10, 6, default_identifier_char_set, identifier_t >
Default identifier type used throughout the project.
using long_identifier = basic_identifier< 20, 6, default_identifier_char_set, long_identifier_t >
Long identifier type used throughout the project.
template<typename Sig >
using callable_ref = basic_callable_ref< Sig, is_noexcept_function_v< Sig > >
Alias for callable object references.
using main_ctx_parent = const main_ctx_object_parent_info &
Alias for main_ctx_object_parent_info parameter type.
template<typename T , typename Range >
using valid_if_in_list = valid_if< T, valid_if_in_list_policy< std::remove_reference_t< T >, Range > >
Specialization of valid_if, for values valid in Range.
template<typename std::size_t B>
using biteset_cell_type = std::conditional_t<(B<=8), std::uint_least8_t, std::conditional_t<(B<=16), std::uint_least16_t, std::conditional_t<(B<=32), std::uint_least32_t, std::conditional_t<(B<=64), std::uint_least64_t, void > >> >
Selects the appropriate type for biteset element representation.
template<typename T >
using has_entry_adapter_t = typename does_have_entry_adapter< T >::type
Trait indicating if there is a log/console entry adapter for type T.
using logger_instance_id = std::uintptr_t
Logger object instance id type.
using console_entry_id_t = std::uintptr_t
Console entry instance id type.
using activity_progress_id_t = std::uintptr_t
Activity progress tracker instance id type.
template<log_event_severity severity>
using log_event_severity_constant = std::integral_constant< log_event_severity, severity >
Type alias for log event severity constants.
using min_log_severity_t = log_event_severity_constant< log_event_severity::EAGINE_MIN_LOG_SEVERITY >
The minimal log severity constant.
template<log_event_severity severity>
using is_log_level_enabled_t = bool_constant<(severity >=min_log_severity_t::value)>
Compile-time trait indicating if the specified log severity is enabled.
template<typename T >
using always_valid = valid_if< T, always_valid_policy >
Specialization of valid_if, for always valid values.
template<typename C , typename T >
using valid_if_le_size_ge0 = in_class_valid_if< T, C, valid_if_le_size_ge0_policy< T, C > >
Specialization of valid_if, for values valid if >= 0 and <= container.size().
template<typename C , typename T >
using valid_if_lt_size_ge0 = in_class_valid_if< T, C, valid_if_lt_size_ge0_policy< T, C > >
Specialization of valid_if, for values valid if >= 0 and < container.size().
template<typename T >
using seconds_t = tagged_quantity< T, units::second >
Alias for type storing duration values in seconds.
template<typename T >
using radians_t = tagged_quantity< T, units::radian >
Alias for type storing angle values in radians.
template<typename T >
using degrees_t = tagged_quantity< T, units::degree >
Alias for type storing angle values in degrees.
template<typename T >
using kelvins_t = tagged_quantity< T, units::kelvin >
Alias for type storing temperature values in kelvins.
template<typename T >
using valid_if_between_0_1 = valid_if< T, valid_if_ge0_le1_policy< std::remove_reference_t< T > >>
Specialization of valid_if, for values valid if 0 <= value <= 1.
template<typename T >
using valid_if_positive = valid_if< T, valid_if_positive_policy< std::remove_reference_t< T > >>
Specialization of valid_if, for values valid if positive.
template<typename T , typename C , C Min, C Max>
using valid_if_between_c = valid_if< T, valid_if_btwn_policy< std::remove_reference_t< T >, C, Min, Max > >
Specialization of valid_if, for values valid if between Min and Max.
template<typename T , T Min, T Max>
using valid_if_between = valid_if_between_c< T, T, Min, Max >
Specialization of valid_if, for values valid if between Min and Max.
template<typename T , T Cmp>
using valid_if_less_than = valid_if< T, valid_if_lt_policy< std::remove_reference_t< T >, Cmp > >
Specialization of valid_if, for values valid if less than Cmp.
template<typename T >
using valid_if_not_zero = valid_if< T, valid_if_nz_policy< std::remove_reference_t< T > >>
Specialization of valid_if, for values valid if not equal to zero.
template<typename T >
using nonzero_t = valid_if_not_zero< T >
Alias for valid_if_not_zero.
template<typename C , typename T >
using valid_if_size_gt = in_class_valid_if< C, T, valid_if_size_gt_policy< C, T > >
Specialization of valid_if, for values valid if they contain more than n items.
template<typename T1 , typename T2 >
using mp_plus_t = typename mp_plus< T1, T2 >::type
Addition operation on types representing numbers.
template<typename T1 , typename T2 >
using mp_minus_t = typename mp_minus< T1, T2 >::type
Subtraction operation on types representing numbers.
template<typename T1 >
using mp_negate_t = typename mp_negate< T1 >::type
Unary negation operation on types representing numbers.
using serialization_errors = bitfield< serialization_error_code >
Alias for serialization error bitfield.
using deserialization_errors = bitfield< deserialization_error_code >
Alias for deserialization error bitfield.
template<typename T >
using serialization_result = valid_if_indicated< T, serialization_errors, bool, false >
Alias for result type of serialization operations.
template<typename T >
using deserialization_result = valid_if_indicated< T, deserialization_errors, bool, false >
Alias for result type of deserialization operations.
template<typename T , typename Indicator , typename Comparable = bool, Comparable Value = true>
using valid_if_indicated = valid_if< T, valid_if_indicated_policy< Indicator, Comparable, Value > >
Specialization of valid_if, for values with non-boolean indicator.
template<typename TL , typename T >
using mp_contains_t = typename mp_contains< TL, T >::type
Trait indicating whether a type list contains a specified type.
template<typename TL1 , typename TL2 >
using mp_union = mp_union_add< TL1, TL2, mp_list<> >
Implements the union operation on compile-time type lists.
template<typename TL1 , typename TL2 >
using mp_union_t = typename mp_union< TL1, TL2 >::type
Trait returning the union of types in two type lists.
template<typename T >
using never_valid = valid_if< T, never_valid_policy >
Specialization of valid_if, for never-valid values.
using work_done = some_true
Type alias used as return value indicating that some work was done.
template<typename T >
using valid_if_ge0_lt1 = valid_if< T, valid_if_ge0_lt1_policy< std::remove_reference_t< T > >>
Specialization of valid_if, for values valid if 0 <= value < 1.
template<typename T , T Cmp>
using valid_if_not = valid_if< T, valid_if_ne_policy< std::remove_reference_t< T >, Cmp > >
Specialization of valid_if, for values valid if not equal to Cmp.
template<typename Src , typename Dst >
using instead_of_t = typename instead_of< Src, Dst >::type
template<typename C , typename T >
using valid_if_lt_size = in_class_valid_if< T, C, valid_if_lt_size_policy< T, C > >
Policy class for values valid if less than container size.
template<typename Dst , typename Src >
using valid_if_within_limits = valid_if< Src, valid_if_within_limits_policy< std::remove_reference_t< Dst >, std::remove_reference_t< Src > >>
Specialization of valid_if, for values valid if within limits of Dst type.
Enumerations
enum class log_event_severity {
backtrace , trace , debug , stat ,
info , warning , error , fatal
}
Log event severity enumeration.
enum class data_compression_level { none , lowest , normal , highest }
Data compression level enumeration.
enum class console_entry_kind { stat , info , warning , error }
Console entry kind enumeration.
enum class power_supply_kind : std::uint8_t { unknown , battery , ac_supply }
System power supply kind.
enum class memory_access_rate {
minimal , low , medium , high ,
very_high
}
Enumeration indicating (estimated) memory access rate.
enum class serialization_error_code : std::uint8_t {
not_supported , too_much_data , incomplete_write , data_sink_error ,
backend_error
}
Serialization error code bits enumeration.
enum class deserialization_error_code : std::uint16_t {
not_supported , not_enough_data , unexpected_data , incomplete_read ,
missing_element , excess_element , missing_member , excess_member ,
invalid_format , data_source_error , backend_error
}
Deserialization error code bits enumeration.
Functions
static auto get_environment_variable (const string_view variable_name) noexcept -> optionally_valid< string_view >
Returns the value in the specified environment variable.
static constexpr auto running_on_valgrind () noexcept -> tribool
Indicates if the current process runs on top of valgrind.
auto config_git_branch () noexcept -> valid_if_not_empty< string_view >
Returns the name of the git branch from which the executable is built.
auto config_git_hash_id () noexcept -> valid_if_not_empty< string_view >
Returns the hash of the commit from which the executable is built.
auto config_git_date () noexcept -> valid_if_not_empty< string_view >
Returns the date of the commit from which the executable is built.
auto config_git_describe () noexcept -> valid_if_not_empty< string_view >
Returns the description of the commit from which the executable is built.
auto config_git_version () noexcept -> valid_if_not_empty< string_view >
Returns the version number as string.
auto config_git_version_major () noexcept -> valid_if_nonnegative< int >
Returns major version number.
auto config_git_version_minor () noexcept -> valid_if_nonnegative< int >
Returns minor version number.
auto config_git_version_patch () noexcept -> valid_if_nonnegative< int >
Returns patch version number.
auto config_git_version_commit () noexcept -> valid_if_nonnegative< int >
Returns commit version number.
auto config_git_version_tuple () noexcept -> std::tuple< int, int, int, int >
Returns the complete version number as a tuple (major, minor, patch, commit).
template<typename T >
static constexpr auto extract (T *ptr) noexcept -> T &
Checks ptr and dereferences it.
template<typename T >
static constexpr auto extract (std::shared_ptr< T > &ptr) noexcept -> auto &
Checks ptr and dereferences it.
template<typename T >
static constexpr auto extract (const std::shared_ptr< T > &ptr) noexcept -> auto &
Checks ptr and dereferences it.
template<typename T , typename D >
static constexpr auto extract (std::unique_ptr< T, D > &ptr) noexcept -> T &
Checks ptr and dereferences it.
template<typename T , typename D >
static constexpr auto extract (const std::unique_ptr< T, D > &ptr) noexcept -> const T &
Checks ptr and dereferences it.
template<typename T >
static constexpr auto extract (std::optional< T > &opt) noexcept -> auto &
Checks ptr and dereferences it.
template<typename T >
static constexpr auto extract (const std::optional< T > &opt) noexcept -> auto &
Checks ptr and dereferences it.
template<typename T >
static constexpr auto make_identity (const T &) noexcept -> type_identity< T >
Makes type_identity for type T of the argument.
template<typename T , typename = std::enable_if_t<std::is_integral_v<T>>>
static constexpr auto std_align (const T v) noexcept
Converts argument to std alignment type.
template<typename T , typename = std::enable_if_t<std::is_integral_v<T>>>
static constexpr auto std_size (const T v) noexcept
Converts argument to std size type.
template<typename T , typename = std::enable_if_t<std::is_integral_v<T>>>
static constexpr auto span_size (const T v) noexcept
Converts argument to span size type.
template<typename T >
static constexpr auto span_align_of (const type_identity< T >={}) noexcept
Returns the byte alignment of type T as span_size_t.
template<typename T >
static constexpr auto span_size_of (const type_identity< T >={}) noexcept
Returns the byte size of type T as span_size_t.
template<typename T , typename S >
static constexpr auto span_size_of (const S n, const type_identity< T >={}) noexcept
Returns the total byte size of n elements of type T as span_size_t.
template<typename Dst , typename Src >
static constexpr auto is_within_limits (const Src value) noexcept
Indicates if value fits into the specified Dst type.
template<typename Dst , typename Src >
static constexpr auto limit_cast (Src value) noexcept -> Dst requires(std::is_convertible_v< Src, Dst >)
Casts value to Dst type if the value fits in that type.
template<typename Src >
static constexpr auto signedness_cast (Src value) noexcept
Casts value to a type with the opposite signedness.
template<typename Dst , typename Src >
static constexpr auto convert_if_fits (Src value) noexcept -> optionally_valid< Dst > requires(std::is_convertible_v< Src, Dst >)
Optionally converts value to Dst type if the value fits in that type.
template<typename T , typename P , typename L >
static constexpr auto extract (const basic_valid_if< T, P, L > &opt) noexcept -> const T &
Overload of extract for conditionally valid values.
template<typename T , typename P , typename L >
static constexpr auto extract (basic_valid_if< T, P, L > &opt) noexcept -> T &
Overload of extract for conditionally valid values.
template<typename T , typename P , typename L >
static constexpr auto extract (basic_valid_if< T, P, L > &&opt) noexcept -> T &&
Overload of extract for conditionally valid values.
template<typename F , typename T , typename P , typename L >
static auto either_or (basic_valid_if< T, P, L > vi, F f) noexcept(noexcept(basic_valid_if< T, P, L >(std::declval< basic_valid_if< T, P, L > && >())) &&noexcept(F(std::declval< F && >()))) -> valid_if_or_fallback< F, T, P, L >
Constructor function for valid_if_or_fallback.
EAGINE_LIB_FUNC auto byte_to_identifier (const byte b) noexcept -> identifier
Creates an identifier representing a byte value as a hex string.
EAGINE_LIB_FUNC auto dec_to_identifier (const int i) noexcept -> identifier
Creates an identifier representing an integer value as a decimal string.
template<typename C , typename P , typename S >
static constexpr auto c_str (const memory::basic_span< C, P, S > s) -> basic_c_str< C, P, S > requires(std::is_convertible_v< memory::basic_span< C, P, S >, basic_string_span< C, P, S >>)
Functions that construct a basic_c_str from a basic_string_span.
template<typename Func >
static auto finally (Func func) noexcept -> func_on_scope_exit< Func >
Function constructing on-scope-exit actions.
template<typename C , typename P , typename S >
static constexpr auto std_view (const memory::basic_span< C, P, S > spn) noexcept -> std::basic_string_view< std::remove_const_t< C >>
Converts a basic_span of characters to string_span.
template<typename C , typename P , typename S >
static constexpr auto to_string (const memory::basic_span< C, P, S > spn) -> std::basic_string< std::remove_const_t< C >>
Converts a basic_span of characters to standard string.
template<typename C , typename T , typename A , typename P , typename S >
static constexpr auto assign_to (std::basic_string< C, T, A > &str, const memory::basic_span< const C, P, S > spn) -> auto &
Assigns the contents of a span of characters to a standard string.
template<typename C , typename T , typename A , typename P , typename S >
static constexpr auto append_to (std::basic_string< C, T, A > &str, const memory::basic_span< const C, P, S > spn) -> auto &
Appends the contents of a span of characters to a standard string.
template<typename T , typename Po1 , typename Po2 , typename L1 , typename L2 >
static constexpr auto operator== (const basic_valid_if< T, Po1, L1 > &v1, const basic_valid_if< T, Po2, L2 > &v2) noexcept -> tribool
Equality comparison of two conditionally valid values.
template<typename T , typename Po1 , typename Po2 , typename L1 , typename L2 >
static constexpr auto operator!= (const basic_valid_if< T, Po1, L1 > &v1, const basic_valid_if< T, Po2, L2 > &v2) noexcept -> tribool
Non-equality comparison of two conditionally valid values.
template<typename T , typename Po1 , typename Po2 , typename L1 , typename L2 >
static constexpr auto operator< (const basic_valid_if< T, Po1, L1 > &v1, const basic_valid_if< T, Po2, L2 > &v2) noexcept -> tribool
Less-than comparison of two conditionally valid values.
template<typename T , typename Po1 , typename Po2 , typename L1 , typename L2 >
static constexpr auto operator> (const basic_valid_if< T, Po1, L1 > &v1, const basic_valid_if< T, Po2, L2 > &v2) noexcept -> tribool
Greater-than comparison of two conditionally valid values.
template<typename T , typename Po1 , typename Po2 , typename L1 , typename L2 >
static constexpr auto operator<= (const basic_valid_if< T, Po1, L1 > &v1, const basic_valid_if< T, Po2, L2 > &v2) noexcept -> tribool
Less-equal comparison of two conditionally valid values.
template<typename T , typename Po1 , typename Po2 , typename L1 , typename L2 >
static constexpr auto operator>= (const basic_valid_if< T, Po1, L1 > &v1, const basic_valid_if< T, Po2, L2 > &v2) noexcept -> tribool
Greater-equal comparison of two conditionally valid values.
auto config_os_name () noexcept -> valid_if_not_empty< string_view >
Returns the name of the OS on which the executable is built.
auto config_os_code_name () noexcept -> valid_if_not_empty< string_view >
Returns the code-name of the OS on which the executable is built.
template<std::size_t M>
static auto operator<< (std::ostream &out, const identifier_name< M > &n) -> std::ostream &
Operator for writing identifier_name into output streams.
auto register_progress_observer (main_ctx_getters &ctx, progress_observer &observer) noexcept -> bool
Registers the activity progress observer.
void unregister_progress_observer (main_ctx_getters &ctx, progress_observer &observer) noexcept
Un-registers the activity progress observer.
void set_progress_update_callback (main_ctx_getters &ctx, const callable_ref< bool() noexcept > &callback, const std::chrono::milliseconds min_interval) noexcept
Assigns a progress update callback function.
void reset_progress_update_callback (main_ctx_getters &ctx) noexcept
Resets the progress update callback function.
template<typename T >
auto from_string (const string_view src) noexcept
Converts the string representation in src to a value of type T.
template<typename T , identifier_t V>
auto from_string (const string_view src, const selector< V > sel) noexcept
Converts the string representation in src to a value of type T.
constexpr auto operator&& (const tribool a, const tribool b) noexcept
Tri-state boolean and operator.
constexpr auto operator|| (const tribool a, const tribool b) noexcept
Tri-state boolean or operator.
template<typename T >
static auto type_name (const T &) noexcept -> std::string
Returns the demangled name for type T.
template<typename T >
static auto type_name () noexcept -> std::string
Returns the demangled name for type T.
template<typename RV , typename C , typename... P, bool NE, RV(C::*)(P...) noexcept Ptr(NE) >
static constexpr auto make_callable_ref (C *obj, member_function_constant< RV(C::*)(P...) noexcept(NE), Ptr > mfc) noexcept -> callable_ref< RV(P...) noexcept(NE)>
Function constructing instances of callable_ref wrapping member functions.
template<span_size_t N>
static constexpr auto make_fixed_size_string (const char(&str)[N]) noexcept
Creates a fixed_size_string from a C-string literal.
template<span_size_t N1, span_size_t N2>
static constexpr auto operator+ (const fixed_size_string< N1 > &s1, const fixed_size_string< N2 > &s2) noexcept
Concatenation operator for fixed_size_string.
template<int I>
static constexpr auto to_fixed_size_string (const int_constant< I >) noexcept requires((I >=0) &&(I< 10))
Converts a single-digit decimal number into fixed_size_string.
template<int I>
static constexpr auto to_fixed_size_string (const int_constant< I >) noexcept requires(I > 9)
Converts a multi-digit decimal number into fixed_size_string.
template<identifier_t ClassId, identifier_t MethodId>
auto operator== (const message_id l, const static_message_id< ClassId, MethodId > r) noexcept
Equality comparison between message_id and static_message_id.
template<typename H , typename I >
auto integer_hash (const I x, const type_identity< H > hid={}, const type_identity< I > iid={}) -> H
Creates a hash value with type H from an integer value of type I.
EAGINE_LIB_FUNC auto random_identifier () -> identifier
Creates an random identifier using a default random engine.
static constexpr auto is_log_level_enabled (const log_event_severity severity) noexcept -> bool
Function indicating if the specified log severity is enabled.
auto substitute_variable_into (std::string &dst, string_view src, const string_view name, const string_view value, const variable_substitution_options={}) noexcept -> std::string &
Substitutes variable value from src into dst.
auto substitute_variables_into (std::string &dst, string_view src, const callable_ref< optionally_valid< string_view >(const string_view) noexcept > &translate, const variable_substitution_options={}) noexcept -> std::string &
Substitutes variable values by using translate, from src into dst.
auto substitute_variables (const string_view src, const callable_ref< optionally_valid< string_view >(const string_view) noexcept > &translate, const variable_substitution_options={}) noexcept -> std::string
Substitutes variable values by using translate, from src.
auto substitute_variables (const std::string &str, const span< const std::string > strings, const variable_substitution_options={}) noexcept -> std::string
Substitutes variable values by using translate, from src into dst.
auto substitute_variables (const std::string &str, const std::map< std::string, std::string, str_view_less > &dictionary, const variable_substitution_options={}) noexcept -> std::string
Substitutes variable values by using translate, from src.
template<typename T >
static constexpr auto seconds_ (const T value) noexcept -> seconds_t< T >
Creates a tagged quantity storing value in seconds.
template<typename T >
static constexpr auto radians_ (const T value) noexcept -> radians_t< T >
Creates a tagged quantity storing value in radians.
template<typename T >
static constexpr auto right_angles_ (const T value) noexcept
Creates a tagged quantity in units of right angle.
static constexpr auto right_angle_ () noexcept
Creates a tagged quantity a right angle value.
template<typename T >
static constexpr auto turns_ (const T value) noexcept
Creates a tagged quantity in full turn units.
template<typename T >
static constexpr auto degrees_ (const T value) noexcept -> degrees_t< T >
Creates a tagged quantity storing value in degrees.
template<typename T >
static constexpr auto kelvins_ (const T value) noexcept -> kelvins_t< T >
Creates a tagged quantity storing value in kelvins.
template<typename T >
static auto extract (optional_reference_wrapper< T > ref) noexcept -> T &
Overload of extract for optional_reference_wrapper.
template<typename R , typename P >
constexpr auto adjusted_duration (std::chrono::duration< R, P > d, memory_access_rate mem_access=memory_access_rate::medium) noexcept
Adjusts time duration in cases program execution is slowed down.
template<typename T , std::size_t N>
static constexpr auto array_size (const T(&)[N]) noexcept
Returns the number of elements in the array passed as argument.
static auto embed (const identifier res_id, const string_view src_path) noexcept -> embedded_resource
Triggers the embedding of data from a file on the specified path.
template<typename T , typename Backend >
auto deserialize (T &value, Backend &backend) noexcept -> deserialization_errors requires(std::is_base_of_v< deserializer_backend, Backend >)
Deserializes a value with the specified serialization backend.
template<typename T , typename Backend >
auto serialize (const T &value, Backend &backend) noexcept -> serialization_errors requires(std::is_base_of_v< serializer_backend, Backend >)
Serializes a value with the specified serialization backend.
template<typename T >
static auto get_errors (const serialization_result< T > &result) noexcept -> serialization_errors
Returns the error bitfield from a serialization result.
template<typename T >
static auto get_errors (const deserialization_result< T > &result) noexcept -> deserialization_errors
Returns the error bitfield from a deserialization result.
template<identifier_t SerializerId, typename T , typename Selector = default_selector_t>
constexpr auto serialize_buffer_for (const T &inst, Selector sel={}) noexcept
Returns a buffer large enough for the serialization of the specified instance.
template<span_size_t N>
static auto operator% (format_string_and_list< N > &&fsal, std::string &&val) noexcept -> format_string_and_list< N+1 >
Operator for adding variable name and value for string formatting.
static auto format (std::string &&fmt_str) noexcept -> format_string_and_list< 0 >
Takes a format string, returns an object for variable specification.
template<typename C , typename T , typename A , typename P1 , typename P2 , typename S1 , typename S2 >
auto string_replace (std::basic_string< C, T, A > &str, const memory::basic_span< const C, P1, S1 > from, const memory::basic_span< const C, P2, S2 > to) noexcept -> std::basic_string< C, T, A > &
Replaces all occurrences of from with to in the given string.
template<typename C , typename T , typename A , typename P1 , typename P2 , typename S1 , typename S2 >
auto string_replace (std::basic_string< C, T, A > &str, const span< const std::tuple< basic_string_span< const C, P1, S1 >, basic_string_span< const C, P2, S2 >>> dict) noexcept -> std::basic_string< C, T, A > &
Replaces all occurrences of the string specifed in the dictionary.
static auto store_data_with_size (const memory::const_block src, memory::block dst) noexcept -> memory::block
Encodes the size of the source block into destination, copies data afterwards.
static auto skip_data_with_size (const memory::const_block src) noexcept -> span_size_t
In a block starting with sub-block with size returns the size of the sub-block.
static auto get_data_with_size (const memory::block src) noexcept -> memory::block
Extracts a sub-block from a larger mutable block with encoded sub-block size.
static auto get_data_with_size (const memory::const_block src) noexcept -> memory::const_block
Extracts a sub-block from a larger const block with encoded sub-block size.
template<typename Function >
static void for_each_data_with_size (memory::const_block src, Function function) noexcept
In a larger block with sub-blocks with size, calls function on each sub-block.
template<typename T , typename P , typename L >
auto operator<< (std::ostream &out, const basic_valid_if< T, P, L > &v) -> auto &
Operator for writing values of basic_valid_if to output streams.
Variables
static constexpr nothing_t nothing
Constant of nothing_t type.
constexpr const default_selector_t default_selector
The default overload selector constant.
constexpr const construct_from_t construct_from
The construct-from tag-dispatch constant.
constexpr const immediate_function_t immediate_function
The use immediate function tag-dispatch constant.
static constexpr const indeterminate_t indeterminate
Constant representing unspecified tribool value.
template<typename T >
constexpr const bool has_entry_adapter_v
Trait indicating if there is a log/console entry adapter for type T.
template<log_event_severity severity>
static constexpr const bool is_log_level_enabled_v
Compile-time trait indicating if the specified log severity is enabled.
template<typename T1 , typename T2 >
static constexpr const auto mp_plus_v
Addition operation on types representing numbers.
template<typename T1 , typename T2 >
static constexpr const auto mp_minus_v
Subtraction operation on types representing numbers.
template<typename T1 >
static constexpr const auto mp_negate_v
Unary negation operation on types representing numbers.
template<typename TL >
static constexpr const auto mp_is_empty_v
Trait indicating whether a type list is empty.
template<typename TL , typename T >
static constexpr const auto mp_contains_v
Trait indicating whether a type list contains a specified type.
Detailed Description
Common code is placed in this namespace.
Typedef Documentation
extracted_type_t
template<typename T > using eagine::extracted_type_t = typedef std::remove_cv_t<typename extract_traits< std::remove_cv_t<std::remove_reference_t<T> >>::value_type>
Returns the value type of an extractable.
See also
extract
Enumeration Type Documentation
console_entry_kind
enum eagine::console_entry_kind strong
Console entry kind enumeration.
Enumerator
stat
Statistic entries.
info
Informational entries.
warning
Warning entries, indicating potential problems.
error
Error entries, indicating serious problems.
memory_access_rate
enum eagine::memory_access_rate strong
Enumeration indicating (estimated) memory access rate.
Enumerator
minimal
Minimal to none memory access.
low
Low memory access rate.
medium
Average access rate.
high
Above average to high access rate.
very_high
Very high access rate.
Function Documentation
config_git_branch()
EAGINE_LIB_FUNC auto eagine::config_git_branch () -> valid_if_not_empty<string_view> noexcept
Returns the name of the git branch from which the executable is built.
See also
config_git_date
config_git_hash_id
config_git_describe
config_git_date()
EAGINE_LIB_FUNC auto eagine::config_git_date () -> valid_if_not_empty<string_view> noexcept
Returns the date of the commit from which the executable is built.
See also
config_git_hash_id
config_git_describe()
EAGINE_LIB_FUNC auto eagine::config_git_describe () -> valid_if_not_empty<string_view> noexcept
Returns the description of the commit from which the executable is built.
See also
config_git_date
config_git_hash_id
config_git_branch
config_git_hash_id()
EAGINE_LIB_FUNC auto eagine::config_git_hash_id () -> valid_if_not_empty<string_view> noexcept
Returns the hash of the commit from which the executable is built.
See also
config_git_date
config_git_branch
config_git_version()
EAGINE_LIB_FUNC auto eagine::config_git_version () -> valid_if_not_empty<string_view> noexcept
Returns the version number as string.
See also
config_git_version_major
config_git_version_minor
config_git_version_patch
config_git_version_commit
config_git_version_tuple
config_git_version_commit()
EAGINE_LIB_FUNC auto eagine::config_git_version_commit () -> valid_if_nonnegative<int> noexcept
Returns commit version number.
See also
config_git_version_major
config_git_version_minor
config_git_version_patch
config_git_version_tuple
config_git_version_major()
EAGINE_LIB_FUNC auto eagine::config_git_version_major () -> valid_if_nonnegative<int> noexcept
Returns major version number.
See also
config_git_version_minor
config_git_version_patch
config_git_version_commit
config_git_version_tuple
config_git_version_minor()
EAGINE_LIB_FUNC auto eagine::config_git_version_minor () -> valid_if_nonnegative<int> noexcept
Returns minor version number.
See also
config_git_version_major
config_git_version_patch
config_git_version_commit
config_git_version_tuple
config_git_version_patch()
EAGINE_LIB_FUNC auto eagine::config_git_version_patch () -> valid_if_nonnegative<int> noexcept
Returns patch version number.
See also
config_git_version_major
config_git_version_minor
config_git_version_commit
config_git_version_tuple
config_git_version_tuple()
auto eagine::config_git_version_tuple () -> std::tuple<int, int, int, int> noexcept
Returns the complete version number as a tuple (major, minor, patch, commit).
See also
config_git_version_major
config_git_version_minor
config_git_version_patch
config_git_version_commit
config_os_code_name()
EAGINE_LIB_FUNC auto eagine::config_os_code_name () -> valid_if_not_empty<string_view> noexcept
Returns the code-name of the OS on which the executable is built.
See also
config_os_name
config_os_name()
EAGINE_LIB_FUNC auto eagine::config_os_name () -> valid_if_not_empty<string_view> noexcept
Returns the name of the OS on which the executable is built.
See also
config_os_code_name
extract() [1/10]
template<typename T , typename P , typename L > static constexpr auto eagine::extract (basic_valid_if< T, P, L > && opt) -> T&& static constexpr noexcept
Overload of extract for conditionally valid values.
Precondition
opt.is_valid()
extract() [2/10]
template<typename T , typename P , typename L > static constexpr auto eagine::extract (basic_valid_if< T, P, L > & opt) -> T& static constexpr noexcept
Overload of extract for conditionally valid values.
Precondition
opt.is_valid()
Referenced by eagine::shared_executable_module::find().
extract() [3/10]
template<typename T , typename P , typename L > static constexpr auto eagine::extract (const basic_valid_if< T, P, L > & opt) -> const T& static constexpr noexcept
Overload of extract for conditionally valid values.
Precondition
opt.is_valid()
Referenced by eagine::msgbus::remote_instance::build(), eagine::msgbus::remote_instance::compiler(), eagine::msgbus::remote_host::ram_usage(), eagine::msgbus::remote_host::ram_usage_change(), substitute_variable_into(), eagine::msgbus::remote_host::swap_usage(), eagine::msgbus::remote_host::swap_usage_change(), and eagine::build_info::version_at_least().
extract() [4/10]
template<typename T > static constexpr auto eagine::extract (const std::optional< T > & opt) -> auto& static constexpr noexcept
Checks ptr and dereferences it.
Precondition
has_value(opt)
extract() [5/10]
template<typename T > static constexpr auto eagine::extract (const std::shared_ptr< T > & ptr) -> auto& static constexpr noexcept
Checks ptr and dereferences it.
Precondition
has_value(ptr)
extract() [6/10]
template<typename T , typename D > static constexpr auto eagine::extract (const std::unique_ptr< T, D > & ptr) -> const T& static constexpr noexcept
Checks ptr and dereferences it.
Precondition
has_value(ptr)
extract() [7/10]
template<typename T > static constexpr auto eagine::extract (std::optional< T > & opt) -> auto& static constexpr noexcept
Checks ptr and dereferences it.
Precondition
has_value(opt)
extract() [8/10]
template<typename T > static constexpr auto eagine::extract (std::shared_ptr< T > & ptr) -> auto& static constexpr noexcept
Checks ptr and dereferences it.
Precondition
has_value(ptr)
extract() [9/10]
template<typename T , typename D > static constexpr auto eagine::extract (std::unique_ptr< T, D > & ptr) -> T& static constexpr noexcept
Checks ptr and dereferences it.
Precondition
has_value(ptr)
extract() [10/10]
template<typename T > static constexpr auto eagine::extract (T * ptr) -> T& static constexpr noexcept
Checks ptr and dereferences it.
Precondition
has_value(ptr)
Examples
app/001_basic_info/main.cpp, app/001_clear/main.cpp, app/002_spectrum/main.cpp, app/003_checker/main.cpp, app/004_triangle/main.cpp, app/007_cube/main.cpp, app/008_yaml_shape/main.cpp, app/009_json_shape/main.cpp, app/010_newton/main.cpp, app/011_mandelbrot/main.cpp, app/012_atomic_counters/main.cpp, app/013_tiling/main.cpp, app/014_voronoi/main.cpp, app/015_worley/main.cpp, app/016_torus/main.cpp, app/017_occlusion/main.cpp, app/018_uv_map_barrel/main.cpp, app/018_uv_map_crate/main.cpp, app/018_uv_map_hydrant/main.cpp, app/019_scaled_cubes/main.cpp, app/020_bezier_patch/main.cpp, app/021_cel_shading/main.cpp, app/022_single_pass_edges/main.cpp, app/023_sketch/main.cpp, app/024_overdraw/main.cpp, app/026_halo/main.cpp, app/028_compute_particles/main.cpp, app/029_furry_torus/main.cpp, app/030_stencil_shadow/main.cpp, app/031_tessellation/main.cpp, app/032_translucent_arrow/main.cpp, app/035_brick_torus/main.cpp, app/037_lantern/main.cpp, app/040_metaballs/main.cpp, eagine/c_api_wrap.cpp, eagine/ecs/elements/init.cpp, eagine/extract.cpp, eagine/from_string.cpp, eagine/limit_cast.cpp, eagine/msgbus/007_ping.cpp, eagine/msgbus/014_tracker.cpp, eagine/sslplus/003_verify_cert.cpp, eagine/sslplus/004_verify_cert.cpp, eagine/system_info.cpp, eglplus/003_list_extensions.cpp, eglplus/008_list_extensions.cpp, oalplus/005_hello_world.cpp, and oglplus/001_info.cpp.
Referenced by eagine::msgbus::remote_instance::application_name(), eagine::msgbus::remote_node::average_message_age(), eagine::msgbus::node_connection::block_usage_ratio(), eagine::msgbus::remote_instance::build(), eagine::msgbus::node_connection::bytes_per_second(), eagine::msgbus::remote_instance::compiler(), eagine::msgbus::remote_host::cpu_concurrent_threads(), eagine::msgbus::remote_node::description(), eagine::msgbus::remote_node::display_name(), eagine::msgbus::remote_node::dropped_messages(), eagine::msgbus::remote_host::free_ram_size(), eagine::msgbus::remote_host::free_ram_size_change(), eagine::msgbus::remote_host::free_swap_size(), eagine::msgbus::remote_host::free_swap_size_change(), eagine::msgbus::remote_node::has_endpoint_info(), eagine::msgbus::remote_instance::host(), eagine::msgbus::remote_node::host(), eagine::msgbus::remote_node::host_id(), eagine::msgbus::remote_node::instance(), eagine::msgbus::remote_node::instance_id(), eagine::msgbus::remote_host::is_alive(), eagine::msgbus::remote_instance::is_alive(), eagine::msgbus::remote_node::is_bridge_node(), eagine::msgbus::remote_node::is_pingable(), eagine::msgbus::remote_node::is_responsive(), eagine::msgbus::remote_node::is_router_node(), eagine::msgbus::node_connection::kind(), eagine::msgbus::remote_node::kind(), eagine::msgbus::remote_host::long_average_load(), eagine::msgbus::remote_host::long_average_load_change(), eagine::msgbus::remote_host::max_temperature(), eagine::msgbus::remote_host::max_temperature_change(), eagine::msgbus::remote_node::messages_per_second(), eagine::msgbus::remote_host::min_temperature(), eagine::msgbus::remote_host::min_temperature_change(), eagine::msgbus::remote_host::name(), eagine::msgbus::remote_node::ping_roundtrip_time(), eagine::msgbus::remote_node::ping_success_rate(), eagine::msgbus::remote_host::power_supply(), eagine::msgbus::remote_node::received_messages(), register_progress_observer(), reset_progress_update_callback(), eagine::msgbus::remote_node::sent_messages(), eagine::msgbus::remote_node::set_ping_interval(), set_progress_update_callback(), eagine::msgbus::remote_host::short_average_load(), eagine::msgbus::remote_host::short_average_load_change(), eagine::msgbus::remote_node::subscribes_to(), eagine::msgbus::remote_host::total_ram_size(), eagine::msgbus::remote_host::total_swap_size(), unregister_progress_observer(), and eagine::msgbus::remote_node::uptime().
Copyright © 2015-2022 Mat Chochlk.
<chochlik -at -gmail.com>
Documentation generated on Wed May 18 2022 by Doxygen (version 1.9.1).