eagine::console_backend Struct Reference
EAGine (0.87.0) a C++ wrapper for rendering APIs
eagine::console_backend Struct Reference abstract
Interface for console backend implementations.
#include <eagine/console/backend.hpp>
Public Member Functions
virtual auto allocator () noexcept -> memory::shared_byte_allocator=0
The memory allocator used by the console backend.
virtual auto type_id () noexcept -> identifier=0
The backend type identifier.
virtual auto entry_backend (const identifier source, const console_entry_kind kind) noexcept -> std::tuple< console_backend *, console_entry_id_t >=0
Returns a pointer to the actual backend to be used by console_entry.
virtual auto begin_message (const identifier source, const console_entry_id_t parent_id, const console_entry_id_t entry_id, const console_entry_kind kind, const string_view format) noexcept -> bool=0
Begins a new console message.
virtual void add_identifier (const identifier arg, const identifier tag, const identifier value) noexcept=0
Add argument with identifier value.
virtual void add_bool (const identifier arg, const identifier tag, const bool value) noexcept=0
Add argument with boolean value.
virtual void add_integer (const identifier arg, const identifier tag, const std::intmax_t value) noexcept=0
Add argument with signed integer value.
virtual void add_unsigned (const identifier arg, const identifier tag, const std::uintmax_t value) noexcept=0
Add argument with unsigned integer value.
virtual void add_float (const identifier arg, const identifier tag, const double value) noexcept=0
Add argument with floating-point value.
virtual void add_duration (const identifier arg, const identifier tag, const std::chrono::duration< float > value) noexcept=0
Add argument with time duration value.
virtual void add_string (const identifier arg, const identifier tag, const string_view value) noexcept=0
Add argument with string value.
virtual void add_blob (const identifier arg, const identifier tag, const memory::const_block value) noexcept=0
Add argument with BLOB `value.
virtual void add_separator () noexcept=0
Prints a message separator.
virtual void finish_message () noexcept=0
Finishes the current console message.
virtual void to_be_continued (const console_entry_id_t parent_id, const console_entry_id_t id) noexcept=0
Indicates that the entry will be followed by some sub-entries.
virtual void concluded (const console_entry_id_t) noexcept=0
Indicates that no other sub entries will be appended to previous entry.
Public Member Functions inherited from eagine::interface< console_backend >
constexpr interface (const interface &)=delete
Not copyable.
auto operator= (interface &&)=delete
Not move assignable.
auto operator= (const interface &)=delete
Not copy assignable.
Additional Inherited Members
Protected Member Functions inherited from eagine::interface< console_backend >
constexpr interface () noexcept=default
Default constructible by derived.
constexpr interface (interface &&) noexcept=default
Move constructible by derived.
Detailed Description
Interface for console backend implementations.
Member Function Documentation
add_blob()
virtual void eagine::console_backend::add_blob (const identifier arg, const identifier tag, const memory::const_block value) pure virtual noexcept
Add argument with BLOB `value.
Parameters
arg the argument name identifier.
tag the argument type identifier.
value the value of the argument.
Referenced by eagine::console_entry::arg().
add_bool()
virtual void eagine::console_backend::add_bool (const identifier arg, const identifier tag, const bool value) pure virtual noexcept
Add argument with boolean value.
Parameters
arg the argument name identifier.
tag the argument type identifier.
value the value of the argument.
Referenced by eagine::console_entry::arg().
add_duration()
virtual void eagine::console_backend::add_duration (const identifier arg, const identifier tag, const std::chrono::duration< float > value) pure virtual noexcept
Add argument with time duration value.
Parameters
arg the argument name identifier.
tag the argument type identifier.
value the value of the argument.
Referenced by eagine::console_entry::arg().
add_float()
virtual void eagine::console_backend::add_float (const identifier arg, const identifier tag, const double value) pure virtual noexcept
Add argument with floating-point value.
Parameters
arg the argument name identifier.
tag the argument type identifier.
value the value of the argument.
add_identifier()
virtual void eagine::console_backend::add_identifier (const identifier arg, const identifier tag, const identifier value) pure virtual noexcept
Add argument with identifier value.
Parameters
arg the argument name identifier.
tag the argument type identifier.
value the value of the argument.
Referenced by eagine::console_entry::arg().
add_integer()
virtual void eagine::console_backend::add_integer (const identifier arg, const identifier tag, const std::intmax_t value) pure virtual noexcept
Add argument with signed integer value.
Parameters
arg the argument name identifier.
tag the argument type identifier.
value the value of the argument.
add_separator()
virtual void eagine::console_backend::add_separator () pure virtual noexcept
Prints a message separator.
See also
begin_message
finish_message
Referenced by eagine::console_entry::separate().
add_string()
virtual void eagine::console_backend::add_string (const identifier arg, const identifier tag, const string_view value) pure virtual noexcept
Add argument with string value.
Parameters
arg the argument name identifier.
tag the argument type identifier.
value the value of the argument.
Referenced by eagine::console_entry::arg().
add_unsigned()
virtual void eagine::console_backend::add_unsigned (const identifier arg, const identifier tag, const std::uintmax_t value) pure virtual noexcept
Add argument with unsigned integer value.
Parameters
arg the argument name identifier.
tag the argument type identifier.
value the value of the argument.
begin_message()
virtual auto eagine::console_backend::begin_message (const identifier source, const console_entry_id_t parent_id, const console_entry_id_t entry_id, const console_entry_kind kind, const string_view format) -> bool pure virtual noexcept
Begins a new console message.
Parameters
source the identifier of the entry source object.
kind the kind of the entry message.
format the format string of the message. May contain argument placeholders.
See also
finish_message
add_separator
Referenced by eagine::console_entry::~console_entry().
concluded()
virtual void eagine::console_backend::concluded (const console_entry_id_t) pure virtual noexcept
Indicates that no other sub entries will be appended to previous entry.
See also
to_be_continued
entry_backend()
virtual auto eagine::console_backend::entry_backend (const identifier source, const console_entry_kind kind) -> std::tuple< console_backend *, console_entry_id_t > pure virtual noexcept
Returns a pointer to the actual backend to be used by console_entry.
Parameters
source the identifier of the source object.
kind the kind of the entry.
finish_message()
virtual void eagine::console_backend::finish_message () pure virtual noexcept
Finishes the current console message.
See also
begin_message
add_separator
Referenced by eagine::console_entry::~console_entry().
to_be_continued()
virtual void eagine::console_backend::to_be_continued (const console_entry_id_t parent_id, const console_entry_id_t id) pure virtual noexcept
Indicates that the entry will be followed by some sub-entries.
See also
concluded
The documentation for this struct was generated from the following file:
eagine/console/backend.hpp
Copyright © 2015-2022 Matúš Chochlík.
<chochlik -at -gmail.com>
Documentation generated on Wed May 18 2022 by Doxygen (version 1.9.1).