eagine::shapes::generator Struct Reference
EAGine (0.87.0) a C++ wrapper for rendering APIs
eagine::shapes::generator Struct Reference abstract
Shape generators and loaders
Interface for shape loaders or generators.
#include <eagine/shapes/generator.hpp>
Public Member Functions
virtual auto attrib_kinds () noexcept -> vertex_attrib_kinds=0
Returns the set of vertex attributes supported by this generator.
auto has (const vertex_attrib_kind attrib) noexcept
Tests if the specified attribute is supported by this generator.
auto supported_attrib_count () noexcept -> span_size_t
Returns the count of vertex attributes supported by this generator.
void for_each_attrib (callable_ref< void(vertex_attrib_kinds, vertex_attrib_name_and_kind)> func)
Calls the specified function for each attribute kind.
virtual auto enable (const generator_capability cap, const bool value=true) noexcept -> bool=0
Enables or disables the specified generator capability.
auto disable (const generator_capability cap) noexcept
Disables the specified generator capability.
virtual auto is_enabled (const generator_capability cap) noexcept -> bool=0
Indicates if the specified generator capability is enabled.
auto indexed_drawing (const drawing_variant var) noexcept -> bool
Indicates if indexed drawing is enabled.
auto strips_allowed () noexcept -> bool
Indicates if element strips are enabled.
auto fans_allowed () noexcept -> bool
Indicates if element fans are enabled.
auto primitive_restart () noexcept -> bool
Indicates if primitive restart is enabled.
virtual auto vertex_count () -> span_size_t=0
Returns the shaped vertex count.
virtual auto attribute_variants (const vertex_attrib_kind) -> span_size_t=0
Returns the count of shape attribute variants.
virtual auto variant_name (const vertex_attrib_variant vav) -> string_view=0
Returns the name of the specified attribute variant.
auto find_variant (const vertex_attrib_kind attrib, const string_view name) -> vertex_attrib_variant
Finds attribute variant by kind and name.
auto find_variant (const string_view name) -> vertex_attrib_variant
Finds attribute variant by name.
virtual auto values_per_vertex (const vertex_attrib_variant) -> span_size_t=0
Returns the number of values per vertex for the specified variant.
auto value_count (const vertex_attrib_variant vav) -> span_size_t
Returns the total number of values for the specified attribute variant.
virtual auto attrib_type (const vertex_attrib_variant vav) -> attrib_data_type=0
Returns the attribute data type for the specified variant.
virtual auto is_attrib_integral (const vertex_attrib_variant vav) -> bool=0
Indicates if the specified variant attribute values are integral.
virtual auto is_attrib_normalized (const vertex_attrib_variant vav) -> bool=0
Indicates if the specified variant attribute values should be normalized.
virtual void attrib_values (const vertex_attrib_variant, span< byte > dest)=0
Fetches the vertex attribute data for the specified variant as bytes.
virtual void attrib_values (const vertex_attrib_variant, span< std::int16_t >)=0
Fetches the vertex attribute data for the specified variant as integers.
virtual void attrib_values (const vertex_attrib_variant, span< std::int32_t >)=0
Fetches the vertex attribute data for the specified variant as integers.
virtual void attrib_values (const vertex_attrib_variant, span< std::uint16_t >)=0
Fetches the vertex attribute data for the specified variant as integers.
virtual void attrib_values (const vertex_attrib_variant, span< std::uint32_t >)=0
Fetches the vertex attribute data for the specified variant as integers.
virtual void attrib_values (const vertex_attrib_variant, span< float > dest)=0
Fetches the vertex attribute data for the specified variant as floats.
virtual auto draw_variant_count () -> span_size_t=0
Returns the count of possible shape draw variants.
auto draw_variant (const span_size_t index) -> drawing_variant
Returns the identifier of the drawing variant at the specified index.
virtual auto index_type (const drawing_variant) -> index_data_type=0
Returns the index data type for the specified draw variant.
auto index_type () -> index_data_type
Returns the index data type for the default draw variant.
virtual auto index_count (const drawing_variant) -> span_size_t=0
Returns the index count for the specified drawing variant.
auto index_count ()
Returns the index count for the default drawing variant.
virtual void indices (const drawing_variant, span< std::uint8_t > dest)=0
Fetches the index data for the specified drawing variant.
void indices (span< std::uint8_t > dest)
Fetches the index data for the default drawing variant.
virtual void indices (const drawing_variant, span< std::uint16_t > dest)=0
Fetches the index data for the specified drawing variant.
void indices (span< std::uint16_t > dest)
Fetches the index data for the default drawing variant.
virtual void indices (const drawing_variant, span< std::uint32_t > dest)=0
Fetches the index data for the specified drawing variant.
void indices (span< std::uint32_t > dest)
Fetches the index data for the default drawing variant.
virtual auto operation_count (const drawing_variant) -> span_size_t=0
Returns the number of drawing instructions for the specified variant.
auto operation_count ()
Returns the number of drawing instructions for the default variant.
virtual void instructions (const drawing_variant, span< draw_operation > dest)=0
Fetches the drawing operations for the specified drawing variant.
void instructions (span< draw_operation > dest)
Fetches the drawing operations for the default drawing variant.
virtual auto bounding_sphere () -> math::sphere< float, true >
Returns the bounding sphere for the generated shape.
virtual void for_each_triangle (generator &gen, const drawing_variant var, const callable_ref< void(const shape_face_info &)> callback)
Calls a callback for each triangle in specified drawing variant.
void for_each_triangle (const callable_ref< void(const shape_face_info &)> callback)
Calls a callback for each triangle in the default drawing variant.
auto are_consistent (const random_attribute_values &values) noexcept -> bool
Checks if the structure for random values is consistent.
virtual void random_surface_values (const random_attribute_values &)
Generates attribute values at random surface points.
virtual void ray_intersections (generator &, const drawing_variant, const span< const math::line< float, true >> rays, span< optionally_valid< float >> intersections)
Calculates the intersections of the shape geometry with a ray.
void ray_intersections (const span< const math::line< float, true >> rays, span< optionally_valid< float >> intersections)
Calculates the intersections of the shape geometry with a ray.
auto ray_intersection (const drawing_variant var, const math::line< float, true > &ray) -> optionally_valid< float >
Returns the parameter for the nearest intersection with a ray.
auto ray_intersection (const math::line< float, true > &ray) -> optionally_valid< float >
Returns the parameter for the nearest intersection with a ray.
Public Member Functions inherited from eagine::interface< generator >
constexpr interface (const interface &)=delete
Not copyable.
auto operator= (interface &&)=delete
Not move assignable.
auto operator= (const interface &)=delete
Not copy assignable.
Additional Inherited Members
Protected Member Functions inherited from eagine::interface< generator >
constexpr interface () noexcept=default
Default constructible by derived.
constexpr interface (interface &&) noexcept=default
Move constructible by derived.
Detailed Description
Interface for shape loaders or generators.
Member Function Documentation
are_consistent()
auto eagine::shapes::generator::are_consistent (const random_attribute_values & values) -> bool inline noexcept
Checks if the structure for random values is consistent.
See also
random_attribute_values
Referenced by random_surface_values().
attrib_kinds()
virtual auto eagine::shapes::generator::attrib_kinds () -> vertex_attrib_kinds pure virtual noexcept
Returns the set of vertex attributes supported by this generator.
See also
attrib_count
Implemented in eagine::shapes::generator_base, eagine::shapes::delegated_gen, and eagine::shapes::cached_gen.
Referenced by supported_attrib_count().
disable()
auto eagine::shapes::generator::disable (const generator_capability cap) inline noexcept
Disables the specified generator capability.
See also
enable
is_enabled
enable()
virtual auto eagine::shapes::generator::enable (const generator_capability cap, const bool value = true) -> bool pure virtual noexcept
Enables or disables the specified generator capability.
See also
disable
is_enabled
Implemented in eagine::shapes::delegated_gen, eagine::shapes::triangle_adjacency_gen, eagine::shapes::generator_base, and eagine::shapes::cached_gen.
Referenced by disable().
for_each_attrib()
void eagine::shapes::generator::for_each_attrib (callable_ref< void(vertex_attrib_kinds, vertex_attrib_name_and_kind)> func) inline
Calls the specified function for each attribute kind.
See also
attrib_kinds
supported_attrib_count
has()
auto eagine::shapes::generator::has (const vertex_attrib_kind attrib) inline noexcept
Tests if the specified attribute is supported by this generator.
See also
attrib_kinds
attrib_count
is_enabled()
virtual auto eagine::shapes::generator::is_enabled (const generator_capability cap) -> bool pure virtual noexcept
Indicates if the specified generator capability is enabled.
See also
enable
disable
Implemented in eagine::shapes::delegated_gen, eagine::shapes::triangle_adjacency_gen, eagine::shapes::generator_base, and eagine::shapes::cached_gen.
Referenced by fans_allowed(), indexed_drawing(), primitive_restart(), and strips_allowed().
random_surface_values()
EAGINE_LIB_FUNC void eagine::shapes::generator::random_surface_values (const random_attribute_values &) virtual
Generates attribute values at random surface points.
See also
are_consistent
supported_attrib_count()
auto eagine::shapes::generator::supported_attrib_count () -> span_size_t inline noexcept
Returns the count of vertex attributes supported by this generator.
See also
attrib_kinds
for_each_attrib
The documentation for this struct was generated from the following files:
eagine/shapes/generator.hpp
eagine/shapes/generator.inl
Copyright © 2015-2022 Mat Chochlk.
<chochlik -at -gmail.com>
Documentation generated on Wed May 18 2022 by Doxygen (version 1.9.1).