eagine::deserializer_data_source Struct Reference
EAGine (0.87.0) a C++ wrapper for rendering APIs
eagine::deserializer_data_source Struct Reference abstract
Serialization and deserialization
Abstract base class for deserialization data sources.
#include <eagine/serialize/data_source.hpp>
Public Member Functions
virtual auto top (span_size_t size) noexcept -> memory::const_block=0
Returns a block covering the specified amount of data of the top.
virtual void pop (span_size_t size) noexcept=0
Returns the specified amount of data of the top of the source.
template<typename Function >
auto scan_until (Function predicate, const span_size_t max, const span_size_t step=256) noexcept -> valid_if_nonnegative< span_size_t >
Returns the position of the first byte where predicate is true.
auto scan_for (const byte what, const span_size_t max, const span_size_t step=256) noexcept -> valid_if_nonnegative< span_size_t >
Returns the position of the first occurrence of the specified byte.
void fetch_all (memory::buffer &dst, const span_size_t step=256) noexcept
Fetches all the remaining data into a buffer.
Public Member Functions inherited from eagine::interface< deserializer_data_source >
constexpr interface (const interface &)=delete
Not copyable.
auto operator= (interface &&)=delete
Not move assignable.
auto operator= (const interface &)=delete
Not copy assignable.
Additional Inherited Members
Protected Member Functions inherited from eagine::interface< deserializer_data_source >
constexpr interface () noexcept=default
Default constructible by derived.
constexpr interface (interface &&) noexcept=default
Move constructible by derived.
Detailed Description
Abstract base class for deserialization data sources.
See also
data_sink
deserializer_backend
Member Function Documentation
pop()
virtual void eagine::deserializer_data_source::pop (span_size_t size) pure virtual noexcept
Returns the specified amount of data of the top of the source.
See also
top
Implemented in eagine::istream_data_source, and eagine::block_data_source.
Referenced by fetch_all().
scan_for()
auto eagine::deserializer_data_source::scan_for (const byte what, const span_size_t max, const span_size_t step = 256) -> valid_if_nonnegative<span_size_t> inline noexcept
Returns the position of the first occurrence of the specified byte.
See also
scan_until
Parameters
what the searched value.
max the maximum number of bytes from the top to scan.
step how much data should be fetched per scan iteration.
scan_until()
template<typename Function > auto eagine::deserializer_data_source::scan_until (Function predicate, const span_size_t max, const span_size_t step = 256) -> valid_if_nonnegative<span_size_t> inline noexcept
Returns the position of the first byte where predicate is true.
See also
scan_for
Parameters
predicate the function indicating where to stop the scan.
max the maximum number of bytes from the top to scan.
step how much data should be fetched per scan iteration.
top()
virtual auto eagine::deserializer_data_source::top (span_size_t size) -> memory::const_block pure virtual noexcept
Returns a block covering the specified amount of data of the top.
See also
pop
scan_until
scan_for
Implemented in eagine::istream_data_source, and eagine::block_data_source.
Referenced by fetch_all(), and scan_until().
The documentation for this struct was generated from the following file:
eagine/serialize/data_source.hpp
Copyright © 2015-2022 Matúš Chochlík.
<chochlik -at -gmail.com>
Documentation generated on Wed May 18 2022 by Doxygen (version 1.9.1).