eagine::logger_backend Struct Reference
EAGine (0.87.0) a C++ wrapper for rendering APIs
eagine::logger_backend Struct Reference abstract
Logging
Interface for logging backend implementations.
#include <eagine/logging/backend.hpp>
Public Member Functions
virtual auto allocator () noexcept -> memory::shared_byte_allocator=0
The memory allocator used by the logger backend.
virtual auto type_id () noexcept -> identifier=0
The backend type identifier.
virtual auto entry_backend (const identifier source, const log_event_severity severity) noexcept -> logger_backend *=0
Returns a pointer to the actual backend to be used by an log_entry.
virtual void enter_scope (const identifier scope) noexcept=0
Enters logging scope.
virtual void leave_scope (const identifier scope) noexcept=0
Leaves logging scope.
virtual void set_description (const identifier source, const logger_instance_id instance, const string_view display_name, const string_view description) noexcept=0
Sets the user-readable description for the logger object.
virtual auto begin_message (const identifier source, const identifier tag, const logger_instance_id instance, const log_event_severity severity, const string_view format) noexcept -> bool=0
Begins a new logging message.
virtual void add_nothing (const identifier arg, const identifier tag) noexcept=0
Add valueless (name-only) argument.
virtual void add_identifier (const identifier arg, const identifier tag, const identifier value) noexcept=0
Add argument with identifier value.
virtual void add_bool (const identifier arg, const identifier tag, const bool value) noexcept=0
Add argument with boolean value.
virtual void add_integer (const identifier arg, const identifier tag, const std::intmax_t value) noexcept=0
Add argument with signed integer value.
virtual void add_unsigned (const identifier arg, const identifier tag, const std::uintmax_t value) noexcept=0
Add argument with unsigned integer value.
virtual void add_float (const identifier arg, const identifier tag, const float value) noexcept=0
Add argument with floating-point value.
virtual void add_float (const identifier arg, const identifier tag, const float min, const float value, const float max) noexcept=0
Add argument with floating-point value with minimum and maximum.
virtual void add_duration (const identifier arg, const identifier tag, const std::chrono::duration< float > value) noexcept=0
Add argument with time duration value.
virtual void add_string (const identifier arg, const identifier tag, const string_view value) noexcept=0
Add argument with string value.
virtual void add_blob (const identifier arg, const identifier tag, const memory::const_block value) noexcept=0
Add argument with BLOB value.
template<typename T >
void add_adapted (const identifier arg, const T &value) requires(has_entry_adapter_v< T >)
Add argument with value having type adaptable to log entry.
virtual void finish_message () noexcept=0
Finishes the current logging message.
virtual void finish_log () noexcept=0
Finishes the current log.
virtual void log_chart_sample (const identifier source, const logger_instance_id instance, const identifier series, const float value) noexcept=0
Adds a chart/graph sample to the log.
Public Member Functions inherited from eagine::interface< logger_backend >
constexpr interface (const interface &)=delete
Not copyable.
auto operator= (interface &&)=delete
Not move assignable.
auto operator= (const interface &)=delete
Not copy assignable.
Additional Inherited Members
Protected Member Functions inherited from eagine::interface< logger_backend >
constexpr interface () noexcept=default
Default constructible by derived.
constexpr interface (interface &&) noexcept=default
Move constructible by derived.
Detailed Description
Interface for logging backend implementations.
Member Function Documentation
add_adapted()
template<typename T > void eagine::logger_backend::add_adapted (const identifier arg, const T & value) inline
Add argument with value having type adaptable to log entry.
Parameters
arg the argument name identifier.
value the value of the argument.
See also
has_entry_adapter_v
add_blob()
virtual void eagine::logger_backend::add_blob (const identifier arg, const identifier tag, const memory::const_block value) pure virtual noexcept
Add argument with BLOB value.
Parameters
arg the argument name identifier.
tag the argument type identifier.
value the value of the argument.
Referenced by eagine::log_entry::arg().
add_bool()
virtual void eagine::logger_backend::add_bool (const identifier arg, const identifier tag, const bool value) pure virtual noexcept
Add argument with boolean value.
Parameters
arg the argument name identifier.
tag the argument type identifier.
value the value of the argument.
add_duration()
virtual void eagine::logger_backend::add_duration (const identifier arg, const identifier tag, const std::chrono::duration< float > value) pure virtual noexcept
Add argument with time duration value.
Parameters
arg the argument name identifier.
tag the argument type identifier.
value the value of the argument.
Referenced by eagine::log_entry::arg().
add_float() [1/2]
virtual void eagine::logger_backend::add_float (const identifier arg, const identifier tag, const float min, const float value, const float max) pure virtual noexcept
Add argument with floating-point value with minimum and maximum.
Parameters
arg the argument name identifier.
tag the argument type identifier.
value the value of the argument.
min the minimum limit for the value.
max the maximum limit for the value.
Referenced by eagine::log_entry::arg().
add_float() [2/2]
virtual void eagine::logger_backend::add_float (const identifier arg, const identifier tag, const float value) pure virtual noexcept
Add argument with floating-point value.
Parameters
arg the argument name identifier.
tag the argument type identifier.
value the value of the argument.
Referenced by eagine::log_entry::arg().
add_identifier()
virtual void eagine::logger_backend::add_identifier (const identifier arg, const identifier tag, const identifier value) pure virtual noexcept
Add argument with identifier value.
Parameters
arg the argument name identifier.
tag the argument type identifier.
value the value of the argument.
Referenced by eagine::log_entry::arg().
add_integer()
virtual void eagine::logger_backend::add_integer (const identifier arg, const identifier tag, const std::intmax_t value) pure virtual noexcept
Add argument with signed integer value.
Parameters
arg the argument name identifier.
tag the argument type identifier.
value the value of the argument.
Referenced by eagine::log_entry::arg().
add_nothing()
virtual void eagine::logger_backend::add_nothing (const identifier arg, const identifier tag) pure virtual noexcept
Add valueless (name-only) argument.
Parameters
arg the argument name identifier.
tag the argument type identifier.
add_string()
virtual void eagine::logger_backend::add_string (const identifier arg, const identifier tag, const string_view value) pure virtual noexcept
Add argument with string value.
Parameters
arg the argument name identifier.
tag the argument type identifier.
value the value of the argument.
Referenced by eagine::log_entry::arg().
add_unsigned()
virtual void eagine::logger_backend::add_unsigned (const identifier arg, const identifier tag, const std::uintmax_t value) pure virtual noexcept
Add argument with unsigned integer value.
Parameters
arg the argument name identifier.
tag the argument type identifier.
value the value of the argument.
Referenced by eagine::log_entry::arg().
begin_message()
virtual auto eagine::logger_backend::begin_message (const identifier source, const identifier tag, const logger_instance_id instance, const log_event_severity severity, const string_view format) -> bool pure virtual noexcept
Begins a new logging message.
Parameters
source the identifier of the source logger object.
tag the identifier of this message type or instance.
instance unique instance id of the source logger object.
severity the log level or severity of the log event.
format the format string of the message. May contain argument placeholders.
Referenced by eagine::log_entry::~log_entry().
entry_backend()
virtual auto eagine::logger_backend::entry_backend (const identifier source, const log_event_severity severity) -> logger_backend * pure virtual noexcept
Returns a pointer to the actual backend to be used by an log_entry.
Parameters
source the identifier of the source logger object.
severity the log level or severity of the log event.
log_chart_sample()
virtual void eagine::logger_backend::log_chart_sample (const identifier source, const logger_instance_id instance, const identifier series, const float value) pure virtual noexcept
Adds a chart/graph sample to the log.
Parameters
source the identifier of the source logger object.
instance unique instance id of the source logger object.
series the identifier of the chart data series.
value the sample value.
The documentation for this struct was generated from the following file:
eagine/logging/backend.hpp
Copyright © 2015-2022 Mat Chochlk.
<chochlik -at -gmail.com>
Documentation generated on Wed May 18 2022 by Doxygen (version 1.9.1).