#!/usr/bin/env bash
# Copyright Matus Chochlik.
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
# https://www.boost.org/LICENSE_1_0.txt
source "$(dirname ${0})/common.sh"

branch=develop

function print_usage() {
	printf "Usage: %s [-b <branch>]\n" "$(basename ${0})"
}

while getopts "b:" optname
do
	case ${optname} in
		b) branch="${OPTARG}";;
		?) print_usage
			exit 1;;
	esac
done

ordered_repo_dirs |\
while read repo_dir
do
	if [[ -f "${repo_dir}/CMakeLists.txt" ]]
	then
		if compgen -G "${repo_dir}/submodules/eagine-*" > /dev/null
		then
			compgen -G "${repo_dir}/submodules/eagine-*" |\
			while read submod_dir
			do
				if [[ -f "${submod_dir}/CMakeLists.txt" ]]
				then
					pushd "${submod_dir}"
					git remote | grep -qxe 'parent' ||\
					git remote add -t "${branch}" parent "../../../$(basename ${submod_dir})"
					popd
				fi
			done
		fi
	fi
done
