#!/usr/bin/env bash
# Copyright Matus Chochlik.
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
# https://www.boost.org/LICENSE_1_0.txt
"$(dirname ${0})/add_remote" \
	-n github \
	-u "git@github.com:matus-chochlik/eagine-%s.git"
