#!/usr/bin/env bash
# Copyright Matus Chochlik.
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
#  http://www.boost.org/LICENSE_1_0.txt
source "$(dirname ${0})/common.sh"

repo_root=$(realpath $(dirname ${0})/..)
sub_remote=$(eagine_default_sub_remote)
remote=$(eagine_default_remote)
branch=develop

function print_usage() {
	printf "Usage: %s [-r <remote>] [-s <submodule-remote>] [-b <branch>]\n" \
		"$(basename ${0})"
}

while getopts "r:s:b:" optname
do
	case ${optname} in
		s) sub_remote="${OPTARG}";;
		r) remote="${OPTARG}";;
		b) branch="${OPTARG}";;
		?) print_usage
			exit 1;;
	esac
done

function do_pull() {
	submod_dir="${1}"
	remote="${2}"
	branch="${3}"

	pushd "${submod_dir}"
	git remote update --prune "${remote}" &&\
	git checkout "${branch}" &&\
	git pull "${remote}" "${branch}"
	popd
}

for repo_dir in "${repo_root}" "${repo_root}/submodules/eagine-"*
do
	do_pull "${repo_dir}" "${remote:-origin}" "${branch}"
	if [[ "${sub_remote}" != "" ]]
	then
		for submod_dir in "${repo_dir}/submodules/eagine-"*
		do
			if [[ -f "${submod_dir}/CMakeLists.txt" ]]
			then do_pull "${submod_dir}" "${sub_remote}" "${branch}"
			fi
		done
	fi
done
