#!/usr/bin/env bash
# Copyright Matus Chochlik.
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
# https://www.boost.org/LICENSE_1_0.txt
source "$(dirname ${0})/common.sh"

repo_root=$(realpath $(dirname ${0})/..)
remote=$(eagine_default_remote)
branch=develop

function print_usage() {
	printf "Usage: %s [-r <remote>] [-b <branch>]\n" "$(basename ${0})"
}

while getopts "r:b:" optname
do
	case ${optname} in
		r) remote="${OPTARG}";;
		b) branch="${OPTARG}";;
		?) print_usage
			exit 1;;
	esac
done

for repo_dir in "${repo_root}" "${repo_root}/submodules/eagine-"*
do
	pushd "${repo_dir}"
	prev_rev="$(git symbolic-ref --short HEAD 2> /dev/null || git rev-parse --short HEAD 2> /dev/null)"
	git checkout "${branch}" &&\
	git push "${remote}" "${branch}"
	if [[ "${prev_rev}" != "" ]]
	then git checkout "${prev_rev}"
	fi
	popd
done
